/**
 * Кастомные / выделенные рунворды (`marked: true`) — «новые в RotW» и т.п.
 * Склеиваются с базовым списком в store вместе с `rotw-runewords.ts`.
 */
export const CUSTOM_RUNEWORDS = [
  {
    id: 94,
    name: {
      ru: "Nightfall",
      en: "Nightfall",
    },
    runes: [1, 33],
    types: [21],
    excluded: "",
    classes: ["Necromancer"],
    patch: "blizzless",
    level: 69,
    ladder: true,
    marked: true,
    stats: {
      ru: [
        "+<span class='varies'>1-10</span> к умению 'Телепортация'",
        "+30% к скорости колдовства",
        "Восстановление маны <span class='varies'>50-100</span>%",
        "+<span class='varies'>50-100</span>% к поиску магических предметов",
        "+60% к шансу блока",
        "+20% к урону от умений яда",
        "+3 к умению 'Скелет' (только для Некромант)",
        "+15 к защите",
        "+1 к радиусу света",
        "Не теряет прочности",
      ],
      en: [
        "+<span class='varies'>1-10</span> To Teleport",
        "+30% Faster Cast Rate",
        "Regenerate Mana <span class='varies'>50-100</span>%",
        "+<span class='varies'>50-100</span>% Better Chance of Getting Magic Items",
        "+60% Increased Chance of Blocking",
        "+20% To Poison Skill Damage",
        "+3 To Raise Skeleton (Necromancer only)",
        "+15 Defense",
        "+1 To Light Radius",
        "Indestructible",
      ],
    },
    complete: false,
  },
  {
    id: 95,
    name: {
      ru: "Молния",
      en: "Lightning",
    },
    runes: [24, 29],
    types: [22],
    excluded: "",
    classes: ["Sorceress"],
    patch: "new",
    level: 61,
    ladder: true,
    marked: true,
    stats: {
      ru: [
        "+3 к умению 'Цепная молния' (только для Волшебница)",
        "+3 к умению 'Молния' (только для Волшебница)",
        "+2 к древу навыков 'Магия молнии' (только для Волшебница)",
        "+25% к скорости колдовства",
        "-10~15% к сопротивлению молнии у врага",
        "+200~300 к мане",
        "+30% к поиску магических предметов",
        "Попадание ослепляет цель",
      ],
      en: [
        "+3 To Chain Lightning (Sorceress only)",
        "+3 To Lightning (Sorceress only)",
        "+2 To Lightning Spells (Sorceress Only)",
        "+25% Faster Cast Rate",
        "-<span class='varies'>10-15</span>% To Enemy Lightning Resistance",
        "+<span class='varies'>200-300</span> To Mana",
        "+30% Better Chance of Getting Magic Items",
        "Hit Blinds Target",
      ],
    },
    complete: false,
  },
  {
    id: 96,
    name: {
      ru: "Зависть",
      en: "Envy",
    },
    runes: [22, 23],
    types: [23],
    excluded: "",
    classes: ["Druid"],
    patch: "new",
    level: 49,
    ladder: true,
    marked: true,
    stats: {
      ru: [
        "+6 к умению 'Поиск предметов'",
        "+2 к древу навыков 'Спутники''(только для Друид)",
        "+8 за уровень к рейтингу атаки (зависит от уровня)",
        "+<span class='varies'>50-75</span>% к поиску магических предметов",
        "30% к скорости атаки",
        "+<span class='varies'>10-15</span>% к скорости колдовства",
        "Требования +30%",
        "+15% ко всем сопротивлениям",
        "Магический урон уменьшен на 7",
      ],
      en: [
        "+6 To Find Item",
        "+2 To Summoning (Druid) (Druid Only)",
        "+8 per Character Lvl to Attack Rating (Based on Character Level)",
        "+<span class='varies'>50-75</span>% Better Chance of Getting Magic Items",
        "30% Increased Attack Speed",
        "+<span class='varies'>10-15</span>% Faster Cast Rate",
        "Requirements +30%",
        "All Resistances +15%",
        "Magic Damage Reduced by 7",
      ],
    },
    complete: false,
  },
  {
    id: 97,
    name: {
      ru: "Голос",
      en: "Voice",
    },
    runes: [8, 14, 16],
    types: [17],
    excluded: "",
    classes: [],
    patch: "new",
    level: 35,
    ladder: true,
    marked: true,
    stats: {
      ru: [
        "+<span class='varies'>2-4</span> к умению 'Воинственный клич' (только для Варвар)",
        "+<span class='varies'>2-6</span> к умению 'Поиск предметов' (только для Варвар)",
        "+2 к умению 'Прыжок' (только для Варвар)",
        "+35% к скорости колдовства",
        "+200 к мане",
        "+<span class='varies'>150-200</span>% к защите",
        "+30% к сопротивлению огню",
        "Восполнение жизни +7",
        "+10 к живучести",
      ],
      en: [
        "+<span class='varies'>2-4</span> To War Cry (Barbarian only)",
        "+<span class='varies'>2-6</span> To Find Item (Barbarian only)",
        "+2 To Leap (Barbarian only)",
        "+35% Faster Cast Rate",
        "+200 To Mana",
        "+<span class='varies'>150-200</span>% Enhanced Defense",
        "Fire Resist +30%",
        "Replenish Life +7",
        "+10 To Vitality",
      ],
    },
    complete: false,
  },
];
