export const REWORKED_RUNEWORDS = [
  {
    id: 9,
    name: {
      ru: "Узор",
      en: "Pattern",
    },
    runes: [7, 9, 10],
    types: [19],
    excluded: "",
    classes: ["Assassin"],
    patch: "2.4",
    level: 23,
    ladder: false,
    reworked: true,
    bugged: {
      status: false,
      message: [],
    },
    stats: {
      ru: [
        "+30% к скорости блока",
        "+(40-80)% к урону",
        "+1-50 урона от молнии",
        "+3-14 урона от льда",
        "+75 урона от яда за 5 сек.",
        "+3 к умению «Блокирование» (только для Ассасинов)",
        "+6 к силе",
        "+6 к ловкости",
        "+15 к сопротивлению всем видам урона",
      ],
      en: [
        "+30% Faster Block Rate",
        "+<span class='varies'>40-80</span>% Enhanced Damage (varies)",
        "Adds 1-50 Lightning Damage",
        "Adds 3-14 Cold Damage",
        "Adds 17-62 Fire Damage",
        "+75 Poison Damage Over 5 Seconds",
        "+3 to Weapon block (Assassin only)",
        "+6 to Strength",
        "+6 to Dexterity",
        "All Resistances +15",
      ],
    },
    complete: false,
    old: {
      runes: [7, 9, 10],
      types: [8],
      stats: {
        ru: [
          "+30% к скорости блока",
          "+(40-80)% к урону",
          "+10% к рейтингу атаки",
          "+17-62 урона от огня",
          "+1-50 урона от молнии",
          "+3-14 урона от льда",
          "+75 урона от яда за 5 сек",
          "+6 к силе",
          "+6 к ловкости",
          "+15 к сопротивлению всем видам урона",
        ],
        en: [
          "+30% Faster Block Rate",
          "+<span class='varies varies--old'>40-80</span>% Enhanced Damage (varies)",
          "10% Bonus to Attack Rating",
          "Adds 17-62 Fire Damage",
          "Adds 1-50 Lightning Damage",
          "Adds 3-14 Cold Damage",
          "+75 Poison Damage Over 5 Seconds",
          "+6 to Strength",
          "+6 to Dexterity",
          "All Resistances +15",
        ],
      },
    },
  },

  {
    id: 14,
    name: {
      ru: "Миф",
      en: "Myth",
    },
    runes: [15, 14, 21],
    types: [17],
    excluded: "",
    classes: ["Barbarian"],
    patch: "1.11",
    level: 45,
    ladder: false,
    reworked: true,
    stats: {
      ru: [
        "+3 к умениям владения оружием (только для варваров)",
        "+2 к уровню умений варвара",
        "+130% к урону",
        "+40 к урону",
        "+20% к вероятности нанести смертельный удар",
        "Восполняет +7 здоровья",
        "Требования: -15%",
      ],
      en: [
        "+3 to Masteries (Barbarian only)",
        "+2 To Barbarian Skill Levels",
        "Adds +40 damage",
        "+20% Deadly Strike",
        "+130% Enhanced Defence",
        "Replenish Life 7",
        "Requirements -15%",
      ],
    },
    complete: false,
    old: {
      runes: [15, 11, 4],
      types: [17],
      stats: {
        ru: [
          "Вероятность 3% применить умение «Рев» 1-го уровня при получении урона",
          "Вероятность 10% применить умение «Провокация» 1-го уровня при ударе",
          "+2 к умениям варвара",
          "+30 к защите от снарядов",
          "Восполняет +10 здоровья",
          "Атакующий получает 14 урона",
          "Требования -15%",
        ],
        en: [
          "3% Chance To Cast Level 1 Howl When Struck",
          "10% Chance To Cast Level 1 Taunt On Striking",
          "+2 To Barbarian Skill Levels",
          "+30 Defense Vs. Missile",
          "Replenish Life +10",
          "Attacker Takes Damage of 14",
          "Requirements -15%",
        ],
      },
    },
  },

  {
    id: 20,
    name: {
      ru: "Мир",
      en: "Peace",
    },
    runes: [22, 10, 11],
    types: [17],
    excluded: "",
    classes: ["Amazon"],
    patch: "",
    level: 47,
    ladder: false,
    reworked: true,
    stats: {
      ru: [
        "Вероятность 2% применить умение «Валькирия» 15-го уровня при ударе",
        "+2 к уровню умениям амазонки",
        "+30% к скорости атаки",
        "+2 к умению «Критический удар»",
        "+30% к сопротивлению льду",
        "+15% к сопротивлению всем видам урона",
        "Атакующий получает 14 урона",
      ],
      en: [
        "2% Chance To Cast level 15 Valkyrie On Striking",
        "+2 To Amazon Skill Levels",
        "+30% Increased Attack Speed",
        "+2 To Critical Strike",
        "Cold Resist +30%",
        "All Resistances +15%",
        "Attacker Takes Damage of 14",
      ],
    },
    complete: false,
    old: {
      runes: [13, 10, 11],
      types: [17],
      stats: {
        ru: [
          "Вероятность 4% применить умение «Замедление снарядов» 5-го уровня при получении урона",
          "Вероятность 2% применить умение «Валькирия» 15-го уровня при ударе",
          "+2 к умениям амазонки",
          "+20% к ускоренному восстановлению после удара",
          "+2 к умению «Критический удар»",
          "+30% к сопротивлению льду",
          "Атакующий получает 14 урона",
        ],
        en: [
          "4% Chance To Cast Level 5 Slow Missiles When Struck",
          "2% Chance To Cast level 15 Valkyrie On Striking",
          "+2 To Amazon Skill Levels",
          "+20% Faster Hit Recovery",
          "+2 To Critical Strike",
          "Cold Resist +30%",
          "Attacker Takes Damage of 14",
        ],
      },
    },
  },

  {
    id: 25,
    name: {
      ru: "Земля",
      en: "Ground",
    },
    runes: [13, 16, 24],
    types: [18],
    excluded: "",
    classes: [],
    patch: "",
    level: 51,
    ladder: true,
    reworked: true,
    stats: {
      ru: [
        "При надевании дает ауру «Очищение» 1-го уровня",
        "+20% к ускоренному восстановлению от удара",
        "+<span class='varies'>75-100</span>% к защите",
        "+10 к живучести",
        "+30% к максимальному запасу маны",
        "+30% к сопротивлению молнии",
        "+<span class='varies'>10-15</span>% к поглощению урона от молнии",
        "+25% к вероятности найти магический предмет",
      ],
      en: [
        "Level 1 Cleansing Aura When Equipped",
        "+20% Faster Hit Recovery",
        "+<span class='varies'>75-100</span>% Enhanced Defense (varies)",
        "+10 to Vitality",
        "Increase Maximum Mana 30%",
        "Lightning Resist +30%",
        "Lightning Absorb +<span class='varies'>10-15</span>%",
        "+25% Better Chance of Getting Magic Items",
      ],
    },
    complete: false,
    old: {
      runes: [13, 16, 9],
      types: [18],
      stats: {
        ru: [
          "+20% к ускоренному восстановлению от удара",
          "+<span class='varies varies--old'>75-100</span>% к защите",
          "+10 к живучести",
          "+5% к максимальному запасу здоровья",
          "+<span class='varies varies--old'>40-60</span>% к сопротивлению молнии",
          "+<span class='varies varies--old'>10-15</span>% к поглощению урона от молнии",
        ],
        en: [
          "+20% Faster Hit Recovery",
          "+<span class='varies varies--old'>75-100</span>% Enhanced Defense (varies)",
          "+10 to Vitality",
          "Increase Maximum Life 5%",
          "Lightning Resist +<span class='varies varies--old'>40-60</span>%",
          "Lightning Absorb +<span class='varies varies--old'>10-15</span>%",
        ],
      },
    },
  },

  {
    id: 26,
    name: {
      ru: "Очаг",
      en: "Hearth",
    },
    runes: [13, 16, 25],
    types: [18],
    excluded: "",
    classes: [],
    patch: "",
    level: 53,
    ladder: true,
    reworked: true,
    stats: {
      ru: [
        "При надевании дате ауру «Правое дело» 16-го уровня",
        "+20% к ускоренному восстановлению от удара",
        "+<span class='varies'>75-100</span>% к защите",
        "+10 к живучести",
        "5% к максимальному сопротивлению яду",
        "+30% к сопротивлению льду",
        "+<span class='varies'>10-15</span>% к поглощению урона от льда",
        "Нельзя заморозить",
      ],
      en: [
        "Level 16 Blessed Aim Aura When Equipped",
        "+20% Faster Hit Recovery",
        "+<span class='varies'>75-100</span>% Enhanced Defense (varies)",
        "+10 to Vitality",
        "+5% to Maximum Poison Resist",
        "Cold Resist +30%",
        "Cold Absorb +10-15%",
        "Cannot be Frozen",
      ],
    },
    complete: false,
    old: {
      runes: [13, 16, 10],
      types: [18],
      stats: {
        ru: [
          "+20% к ускоренному восстановлению от удара",
          "+(75-100)% к защите",
          "+10 к живучести",
          "+5% к максимальному запасу здоровья",
          "+(40-60)% к сопротивлению льду",
          "+(10-15)% к поглощению урона от льда",
          "Нельзя заморозить",
        ],
        en: [
          "+20% Faster Hit Recovery",
          "+<span class='varies varies--old'>75-100</span>% Enhanced Defense (varies)",
          "+10 to Vitality",
          "Increase Maximum Life 5%",
          "Cold Resist +40-60%",
          "Cold Absorb +10-15%",
          "Cannot be Frozen",
        ],
      },
    },
  },

  {
    id: 27,
    name: {
      ru: "Закалка",
      en: "Temper",
    },
    runes: [13, 16, 21],
    types: [18],
    excluded: "",
    classes: [],
    patch: "",
    level: 45,
    ladder: true,
    reworked: true,
    stats: {
      ru: [
        "+20% к скорости применения умений",
        "+20% к ускоренному восстановлению от удара",
        "Похищает 8% здоровья за удар",
        "+130% к защите",
        "+10 к живучести",
        "+30% к сопротивлению огню",
        "+(10-15)% к поглощению урона от огня",
        "+350% к золоту за убийство монстров",
      ],
      en: [
        "+20% Faster Cast Rate",
        "+20% Faster Hit Recovery",
        "8% life stolen per hit",
        "130% Enhanced Defense",
        "+10 to Vitality",
        "Fire Resist +30%",
        "Fire Absorb +10-15%",
        "+350% extra gold from monsters",
      ],
    },
    complete: false,
    old: {
      runes: [13, 16, 8],
      types: [18],
      stats: {
        ru: [
          "+20% к ускоренному восстановлению от удара",
          "+(75-100)% к защите",
          "+10 к живучести",
          "+5% к максимальному запасу здоровья",
          "+(40-60)% к сопротивлению огню",
          "+(10-15)% к поглощению урона от огня",
        ],
        en: [
          "+20% Faster Hit Recovery",
          "+<span class='varies varies--old'>75-100</span>% Enhanced Defense (varies)",
          "+10 to Vitality",
          "Increase Maximum Life 5%",
          "Fire Resist +40-60%",
          "Fire Absorb +10-15%",
        ],
      },
    },
  },

  {
    id: 36,
    name: {
      ru: "Непреклонность",
      en: "Unbending Will",
    },
    runes: [19, 16, 6, 15],
    types: [3],
    excluded: "",
    classes: [],
    patch: "2.4",
    level: 41,
    ladder: false,
    reworked: true,
    stats: {
      ru: [
        "Вероятность 18% применить умение «Провокация» 18-го уровня при ударе",
        "+3 к боевым умениям (только для варваров)",
        "+<span class='varies'>20-30</span>% к скорости атаки",
        "+<span class='varies'>300-350</span>% к урону",
        "+9 к максимальному урону",
        "Похищает <span class='varies'>6-8</span>% здоровья за удар",
        "Запрещает монстрам лечиться",
        "+10 к силе",
        "+10 к живучести",
        "-8 к урону",
        "Требования -20%",
      ],
      en: [
        "18% Chance to cast Level 18 Taunt on striking",
        "+3 To Combat Skills (Barbarian Only)",
        "+<span class='varies'>20-30</span>% Increased Attack Speed (varies)",
        "+<span class='varies'>300-350</span>% Enhanced Damage (varies)",
        "+9 To Maximum Damage",
        "<span class='varies'>8-10</span>% Life Stolen Per Hit (varies)",
        "Prevent Monster Heal",
        "+10 To Strength",
        "+10 To Vitality",
        "Damage Reduced By 8",
        "Requirements -20%",
      ],
    },
    complete: false,
    old: {
      runes: [19, 16, 6, 2, 1, 15],
      types: [3],
      stats: {
        ru: [
          "Вероятность 18% применить умение «Провокация» 18-го уровня при ударе",
          "+3 к боевым умениям (только для варваров)",
          "+(20-30)% к скорости атаки",
          "+(300-350)% к урону",
          "+9 к максимальному урону",
          "+50 к рейтингу атаки",
          "+75% урона по нежити",
          "+50 к рейтингу атаки против нежити",
          "Похищает (6-8)% здоровья за удар",
          "Запрещает монстрам лечиться",
          "+10 к силе",
          "+10 к живучести",
          "-8 к урону",
          "+1 к радиусу обзора",
          "Требования -20%",
        ],
        en: [
          "18% Chance to cast Level 18 Taunt on striking",
          "+3 To Combat Skills (Barbarian Only)",
          "+<span class='varies varies--old'>20-30</span>% Increased Attack Speed (varies)",
          "+<span class='varies varies--old'>300-350</span>% Enhanced Damage (varies)",
          "+9 To Maximum Damage",
          "+50 To Attack Rating",
          "+75% Damage to Undead",
          "+50 Attack Rating Against Undead",
          "<span class='varies varies--old'>8-10</span>% Life Stolen Per Hit (varies)",
          "Prevent Monster Heal",
          "+10 To Strength",
          "+10 To Vitality",
          "Damage Reduced By 8",
          "+1 Light Radius",
          "Requirements -20%",
        ],
      },
    },
  },

  {
    id: 38,
    name: {
      ru: "Страсть",
      en: "Passion",
    },
    runes: [14, 9, 2, 20],
    types: [12],
    excluded: "",
    classes: [],
    patch: "",
    level: 43,
    ladder: false,
    reworked: true,
    bugged: {
      status: false,
      message: [],
    },
    stats: {
      ru: [
        "+25% к скорости атаки",
        "+(160-210)% к урону",
        "+<span class='varies'>50-80</span>% к рейтингу атаки",
        "+75% урона по нежити",
        "+50 к рейтингу атаки против нежити",
        "+1-50 урона от молнии",
        "+<span class='varies'>1-6</span> к умению «Берсерк»",
        "+<span class='varies'>1-6</span> к умению «Истовость»",
        "+25% к вероятности обратить монстра в бегство при ударе",
        "+75% к золоту за убийство монстров",
        "«Сердце росомахи» 3-го уровня (12 зарядов)",
      ],
      en: [
        "+25% Increased Attack Speed",
        "+200 To Maximum Damage",
        "<span class='varies'>50-80</span>% Bonus To Attack Rating (varies)",
        "+75% Damage To Undead",
        "+50 To Attack Rating Against Undead",
        "Adds 1-50 Lightning Damage",
        "+<span class='varies'>1-6</span> To Berserk (varies)",
        "+<span class='varies'>1-6</span> To Zeal (varies)",
        "Hit Causes Monster To Flee 25%",
        "75% Extra Gold From Monsters",
        "Level 3 Heart of Wolverine (12 Charges)",
      ],
    },
    complete: false,
    old: {
      runes: [14, 9, 2, 20],
      types: [12],
      stats: {
        ru: [
          "+25% к скорости атаки",
          "+(160-210)% к урону",
          "+(50-80)% к рейтингу атаки",
          "+75% урона по нежити",
          "+50 к рейтингу атаки против нежити",
          "+1-50 урона от молнии",
          "+1 к умению «Берсерк»",
          "+1 к умению «Истовость»",
          "При ударе ослепляет цель +10",
          "+25% к вероятности обратить монстра в бегство при ударе",
          "+75% к золоту за убийство монстров",
          "«Сердце росомахи» 3-го уровня (12/12 зарядов)",
        ],
        en: [
          "+25% Increased Attack Speed",
          "+<span class='varies varies--old'>160-210</span>% Enhanced Damage (varies)",
          "<span class='varies varies--old'>50-80</span>% Bonus To Attack Rating (varies)",
          "+75% Damage To Undead",
          "+50 To Attack Rating Against Undead",
          "Adds 1-50 Lightning Damage",
          "+1 To Berserk",
          "+1 To Zeal",
          "Hit Blinds Target +10",
          "Hit Causes Monster To Flee 25%",
          "75% Extra Gold From Monsters",
          "Level 3 Heart of Wolverine (12 Charges)",
        ],
      },
    },
  },

  {
    id: 39,
    name: {
      ru: "Судия",
      en: "Lawbringer",
    },
    runes: [11, 20, 18],
    types: [3, 11, 7],
    excluded: "",
    classes: [],
    patch: "",
    level: 43,
    ladder: false,
    reworked: true,
    stats: {
      ru: [
        "Вероятность 20% применить умение «Одряхление» 15-го уровня при ударе",
        "При надевании дает ауру «Убежище» <span class='varies'>16-18</span>-го уровня",
        "+25% к скорости атаки",
        "+1-990 урона от молнии",
        "Похищает 15% маны за удар",
        "Похищает 7% здоровья за удар",
        "+1 к умению «Истовость»",
        "Убитые монстры не возрождаются",
        "+10 к ловкости",
        "+75% к золоту за убийство монстров",
      ],
      en: [
        "20% Chance To Cast Level 15 Decrepify On Striking",
        "Level <span class='varies'>16-18</span> Sanctuary Aura When Equipped (varies)",
        "+25% Increased Attack Speed",
        "Adds 1-990 Lightning Damage",
        "15% Mana Stolen Per Hit",
        "7% Life Stolen Per Hit",
        "+1 to Zeal",
        "Slain Monsters Rest In Peace",
        "+10 To Dexterity",
        "75% Extra Gold From Monsters",
      ],
    },
    complete: false,
    old: {
      runes: [11, 20, 18],
      types: [3, 11, 7],
      stats: {
        ru: [
          "Вероятность 20% применить умение «Одряхление» 15-го уровня при ударе",
          "При надевании дает ауру «Убежище» (16-18)-го уровня",
          "-50% к защите цели",
          "+150-210 урона от огня",
          "+130-180 урона от льда",
          "Похищает 7% здоровья за удар",
          "Убитые монстры не возрождаются",
          "+(200-250) к защите от снарядов",
          "+10 к ловкости",
          "+75% к золоту за убийство монстров",
        ],
        en: [
          "20% Chance To Cast Level 15 Decrepify On Striking",
          "Level <span class='varies varies--old'>16-18</span> Sanctuary Aura When Equipped (varies)",
          "-50% Target Defense",
          "Adds 150-210 Fire Damage",
          "Adds 130-180 Cold Damage",
          "7% Life Stolen Per Hit",
          "Slain Monsters Rest In Peace",
          "+<span class='varies varies--old'>200-250</span> Defense Vs. Missile (varies)",
          "+10 To Dexterity",
          "75% Extra Gold From Monsters",
        ],
      },
    },
  },

  {
    id: 40,
    name: {
      ru: "Голос разума",
      en: "Voice of Reason",
    },
    runes: [20, 18, 1, 2],
    types: [3, 2, 7],
    excluded: "",
    classes: [],
    patch: "1.10",
    level: 43,
    ladder: false,
    reworked: true,
    bugged: {
      status: false,
      message: [],
    },
    stats: {
      ru: [
        "+30% к скорости атаки",
        "+<span class='varies'>150-200</span>% к урону",
        "+50 к рейтингу атаки",
        "+<span class='varies'>220-350</span>% к урону по демонам",
        "+<span class='varies'>355-375</span>% урона по нежети",
        "+50 к рейтингу атаки против нежити",
        "+100-220 урона от льда",
        "-24% к сопротивлению льду у врага",
        "+10 к ловкости",
        "Нельзя заморозить",
        "75% к золоту за убийство монстров",
        "+1 к радиусу обзора",
      ],
      en: [
        "+30% Faster Cast Rate",
        "+<span class='varies'>150-200</span>% Enhanced Damage (varies)",
        "+50 To Attack Rating",
        "+<span class='varies'>220-350</span>% Damage To Demons (varies)",
        "+<span class='varies'>355-375</span>% Damage To Undead (varies)",
        "+50 To Attack Rating Against Undead",
        "Adds 100-220 Cold Damage",
        "-24% To Enemy Cold Resistance",
        "+10 To Dexterity",
        "Cannot Be Frozen",
        "75% Extra Gold From Monsters",
        "+1 To Light Radius",
      ],
    },
    complete: false,
    old: {
      runes: [20, 18, 1, 2],
      types: [3, 2],
      stats: {
        ru: [
          "Вероятность 15% применить умение «Морозная сфера» 13-го уровня при ударе",
          "Вероятность 18% применить умение «Ледяной удар» 20-го уровня при ударе",
          "+50 к рейтингу атаки",
          "+(220-350)% к урону по демонам",
          "+(355-375)% урона по нежити",
          "+50 к рейтингу атаки против нежити",
          "+100-220 урона от льда",
          "-24% к сопротивлению льду у врага",
          "+10 к ловкости",
          "Нельзя заморозить",
          "+75% к золоту за убийство монстров",
          "+1 к радиусу обзора",
        ],
        en: [
          "15% Chance To Cast Level 13 Frozen Orb On Striking",
          "18% Chance To Cast Level 20 Ice Blast On Striking",
          "+50 To Attack Rating",
          "+<span class='varies varies--old'>220-350</span>% Damage To Demons (varies)",
          "+<span class='varies varies--old'>355-375</span>% Damage To Undead (varies)",
          "+50 To Attack Rating Against Undead",
          "Adds 100-220 Cold Damage",
          "-24% To Enemy Cold Resistance",
          "+10 To Dexterity",
          "Cannot Be Frozen",
          "75% Extra Gold From Monsters",
          "+1 To Light Radius",
        ],
      },
    },
  },

  {
    id: 42,
    name: {
      ru: "Просветление",
      en: "Enlightenment",
    },
    runes: [21, 8, 12],
    types: [17],
    excluded: "",
    classes: ["Sorceress"],
    patch: "1.11",
    level: 45,
    ladder: false,
    reworked: true,
    stats: {
      ru: [
        "Вероятность 30% применить умение «Огненный след» 15-го уровня при получении урона",
        "+2 к уровню умений волшебницы",
        "+10% к скорости применения умений",
        "+6 к умению «Огненная стена» (только для волшебниц)",
        "+6 к умению «Кольцо льда» (только для волшебниц)",
        "+30% к защите",
        "+30% к сопротивлению огню",
        "-7 к урону",
      ],
      en: [
        "30% Chance To Cast Level 15 Blaze When Struck",
        "+2 To Sorceress Skill Levels",
        "+10% Faster Cast Rate",
        "+6 to Fire Wall (Sorceress only)",
        "+6 to Frost Nova (Sorceress only)",
        "+30% Enhanced Defense",
        "Fire Resist +30%",
        "Damage Reduced By 7",
      ],
    },
    complete: false,
    old: {
      runes: [21, 8, 12],
      types: [17],
      stats: {
        ru: [
          "Вероятность 5% применить умение «Огненный след» 15-го уровня при получении урона",
          "Вероятность 5% применить умение «Огненный шар» 15-го уровня при ударе",
          "+2 к умениям волшебницы",
          "+1 к умению «Тепло»",
          "+30% к защите",
          "+30% к сопротивлению огню",
          "-7 к урону",
        ],
        en: [
          "5% Chance To Cast Level 15 Blaze When Struck",
          "5% Chance To Cast level 15 Fire Ball On Striking",
          "+2 To Sorceress Skill Levels",
          "+1 To Warmth",
          "+30% Enhanced Defense",
          "Fire Resist +30%",
          "Damage Reduced By 7",
        ],
      },
    },
  },

  {
    id: 43,
    name: {
      ru: "Мудрость",
      en: "Wisdom",
    },
    runes: [21, 6, 2],
    types: [18],
    excluded: "",
    classes: [],
    patch: "2.4",
    level: 45,
    ladder: false,
    reworked: true,
    stats: {
      ru: [
        "+33% к пробивающей атаке",
        "+90% к урону",
        "Похищает <span class='varies'>4-8</span>% маны за удар",
        "+30% к защите",
        "+10 к энергии",
        "Выносливость снижается на 15% медленнее",
        "Нельзя заморозить",
        "+5 к мане при убийстве",
        "+15% к урону, приходящемуся на ману",
      ],
      en: [
        "+33% Piercing Attack",
        "+90% Enhanced Damage",
        "<span class='varies'>4-8</span>% Mana Stolen Per Hit (varies)",
        "+30% Enhanced Defense",
        "+10 To Energy",
        "15% Slower Stamina Drain",
        "Cannot Be Frozen",
        "+5 Mana After Each Kill",
        "15% Damage Taken Goes to Mana",
      ],
    },
    complete: false,
    old: {
      runes: [21, 6, 2],
      types: [18],
      stats: {
        ru: [
          "+33% к пронзающей атаке",
          "+(15-25)% к рейтингу атаки",
          "Похищает (4-8)% маны за удар",
          "+30% к защите",
          "+10 к энергии",
          "Выносливость снижается на 15% медленнее",
          "Нельзя заморозить",
          "+5 к мане при убийстве",
          "+15% к урону, приходящемуся на ману",
        ],
        en: [
          "+33% Piercing Attack",
          "+<span class='varies varies--old'>15-25</span>% Bonus to Attack Rating (varies)",
          "<span class='varies varies--old'>4-8</span>% Mana Stolen Per Hit (varies)",
          "+30% Enhanced Defense",
          "+10 Energy",
          "15% Slower Stamina Drain",
          "Cannot Be Frozen",
          "+5 Mana After Each Kill",
          "15% Damage Taken Goes to Mana",
        ],
      },
    },
  },

  {
    id: 46,
    name: {
      ru: "Сумрак",
      en: "Gloom",
    },
    runes: [19, 22, 21],
    types: [17],
    excluded: "",
    classes: [],
    patch: "1.10",
    level: 47,
    ladder: false,
    reworked: true,
    bugged: {
      status: false,
      message: [],
    },
    stats: {
      ru: [
        "Вероятность 30% применить умение «Покров теней» 8-го уровня при получении урона",
        "+1 ко всем умениям",
        "+20% к скорости применения умений",
        "+30% к ускоренному восстановления от удара",
        "+<span class='varies'>200-260</span>% к защите",
        "+10 к силе",
        "+15 к сопротивлению всем видам урона",
        "-25% к вероятности найти магический предмет",
      ],
      en: [
        "30% Chance To Cast Level 8 Cloak of Shadows When Struck",
        "+1 To All Skills",
        "+20% Faster Cast Rate",
        "+30% Faster Hit Recovery",
        "+<span class='varies'>200-260</span>% Enhanced Defense (varies)",
        "+10 To Strength",
        "All resistances +15",
        "-30% Chance Of Getting Magic Items",
      ],
    },
    complete: false,
    old: {
      runes: [19, 22, 21],
      types: [17],
      stats: {
        ru: [
          "Вероятность 15% применить умение «Лишение зрения» 3-го уровня при получении урона",
          "+10% к ускоренному восстановлению от удара",
          "+<span class='varies'>200-260</span>% к защите",
          "+10 к силе",
          "+45 к сопротивлению всем видам урона",
          "Вдвое уменьшает время заморозки",
          "+5% к урону, приходящемуся на ману",
          "-3 к радиусу обзора",
        ],
        en: [
          "15% Chance To Cast Level 3 Dim Vision When Struck",
          "+10% Faster Hit Recovery",
          "+<span class='varies varies--old'>200-260</span>% Enhanced Defense (varies)",
          "+10 To Strength",
          "All Resistances +45",
          "Half Freeze Duration",
          "5% Damage Taken Goes To Mana",
          "-3 To Light Radius",
        ],
      },
    },
  },

  {
    id: 47,
    name: {
      ru: "Камень",
      en: "Stone",
    },
    runes: [13, 22, 21, 17],
    types: [17],
    excluded: "",
    classes: [],
    patch: "1.10",
    level: 47,
    ladder: false,
    reworked: true,
    stats: {
      ru: [
        "При надевании дает ауру «Непокорность» 6-го уровня",
        "+60% к ускоренному восстановлению от удара",
        "Вероятность 20% заблокировать удар",
        "+<span class='varies'>250-290</span>% к защите",
        "+16 к силе",
        "+16 к живучести",
        "+10 к энергии",
        "+40 к сопротивлению всем видам урона",
      ],
      en: [
        "Level 6 Defiance Aura When Equipped",
        "+60% Faster Hit Recovery",
        "+20% Increased Chance Of Blocking",
        "+<span class='varies'>250-290</span>% Enhanced Defense (varies)",
        "+16 To Strength",
        "+16 To Vitality",
        "+10 To Energy",
        "All Resistances +40",
      ],
    },
    complete: false,
    old: {
      runes: [13, 22, 21, 17],
      types: [17],
      stats: {
        ru: [
          "+60% к ускоренному восстановлению от удара",
          "+(250-290)% к защите",
          "+300 к защите от снарядов",
          "+16 к силе",
          "+16 к живучести",
          "+10 к энергии",
          "+15 к сопротивлению всем видам урона",
          "«Пылающий валун» 16-го уровня (80/80 зарядов)",
          "«Глиняный голем» 16-го уровня (16/16 зарядов)",
        ],
        en: [
          "+60% Faster Hit Recovery",
          "+<span class='varies varies--old'>250-290</span>% Enhanced Defense (varies)",
          "+300 Defense Vs. Missile",
          "+16 To Strength",
          "+16 To Vitality",
          "+10 To Energy",
          "All Resistances +15",
          "Level 16 Molten Boulder (80 Charges)",
          "Level 16 Clay Golem (16 Charges)",
        ],
      },
    },
  },

  {
    id: 48,
    name: {
      ru: "Кость",
      en: "Bone",
    },
    runes: [12, 22, 22],
    types: [17],
    excluded: "",
    classes: ["Necromancer"],
    patch: "1.11",
    level: 47,
    ladder: false,
    reworked: true,
    bugged: {
      status: false,
      message: [],
    },
    stats: {
      ru: [
        "+2 к уровню умений некроманта",
        "+20% к скорости применения умений",
        "+6 к умению «Скелет» (только для некромантов)",
        "+6 к умению «Костяной доспех» (только для некромантов)",
        "+30 к сопротивлению всем видам урона",
        "-7 к урону",
      ],
      en: [
        "+2 To Necromancer Skill Levels",
        "+20% Faster Cast Rate",
        "+6 to Raise Skeleton (Necromancer only)",
        "+6 to Bone Armor (Necromancer only)",
        "All Resistances +30",
        "Damage Reduced By 7",
      ],
    },
    complete: false,
    old: {
      runes: [12, 22, 22],
      types: [17],
      stats: {
        ru: [
          "Вероятность 15% применить умение «Костяной доспех» 10-го уровня при получении урона",
          "Вероятность 15% применить умение «Костяное копье» 10-го уровня при ударе",
          "+2 к умениям некроманта",
          "+(100-150) к мане",
          "+30 к сопротивлению всем видам урона",
          "-7 к урону",
        ],
        en: [
          "15% Chance To Cast level 10 Bone Armor When Struck",
          "15% Chance To Cast level 10 Bone Spear On Striking",
          "+2 To Necromancer Skill Levels",
          "+<span class='varies varies--old'>100-150</span> To Mana (varies)",
          "All Resistances +30",
          "Damage Reduced By 7",
        ],
      },
    },
  },

  {
    id: 50,
    name: {
      ru: "Благоразумие",
      en: "Prudence",
    },
    runes: [23, 3],
    types: [17],
    excluded: "",
    classes: [],
    patch: "1.10",
    level: 49,
    ladder: false,
    reworked: true,
    stats: {
      ru: [
        "Вероятность 10% применить умение «Ураганный доспех» 16-го уровня при получении урона",
        "Вероятность 10% применить умение «Костяной доспех» 20-го уровня при получении урона",
        "+<span class='varies'>4-6</span> к умению «Крик»",
        "<span class='varies'>200-235</span>% к защите",
        "+<span class='varies'>25-35</span> к сопротивлению всем видам урона",
        "Урон уменьшен на 12%",
        "-7 к магическому урону",
        "+2 к мане при убийстве",
        "Восполняет 1 ед. прочности раз в 25 сек.",
      ],
      en: [
        "10% Chance to cast level 16 Cyclone Armor when struck",
        "10% Chance to cast level 20 Bone Armor when struck",
        "+<span class='varies'>4-6</span> to Shout (varies)",
        "<span class='varies'>200-235</span>% Enhanced Defense (varies)",
        "All Resistances +<span class='varies'>25-35</span> (varies)",
        "Damage reduced by 12%",
        "Magic Damage Reduced by 7",
        "+2 To Mana After Each Kill",
        "Repairs 1 Durability In 4 Seconds",
      ],
    },
    complete: false,
    bugged: {
      status: false,
      message: [],
    },
    old: {
      runes: [23, 3],
      types: [17],
      stats: {
        ru: [
          "+25% к ускоренному восстановлению от удара",
          "+(140-170)% к защите",
          "+(25-35) к сопротивлению всем видам урона",
          "-3 к урону",
          "-17 к магическому урону",
          "+2 к мане при убийстве",
          "+1 к радиусу обзора",
          "Восполняет 1 ед. прочности раз в 4 сек.",
        ],
        en: [
          "+25% Faster Hit Recovery",
          "+<span class='varies varies--old'>140-170</span>% Enhanced Defense (varies)",
          "All Resistances +<span class='varies varies--old'>25-35</span> (varies)",
          "Damage Reduced by 3",
          "Magic Damage Reduced by 17",
          "+2 To Mana After Each Kill",
          "+1 To Light Radius",
          "Repairs Durability 1 In 4 Seconds",
        ],
      },
    },
  },

  {
    id: 51,
    name: {
      ru: "Убежище",
      en: "Sanctuary",
    },
    runes: [18, 18, 23],
    types: [16],
    excluded: "",
    classes: [],
    patch: "1.10",
    level: 49,
    ladder: false,
    reworked: true,
    stats: {
      ru: [
        "Вероятность 10% применить умение «Замедление снарядов» 12-го уровня при получении урона",
        "При надевании дает ауру «Спасение» <span class='varies'>1-4</span> уровня",
        "+2 ко всем умениям",
        "+20% к ускоренному восстановлению от удара",
        "+20% к скорости блока",
        "Вероятность 40% заблокировать удар",
        "+<span class='varies'>130-160</span>% к защите",
        "+20 к ловкости",
        "-7 к магическому урону",
      ],
      en: [
        "10% Chance to cast level 12 Slow Missiles when struck",
        "Level <span class='varies'>1-4</span> Salvation Aura When Equipped",
        "+2 To All Skills",
        "+20% Faster Hit Recovery",
        "+20% Faster Block Rate",
        "40% Increased Chance of Blocking",
        "+<span class='varies'>130-160</span>% Enhanced Defense (varies)",
        "+20 To Dexterity",
        "Magic Damage Reduced By 7",
      ],
    },
    complete: false,
    old: {
      runes: [18, 18, 23],
      types: [16],
      stats: {
        ru: [
          "+20% к ускоренному восстановлению от удара",
          "+20% к скорости блока",
          "Вероятность 20% заблокировать удар",
          "+(130-160)% к защите",
          "+250 к защите от снарядов",
          "+20 к ловкости",
          "+(50-70) к сопротивлению всем видам урона",
          "-7 к магическому урону",
          "«Замедление снарядов» 12-го уровня (60/60 зарядов)",
        ],
        en: [
          "+20% Faster Hit Recovery",
          "+20% Faster Block Rate",
          "20% Increased Chance of Blocking",
          "+<span class='varies varies--old'>130-160</span>% Enhanced Defense (varies)",
          "+250 Defense vs. Missile",
          "+20 To Dexterity",
          "All Resistances +<span class='varies varies--old'>50-70</span> (varies)",
          "Magic Damage Reduced By 7",
          "Level 12 Slow Missiles (60 Charges)",
        ],
      },
    },
  },

  {
    id: 52,
    name: {
      ru: "Клятва",
      en: "Oath",
    },
    runes: [13, 21, 23, 17],
    types: [3, 1, 2],
    excluded: "",
    classes: [],
    patch: "1.10",
    level: 49,
    ladder: false,
    reworked: true,
    stats: {
      ru: [
        "Вероятность 30% применить умение «Костяной дух» 20-го уровня при ударе",
        "Не теряет прочности",
        "+<span class='varies'>40-50</span>% к скорости атаки",
        "+<span class='varies'>300-340</span>% к урону",
        "+75% к урону по демонам",
        "+100 к рейтингу атаки против демонов",
        "Запрещает монстрам лечиться",
        "+10 к энергии",
        "+<span class='varies'>10-15</span> поглощаемого магического урона",
        "«Сердце рассомахи» 16-го уровня (20/20 зарядов)",
        "«Желеный голем» 17-го уровня (14/14 зарядов)",
      ],
      en: [
        "30% Chance To Cast Level 20 Bone Spirit On Striking",
        "Indestructible",
        "+<span class='varies'>40-50</span>% Increased Attack Speed (varies)",
        "+<span class='varies'>300-340</span>% Enhanced Damage (varies)",
        "+75% Damage To Demons",
        "+100 To Attack Rating Against Demons",
        "Prevent Monster Heal",
        "+10 To Energy",
        "+<span class='varies'>10-15</span> Magic Absorb (varies)",
        "Level 16 Heart Of Wolverine (20 Charges)",
        "Level 17 Iron Golem (14 Charges)",
      ],
    },
    complete: false,
    old: {
      runes: [13, 21, 23, 17],
      types: [3, 1, 2],
      stats: {
        ru: [
          "Не теряет прочности",
          "Вероятность 30% применить умение «Костяной дух» 20-го уровня при ударе",
          "+50% к скорости атаки",
          "+(210-340)% к урону",
          "+75% к урону по демонам",
          "+100 к рейтингу атаки против демонов",
          "Запрещает монстрам лечиться",
          "+10 к энергии",
          "+(10-15) поглощаемого магического урона",
          "«Сердце рассомахи» 16-го уровня (20/20 зарядов)",
          "«Желеный голем» 17-го уровня (14/14 зарядов)",
        ],
        en: [
          "30% Chance To Cast Level 20 Bone Spirit On Striking",
          "Indestructible",
          "50% Increased Attack Speed",
          "+<span class='varies varies--old'>210-340</span>% Enhanced Damage (varies)",
          "+75% Damage To Demons",
          "+100 To Attack Rating Against Demons",
          "Prevent Monster Heal",
          "+10 To Energy",
          "+<span class='varies varies--old'>10-15</span> Magic Absorb (varies)",
          "Level 16 Heart Of Wolverine (20 Charges)",
          "Level 17 Iron Golem (14 Charges)",
        ],
      },
    },
  },

  {
    id: 53,
    name: {
      ru: "Дождь",
      en: "Rain",
    },
    runes: [9, 23, 6],
    types: [17],
    excluded: "",
    classes: ["Druid"],
    patch: "1.11",
    level: 49,
    ladder: false,
    reworked: true,
    bugged: {
      status: false,
      message: [],
    },
    stats: {
      ru: [
        "Вероятность 5% применить умение «Ураган» 26-го уровня при получении урона",
        "Вероятность 5% применить умение «Ураганный доспех» 15-го уровня при получении урона",
        "+2 к умениям друида",
        "+2 to Summoning skils (druid only)",
        "+30% к сопротивлению молнии",
        "-7 к магическому урону",
        "+15% к урону, приходящемуся на ману",
        "300% к золоту за убийство монстров",
        "Level 1 Amplify Damage (12 Charges)",
      ],
      en: [
        "5% Chance To Cast Level 26 Hurricane When Struck",
        "5% Chance To Cast Level 15 Cyclone Armor When Struck",
        "+2 to Summoning skils (druid only)",
        "+2 To Druid Skills",
        "Lightning Resist +30%",
        "Magic Damage Reduced By 7",
        "15% Damage Taken Goes to Mana",
        "300% extra gold from monsters",
        "Level 1 Amplify Damage (12 Charges)",
      ],
    },
    complete: false,
    old: {
      runes: [9, 23, 6],
      types: [17],
      stats: {
        ru: [
          "Вероятность 5% применить умение «Ураганный доспех» 15-го уровня при получении урона",
          "Вероятность 5% применить умение «Смерч» 15-го уровня при ударе",
          "+2 к умениям друида",
          "+(100-150) к мане",
          "+30% к сопротивлению молнии",
          "-7 к магическому урону",
          "+15% к урону, приходящемуся на ману",
        ],
        en: [
          "5% Chance To Cast Level 15 Cyclone Armor When Struck",
          "5% Chance To Cast Level 15 Twister On Striking",
          "+2 To Druid Skills",
          "+<span class='varies varies--old'>100-150</span> To Mana (varies)",
          "Lightning Resist +30%",
          "Magic Damage Reduced By 7",
          "15% Damage Taken Goes to Mana",
        ],
      },
    },
  },

  {
    id: 54,
    name: {
      ru: "Бред",
      en: "Delirium",
    },
    runes: [20, 24, 16],
    types: [18],
    excluded: "",
    classes: [],
    patch: "1.11",
    level: 51,
    ladder: false,
    reworked: true,
    stats: {
      ru: [
        "Вероятность 1% применить умение «Бред» 50-го уровня при получении урона",
        "Вероятность 6% применить умение «Ментальный взрыв» 14-го уровня при получении урона",
        "Вероятность 11% применить умение «Замешательство» 18-го уровня при ударе",
        "+2 ко всем умениям",
        "+261 к защите",
        "+10 к живучести",
        "+50% к золоту за убийство монстров",
        "+25% к вероятности найти магический предмет",
        "«Телепортация» 1-го уровня (60 зарядов)",
      ],
      en: [
        "1% Chance To Cast Level 50 Delirium When Struck",
        "6% Chance To Cast Level 14 Mind Blast When Struck",
        "11% Chance To Cast Level 18 Confuse When Struck",
        "+2 To All Skills",
        "+261 Defense",
        "+10 To Vitality",
        "50% Extra Gold From Monsters",
        "+75% Better Chance of Getting Magic Items",
        "Level 1 Teleport (60 Charges)",
      ],
    },
    complete: false,
    old: {
      runes: [20, 24, 16],
      types: [18],
      stats: {
        ru: [
          "Вероятность 1% применить умение «Бред» 50-го уровня при получении урона",
          "Вероятность 6% применить умение «Ментальный взрыв» 14-го уровня при получении урона",
          "Вероятность 14% применить умение «Устрашение» 13-го уровня при получении урона",
          "Вероятность 18% применить умение «Замешательство» 18-го уровня при ударе",
          "+2 ко всем умениям",
          "+261 к защите",
          "+10 к живучести",
          "+50% к золоту за убийство монстров",
          "+25% к вероятности найти магический предмет",
          "«Привлечение» 17-го уровня (60/60 зарядов)",
        ],
        en: [
          "1% Chance To Cast Level 50 Delirium* (morph) When Struck",
          "6% Chance To Cast Level 14 Mind Blast When Struck",
          "14% Chance To Cast Level 13 Terror When Struck",
          "11% Chance To Cast Level 18 Confuse On Striking",
          "+2 To All Skills",
          "+261 Defense",
          "+10 To Vitality",
          "50% Extra Gold From Monsters",
          "25% Better Chance of Getting Magic Items",
          "Level 17 Attract (60 Charges)",
        ],
      },
    },
  },

  {
    id: 55,
    name: {
      ru: "Цареубийца",
      en: "Kingslayer",
    },
    runes: [23, 22, 25, 19],
    types: [3, 1],
    excluded: "",
    classes: [],
    patch: "1.10",
    level: 53,
    ladder: false,
    reworked: true,
    bugged: {
      status: false,
      message: [],
    },
    stats: {
      ru: [
        "+30% к скорости атаки",
        "+<span class='varies'>270-300</span>% к урону",
        "-25% к защите цели",
        "20% к рейтингу атаки",
        "+33% к вероятности нанести сокрушающий удар",
        "+50% к вероятности нанести открытую рану",
        "+6 к умению «Возмездие» (только для паладинов)",
        "Запрещает монстрам лечиться",
        "+10 к силе",
        "Восполняет 1 ед. прочности раз в 20 сек.",
      ],
      en: [
        "+30% Increased Attack Speed",
        "+<span class='varies'>270-300</span>% Enhanced Damage (varies)",
        "-25% Target Defense",
        "20% Bonus To Attack Rating",
        "+33% Chance of Crushing Blow",
        "+50% Chance of Open Wounds",
        "+6 To Vengeance (paladin only)",
        "Prevent Monster Heal",
        "+10 To Strength",
        "Repairs 1 durability in 20 seconds",
      ],
    },
    complete: false,
    old: {
      runes: [23, 22, 25, 19],
      types: [3, 1],
      stats: {
        ru: [
          "+30% к скорости атаки",
          "+(230-270)% к урону",
          "-25% к защите цели",
          "+20% к рейтингу атаки",
          "+33% к вероятности нанести сокрушающий удар",
          "+50% к вероятности нанести открытую рану",
          "+1 к умению «Возмездие»",
          "Запрещает монстрам лечиться",
          "+10 к силе",
          "+40% к золоту за убийство монстров",
        ],
        en: [
          "+30% Increased Attack Speed",
          "+<span class='varies varies--old'>230-270</span>% Enhanced Damage (varies)",
          "-25% Target Defense",
          "20% Bonus To Attack Rating",
          "33% Chance of Crushing Blow",
          "50% Chance of Open Wounds",
          "+1 To Vengeance",
          "Prevent Monster Heal",
          "+10 To Strength",
          "40% Extra Gold From Monsters",
        ],
      },
    },
  },

  {
    id: 56,
    name: {
      ru: "Разлом",
      en: "Rift",
    },
    runes: [15, 18, 20, 25],
    types: [9, 7],
    excluded: "",
    classes: [],
    patch: "1.10",
    level: 53,
    ladder: false,
    reworked: true,
    stats: {
      ru: [
        "Вероятность 20% применить умение «Ураган» 16-го уровня при ударе",
        "Вероятность 16% применить умение «Морозная сфера» 21-го уровня при атаке",
        "+20% к скорости атаки",
        "+20% к рейтингу атаки",
        "+15% к урону от умений льда",
        "+<span class='varies'>5-10</span> ко всем характеристикам",
        "+10 к ловкости",
        "+38% к урону, приходящемуся на ману",
        "+75% к золоту за убийство монстров",
        "«Железная дева» 15-го уровня (40 зарядов)",
        "Требования -20%",
      ],
      en: [
        "20% Chance To Cast Level 16 Hurricane On Striking",
        "16% Chance To Cast Level 21 Frozen Orb On Attack",
        "+20% Increased Attack Speed",
        "20% Bonus To Attack Rating",
        "+15% Cold Skill Damage",
        "+<span class='varies'>5-10</span> To All Stats (varies)",
        "+10 To Dexterity",
        "+38% Damage Taken Goes To Mana",
        "75% Extra Gold From Monsters",
        "Level 15 Iron Maiden (40 Charges)",
        "Requirements -20%",
      ],
    },
    complete: false,
    old: {
      runes: [15, 18, 20, 25],
      types: [9, 7],
      stats: {
        ru: [
          "Вероятность 20% применить умение «Торнадо» 16-го уровня при ударе",
          "Вероятность 16% применить умение «Морозная сфера» 21-го уровня при атаке",
          "+20% к рейтингу атаки",
          "+160-250 магического урона",
          "+60-180 урона от огня",
          "+(5-10) ко всем характеристикам",
          "+10 к ловкости",
          "+38% к урону, приходящемуся на ману",
          "+75% к золоту за убийство монстров",
          "«Железная дева» 15-го уровня (40/40 зарядов)",
          "Требования -20%",
        ],
        en: [
          "20% Chance To Cast Level 16 Tornado On Striking",
          "16% Chance To Cast Level 21 Frozen Orb On Attack",
          "20% Bonus To Attack Rating",
          "Adds 160-250 Magic Damage",
          "Adds 60-180 Fire Damage",
          "+<span class='varies varies--old'>5-10</span> To All Stats (varies)",
          "+10 To Dexterity",
          "38% Damage Taken Goes To Mana",
          "75% Extra Gold From Monsters",
          "Level 15 Iron Maiden (40 Charges)",
          "Requirements -20%",
        ],
      },
    },
  },

  {
    id: 57,
    name: {
      ru: "Убеждение",
      en: "Principle",
    },
    runes: [8, 24, 2],
    types: [17],
    excluded: "",
    classes: ["Paladin"],
    patch: "1.11",
    level: 51,
    ladder: false,
    reworked: true,
    stats: {
      ru: [
        "Вероятность 15% применить умение «Длань небес» 25-го уровня при ударе",
        "+2 к уровню умений падалина",
        "+50% урона по нежети",
        "+<span class='varies'>100-150</span> к здоровью",
        "Выносливость снижается на 15% медленнее",
        "+30% к сопротивлению огню",
        "+75% к вероятности найти магический предмет",
      ],
      en: [
        "15% chance to cast level 25 Fist of Heavens on striking",
        "+2 To Paladin Skill Levels",
        "+50% Damage to Undead",
        "+<span class='varies'>100-150</span> To Life (varies)",
        "15% Slower Stamina Drain",
        "Fire Resist +30%",
        "+75% Better Chance of Getting Magic Items",
      ],
    },
    complete: false,
    old: {
      runes: [8, 25, 2],
      types: [17],
      stats: {
        ru: [
          "Вероятность 100% применить умение «Заряд света» 5-го уровня при ударе",
          "+2 к умениям паладина",
          "Выносливость снижается на 15% медленнее",
          "+5% к максимальному сопротивлению яду",
          "+30% к сопротивлению огню",
        ],
        en: [
          "100% Chance To Cast Level 5 Holy Bolt On Striking",
          "+2 To Paladin Skill Levels",
          "15% Slower Stamina Drain",
          "+5% To Maximum Poison Resist",
          "Fire Resist +30%",
        ],
      },
    },
  },

  {
    id: 58,
    name: {
      ru: "Мозаика",
      en: "Mosaic",
    },
    runes: [23, 25, 11],
    types: [19],
    excluded: "",
    classes: ["Assassin"],
    patch: "2.6",
    level: 53,
    ladder: true,
    reworked: true,
    stats: {
      ru: [
        "+50% к скорости атаки",
        "+20% к рейтингу атаки",
        "Похищает 7% здоровья за удар",
        "+8-15% к урону от умений льда",
        "+8-15% к урону от умений молнии",
        "+8-15% к урону от умений огня",
        "+5 к умению «Удар феникса» (только для ассасинов)",
        "+5 к умению «Ледяные клинки» (только для ассасинов)",
        "+5 к умению «Грозовые когти» (только для ассасинов)",
        "Запрещает монстрам лечиться",
      ],
      en: [
        "+50% Increased Attack Speed",
        "+20% Bonus to Attack Rating",
        "7% Life Slolen Per Hit",
        "+8-15% to Cold Skill Damage",
        "+8-15% to Lightning Skill Damage",
        "+8-15% to Fire Skill Damage",
        "+5 to Phoenix Strike (Assassin only)",
        "+5 to Blades of Ice (Assassin only)",
        "+5 to Claws of Thunder (Assassin only)",
        "Prevent Monster Heal",
      ],
    },
    complete: false,
    old: {
      runes: [23, 25, 11],
      types: [8],
      stats: {
        ru: [
          "+50% к вероятности завершающих приемов не потратить заряды",
          "При срабатывании этого эффекта время действия зарядов обновляется",
          "+2 к боевым искусствам (только для ассасинов)",
          "+20% к скорости атаки",
          "+(200-250)% к урону",
          "+20% к рейтингу атаки",
          "Похищает 7% здоровья за удар",
          "+(8-15)% к урону от умений льда",
          "+(8-15)% к урону от умений молнии",
          "+(8-15)% к урону от умений огня",
          "Запрещает монстрам лечиться",
        ],
        en: [
          "+50% chance for finishing moves to not consume charges",
          "+2 to Martial Arts (Assassin only)",
          "+20% Increased Attack Speed",
          "+<span class='varies varies--old'>200-250</span>% Enhanced Damage (varies)",
          "+20% Bonus to Attack Rating",
          "7% Life Steal",
          "+8-15% to Cold Skill Damage",
          "+8-15% to Lightning Skill Damage",
          "+8-15% to Fire Skill Damage",
          "Prevent Monster Heal",
        ],
      },
    },
  },

  {
    id: 67,
    name: {
      ru: "Печаль",
      en: "Grief",
    },
    runes: [5, 3, 28, 23, 8],
    types: [3, 1],
    excluded: "",
    patch: "1.10",
    level: 59,
    ladder: false,
    reworked: true,
    stats: {
      ru: [
        "Вероятность 35% применить умение «Яд» 15-го уровня при ударе",
        "+<span class='varies'>30-40</span>% к скорости атаки",
        "+<span class='varies'>320-360</span> к урону",
        "Игнорирует защиту цели",
        "-25% к защите цели",
        "+(1.875*clvl)% к урону по демонам (зависит от уровня персонажа)",
        "+5-30 урона от огня",
        "-<span class='varies'>20-25</span>% к сопротивлению яду у врага",
        "+20% к вероятности нанести смертельный удар",
        "Запрещает монстрам лечиться",
        "+<span class='varies'>10-15</span> к здоровью при убийстве",
        "+2 к мане при убийстве",
      ],
      en: [
        "35% Chance To Cast Level 15 Venom On Striking",
        "+<span class='varies'>30-40</span>% Increased Attack Speed (varies)",
        "Damage +<span class='varies'>320-360</span> (varies)",
        "Ignore Target's Defense",
        "-25% Target Defense",
        "+(1.875 per character level) 1.875-185.625% Damage To Demons (Based on Character Level) ",
        "Adds 5-30 Fire Damage",
        "-<span class='varies'>20-25</span>% To Enemy Poison Resistance (varies)",
        "+20% Deadly Strike",
        "Prevent Monster Heal",
        "+<span class='varies'>10-15</span> Life After Each Kill (varies)",
        "+2 To Mana After Each Kill",
      ],
    },
    complete: false,
    old: {
      runes: [5, 3, 28, 23, 8],
      types: [3, 1],
      stats: {
        ru: [
          "Вероятность 35% применить умение «Яд» 15-го уровня при ударе",
          "+(30-40)% к скорости атаки",
          "+(340-400) к урону",
          "Игнорирует защиту цели",
          "-25% к защите цели",
          "+(1.875*clvl)% к урону по демонам (зависит от уровня персонажа)",
          "+5-30 урона от огня",
          "-(20-25)% к сопротивлению яду у врага",
          "+20% к вероятности нанести смертельный удар",
          "Запрещает монстрам лечиться",
          "+2 к мане при убийстве",
          "+(10-15) к здоровью при убийстве",
        ],
        en: [
          "35% Chance To Cast Level 15 Venom On Striking",
          "+<span class='varies varies--old'>30-40</span>% Increased Attack Speed (varies)",
          "Damage +<span class='varies varies--old'>340-400</span> (varies)",
          "Ignore Target's Defense",
          "+(1.875 per character level) 1.875-185.625% Damage To Demons (Based on Character Level) ",
          "-<span class='varies varies--old'>20-25</span>% To Enemy Poison Resistance (varies)",
          "+<span class='varies varies--old'>10-15</span> Life After Each Kill (varies)",
          "20% Deadly Strike",
          "Prevent Monster Heal",
          "+2 To Mana After Each Kill",
          "Adds 5-30 Fire Damage",
          "-25% Target Defense",
        ],
      },
    },
  },

  {
    id: 69,
    name: {
      ru: "Ветер",
      en: "Wind",
    },
    runes: [29, 1],
    types: [4],
    excluded: "",
    patch: "1.10",
    level: 61,
    ladder: false,
    reworked: true,
    stats: {
      ru: [
        "Вероятность 25% применить умение Смерч 9-го уровня при ударе",
        "+1 ко всем умениям",
        "+20% к скороти ходьбы и бега",
        "+40% к скорости атаки",
        "+10% к скорости применения умений",
        "+<span class='varies'>280-320</span>к урону",
        "-50% к защите цели",
        "+50 к рейтингу атаки",
        "При ударе ослепляет цель",
        "+1 к радиусу обзора",
      ],
      en: [
        "25% Chance To Cast Level 9 Twister On Striking",
        "+1 to All Skills",
        "+20% Faster Run/Walk",
        "+40% Increased Attack Speed",
        "+10% Faster Cast Rate",
        "Damage +<span class='varies'>280-320</span> (varies)",
        "-50% Target Defense",
        "+50 To Attack Rating",
        "Hit Blinds Target",
        "+1 To Light Radius",
      ],
    },
    complete: false,
    old: {
      runes: [29, 1],
      types: [4],
      stats: {
        ru: [
          "Вероятность 10% применить умение «Торнадо» 9-го уровня при ударе",
          "+20% к скорости ходьбы и бега",
          "+40% к скорости атаки",
          "+15% к ускоренному восстановлению от удара",
          "+(120-160)% к урону",
          "-50% к защите цели",
          "+50 к рейтингу атаки",
          "При ударе ослепляет цель",
          "+1 к радиусу обзора",
          "«Смерч» 13-го уровня (127/127 зарядов)",
        ],
        en: [
          "10% Chance To Cast Level 9 Tornado On Striking",
          "+20% Faster Run/Walk",
          "+40% Increased Attack Speed",
          "+15% Faster Hit Recovery",
          "+<span class='varies varies--old'>120-160</span>% Enhanced Damage (varies)",
          "-50% Target Defense",
          "+50 To Attack Rating",
          "Hit Blinds Target",
          "+1 To Light Radius",
          "Level 13 Twister (127 Charges)",
        ],
      },
    },
  },

  {
    id: 72,
    name: {
      ru: "Цепи чести",
      en: "Chains of Honor",
    },
    runes: [14, 22, 30, 24],
    types: [17],
    excluded: "",
    patch: "1.10",
    level: 63,
    ladder: false,
    reworked: true,
    stats: {
      ru: [
        "+15% к скорости атаки",
        "+400% к урону по демонам",
        "Похищает 10% здоровья за удар",
        "120% к защите",
        "Восполняет +7 здоровья",
        "+65 к сопротивлению всем видам урона",
        "Урон уменьшен на 8%",
        "-25 к магическому урону",
        "+75% к вероятности найти магический предмет",
      ],
      en: [
        "+15% Increased Attack Speed",
        "+400% Damage To Demons",
        "10% Life Stolen Per Hit",
        "120% Enhanced Defense",
        "Replenish Life +7",
        "All Resistances +65",
        "Damage Reduced By 8%",
        "Magic damage reduced by 25",
        "+75% Better Chance of Getting Magic Items",
      ],
    },
    complete: false,
    old: {
      runes: [14, 22, 30, 24],
      types: [17],
      stats: {
        ru: [
          "+2 ко всем умениям",
          "+200% к урону по демонам",
          "+100% урона по нежити",
          "Похищает 8% здоровья за удар",
          "+70% к защите",
          "+20 к силе",
          "Восполняет +7 здоровья",
          "+65 к сопротивлению всем видам урона",
          "Урон уменьшен на 8%",
          "+25% к вероятности найти магический предмет",
        ],
        en: [
          "+2 To All Skills",
          "+200% Damage To Demons",
          "+100% Damage To Undead",
          "8% Life Stolen Per Hit",
          "+70% Enhanced Defense",
          "+20 To Strength",
          "Replenish Life +7",
          "All Resistances +65",
          "Damage Reduced By 8%",
          "25% Better Chance of Getting Magic Items",
        ],
      },
    },
  },

  {
    id: 73,
    name: {
      ru: "Вечность",
      en: "Eternity",
    },
    runes: [11, 30, 24, 12, 29],
    types: [4],
    excluded: "",
    patch: "1.10",
    level: 63,
    ladder: false,
    reworked: true,
    stats: {
      ru: [
        "Не теряет прочности",
        "+<span class='varies'>310-350</span>% к урону",
        "+9 к минимальному урону",
        "Похищает 7% здоровья за удар",
        "20% к вероятности нанести сокрущающий удар",
        "+6 к умению «Оживление»",
        "+1 к умению «Телепортация»",
        "+6 к умению «Чары»",
        "При ударе ослепляет цель",
        "Замедляет цель на 33%",
        "30% к вероятности найти магический предмет",
      ],
      en: [
        "Indestructible",
        "+<span class='varies'>310-350</span>% Enhanced Damage (varies)",
        "+9 To Minimum Damage",
        "7% Life Stolen Per Hit",
        "20% Chance of Crushing Blow",
        "+6 to Revive",
        "+1 to Teleport",
        "+6 to Enchant",
        "Hit Blinds Target",
        "Slows Target By 33%",
        "30% Better Chance Of Getting Magic Items",
      ],
    },
    complete: false,
    old: {
      runes: [11, 30, 24, 12, 29],
      types: [4],
      stats: {
        ru: [
          "Не теряет прочности",
          "+(260-310)% к урону",
          "+9 к минимальному урону",
          "Похищает 7% здоровья при ударе",
          "+20% к вероятности нанести сокрушающий удар",
          "При ударе ослепляет цель",
          "Замедляет цель на 33%",
          "Восполняет 16% маны",
          "Нельзя заморозить",
          "+30% к вероятности найти магический предмет",
          "«Оживление» 8-го уровня (88/88 зарядов)",
        ],
        en: [
          "Indestructible",
          "+<span class='varies varies--old'>260-310</span>% Enhanced Damage (varies)",
          "+9 To Minimum Damage",
          "7% Life Stolen Per Hit",
          "20% Chance of Crushing Blow",
          "Hit Blinds Target",
          "Slows Target By 33%",
          "Regenerate Mana 16%",
          "Replenish Life +16",
          "Cannot Be Frozen",
          "30% Better Chance Of Getting Magic Items",
          "Level 8 Revive (88 Charges)",
        ],
      },
    },
  },

  {
    id: 75,
    name: {
      ru: "Гнев",
      en: "Wrath",
    },
    runes: [21, 17, 30, 23],
    types: [6],
    excluded: "",
    patch: "1.10",
    level: 63,
    ladder: false,
    reworked: true,
    stats: {
      ru: [
        "Вероятность 5% применить умение «Похищение жизни» 10-го уровня при ударе",
        "Вероятность 15% применить умение «Усиление урона» 14-го уровня при ударе",
        "+20% к скорости атаки",
        "+300% к урону",
        "75% к урону по демонам",
        "+100 к рейтингу атаки против демонов",
        "+20% к вероятности нанести сокрушающий удар",
        "+1 к умению «Залп»",
        "Запрещает монстрам лечиться",
        "+10 к энергии",
        "Нельзя заморозить",
      ],
      en: [
        "5% Chance To Cast Level 10 Life Tap On Striking",
        "15% Chance To Cast Level 14 Amplify Damage On Striking",
        "+20% Increased Attack Speed",
        "+300% Enhanced Damage",
        "75% Damage To Demons",
        "+100 To Attack Rating Against Demons",
        "20% Chance of Crushing Blow",
        "+1 to Multiple Shot",
        "Prevent Monster Heal",
        "+10 To Energy",
        "Cannot Be Frozen",
      ],
    },
    complete: false,
    old: {
      runes: [21, 17, 30, 23],
      types: [6],
      stats: {
        ru: [
          "Вероятность 30% применить умение «Одряхление» 1-го уровня при ударе",
          "Вероятность 5% применить умение «Похищение жизни» 10-го уровня за удар",
          "+375% к урону по демонам",
          "+100 к рейтингу атаки против демонов",
          "+250-300% урона по нежити",
          "+85-120 магического урона",
          "+41-240 урона от молнии",
          "+20% к вероятности нанести сокрушающий удар",
          "Запрещает монстрам лечиться",
          "+10 к энергии",
          "Нельзя заморозить",
        ],
        en: [
          "30% Chance To Cast Level 1 Decrepify On Striking",
          "5% Chance To Cast Level 10 Life Tap On Striking",
          "+375% Damage To Demons",
          "+100 To Attack Rating Against Demons",
          "+<span class='varies varies--old'>250-300</span>% Damage To Undead (varies)",
          "Adds 85-120 Magic Damage",
          "Adds 41-240 Lightning Damage",
          "20% Chance of Crushing Blow",
          "Prevent Monster Heal",
          "+10 To Energy",
          "Cannot Be Frozen",
        ],
      },
    },
  },

  {
    id: 78,
    name: {
      ru: "Голод",
      en: "Famine",
    },
    runes: [19, 27, 9, 31],
    types: [6],
    excluded: "",
    patch: "1.10",
    level: 65,
    ladder: false,
    reworked: true,
    bugged: {
      status: false,
      message: [],
    },
    stats: {
      ru: [
        "Вероятность 10% применить умение «Снижение сопротивления» 7-го уровня при ударе",
        "+85% к скорости атаки",
        "Взрывные стрелы или болты",
        "250% к урону",
        "Игнорирует защиту цели",
        "+520-840 урона от огня",
        "+1-2030 урона от молнии",
        "+1 к умению «Мастер огня»",
        "+10 к силе",
      ],
      en: [
        "10% chance to cast level 7 Lower Resist on striking",
        "+85% Increased Attack Speed",
        "Fires Explosive arrows or bolts (Level 12)",
        "250% Enhanced Damage",
        "Ignore Target's Defense",
        "Adds 520-840 Fire Damage",
        "Adds 1-2030 Lightning Damage",
        "+1 to Fire Mastery ",
        "+10 To Strength",
      ],
    },
    complete: false,
    old: {
      runes: [19, 27, 9, 31],
      types: [1, 11],
      stats: {
        ru: [
          "+30% к скорости атаки",
          "+(320-370)% к урону",
          "Игнорирует защиту цели",
          "+180-200 магического урона",
          "+50-200 урона от огня",
          "+51-250 урона от молнии",
          "+50-200 урона от льда",
          "Похищает 12% здоровья при ударе",
          "Запрещает монстрам лечиться",
          "+10 к силе",
        ],
        en: [
          "+30% Increased Attack Speed",
          "+<span class='varies varies--old'>320-370</span>% Enhanced Damage (varies)",
          "Ignore Target's Defense",
          "Adds 180-200 Magic Damage",
          "Adds 50-200 Fire Damage",
          "Adds 51-250 Lightning Damage",
          "Adds 50-200 Cold Damage",
          "12% Life Stolen Per Hit",
          "Prevent Monster Heal",
          "+10 To Strength",
        ],
      },
    },
  },

  {
    id: 79,
    name: {
      ru: "Клеймо",
      en: "Brand",
    },
    runes: [31, 28, 23, 25],
    types: [6],
    excluded: "",
    patch: "1.10",
    level: 65,
    ladder: false,
    reworked: true,
    stats: {
      ru: [
        "Вероятность 30% применить умение «Одряхление» 1-го уровня при ударе",
        "Вероятность 100% применить умение «Костяное копье» 18-го уровня при ударе",
        "Взрывные стрелы или болты",
        "+<span class='varies'>365-400</span>% к урону",
        "Игнорирует защиту цели",
        "20% к рейтингу атаки",
        "+<span class='varies'>280-330</span>% к урону по демонам",
        "+50% к вероятности нанести смертельный удар",
        "Запрещает монстрам лечиться",
        "Отбрасывание врагов",
      ],
      en: [
        "30% Chance To Cast Level 1 Decrepify On Striking",
        "100% Chance To Cast Level 18 Bone Spear On Striking",
        "Fires Explosive Arrows or Bolts (15)",
        "+<span class='varies'>365-400</span>% Enhanced Damage (varies)",
        "Ignore Target's Defense",
        "20% Bonus to Attack Rating",
        "+<span class='varies'>280-330</span>% Damage To Demons (varies)",
        "+50% Deadly Strike",
        "Prevent Monster Heal",
        "Knockback",
      ],
    },
    complete: false,
    old: {
      runes: [31, 28, 23, 25],
      types: [6],
      stats: {
        ru: [
          "Вероятность 35% применить умение «Усиление урона» 14-го уровня при получении урона",
          "Вероятность 100% применить умение «Костяное копье» 18-го уровня при ударе",
          "Взрывные стрелы или болты (15-го уровня)",
          "+(260-340)% к урону",
          "Игнорирует защиту цели",
          "+20% к рейтингу атаки",
          "+(280-330)% к урону по демонам",
          "+20% к вероятности нанести смертельный удар",
          "Запрещает монстрам лечиться",
          "Отбрасывает врагов",
        ],
        en: [
          "35% Chance To Cast Level 14 Amplify Damage When Struck",
          "100% Chance To Cast Level 18 Bone Spear On Striking",
          "+<span class='varies varies--old'>260-340</span>% Enhanced Damage (varies)",
          "Ignore Target's Defense",
          "20% Bonus to Attack Rating",
          "+<span class='varies varies--old'>280-330</span>% Damage To Demons (varies)",
          "20% Deadly Strike",
          "Prevent Monster Heal",
          "Knockback",
          "Fires Explosive Arrows or Bolts (15)",
        ],
      },
    },
  },

  {
    id: 80,
    name: {
      ru: "Разрушение",
      en: "Destruction",
    },
    runes: [26, 28, 30, 31, 18],
    types: [12],
    excluded: "",
    patch: "1.10",
    level: 65,
    ladder: false,
    reworked: true,
    stats: {
      ru: [
        "15% chance to cast level 30 Fissure on striking",
        "10% chance to cast level 25 Immolation Arrow on striking",
        "10% chance to cast level 20 Death Sentry when you kill an enemy",
        "10% chance to cast Level 20 Armageddon when you kill an enemy",
        "20% increased attack speed",
        "+350% Enhanced Damage",
        "Ignore Target's Defense",
        "7% Mana Stolen Per Hit",
        "20% Chance Of Crushing Blow",
        "20% Deadly Strike",
        "Knockback",
        "+10 To Dexterity",
      ],
      en: [
        "15% chance to cast level 30 Fissure on striking",
        "10% chance to cast level 25 Immolation Arrow on striking",
        "10% chance to cast level 20 Death Sentry when you kill an enemy",
        "10% chance to cast Level 20 Armageddon when you kill an enemy",
        "20% increased attack speed",
        "+350% Enhanced Damage",
        "Ignore Target's Defense",
        "7% Mana Stolen Per Hit",
        "20% Chance Of Crushing Blow",
        "20% Deadly Strike",
        "Knockback",
        "+10 To Dexterity",
      ],
    },
    complete: false,
    old: {
      runes: [26, 28, 30, 31, 18],
      types: [9, 3],
      stats: {
        ru: [
          "Вероятность 23% применить умение «Вулкан» 12-го уровня при ударе",
          "Вероятность 5% применить умение «Пылающий валун» 23-го уровня при ударе",
          "Вероятность 100% применить умение «Метеорит» 45-го уровня после смерти",
          "Вероятность 15% применить умение «Кольцо молний» 22-го уровня при атаке",
          "+350% к урону",
          "Игнорирует защиту цели",
          "+100-180 магического урона",
          "Похищает 7% маны при ударе",
          "+20% к вероятности нанести сокрушающий удар",
          "+20% к вероятности нанести смертельный удар",
          "Запрещает монстрам лечиться",
          "+10 к ловкости",
        ],
        en: [
          "23% Chance To Cast Level 12 Volcano On Striking",
          "5% Chance To Cast Level 23 Molten Boulder On Striking",
          "100% Chance To Cast level 45 Meteor When You Die",
          "15% Chance To Cast Level 22 Nova On Attack",
          "+350% Enhanced Damage",
          "Ignore Target's Defense",
          "Adds 100-180 Magic Damage",
          "7% Mana Stolen Per Hit",
          "20% Chance Of Crushing Blow",
          "20% Deadly Strike",
          "Prevent Monster Heal",
          "+10 To Dexterity",
        ],
      },
    },
  },

  {
    id: 83,
    name: {
      ru: "Лёд",
      en: "Ice",
    },
    runes: [11, 13, 31, 28],
    types: [6],
    excluded: "",
    patch: "1.10",
    level: 65,
    ladder: false,
    reworked: true,
    bugged: {
      status: false,
      message: [],
    },
    stats: {
      ru: [
        "100% chance to cast level 26 Arctic Blast on striking",
        "Level 18 Holy Freeze Aura When Equipped",
        "+90% Increased Attack Speed",
        "+<span class='varies'>285-310</span>% Enhanced Damage (varies)",
        "Ignore Target's Defense",
        "7% Life Stolen Per Hit",
        "-20% To Enemy Cold Resistance",
        "+<span class='varies'>25-30</span>% To Cold Skill Damage (varies)",
        "20% Deadly Strike",
        "3.125-309.375 Extra Gold From Monsters (Based on Character Level)",
      ],
      en: [
        "100% chance to cast level 26 Arctic Blast on striking",
        "Level 18 Holy Freeze Aura When Equipped",
        "+90% Increased Attack Speed",
        "+<span class='varies'>285-310</span>% Enhanced Damage (varies)",
        "Ignore Target's Defense",
        "7% Life Stolen Per Hit",
        "-20% To Enemy Cold Resistance",
        "+<span class='varies'>25-30</span>% To Cold Skill Damage (varies)",
        "20% Deadly Strike",
        "3.125-309.375 Extra Gold From Monsters (Based on Character Level)",
      ],
    },
    complete: false,
    old: {
      runes: [11, 13, 31, 28],
      types: [6],
      stats: {
        ru: [
          "Вероятность 100% применить умение «Снежная буря» 40-го уровня при достижении нового уровня",
          "Вероятность 25% применить умение «Кольцо льда» 22-го уровня при ударе",
          "При надевании дает ауру «Священный холод» 18-го уровня",
          "+20% к скорости атки",
          "+(140-210)% к урону",
          "Игнорирует защиту цели",
          "+(25-30)% к урону от умений льда",
          "Похищает 7% здоровья за удар",
          "-20% к сопротивлению льду у врага",
          "+20% к вероятности нанести смертельный удар",
          "+(3.125%*clvl)% к золоту за убийство монстров (зависит от уровня персонажа)",
        ],
        en: [
          "100% Chance To Cast Level 40 Blizzard When You Level-up",
          "25% Chance To Cast Level 22 Frost Nova On Striking",
          "Level 18 Holy Freeze Aura When Equipped",
          "+20% Increased Attack Speed",
          "+<span class='varies varies--old'>140-210</span>% Enhanced Damage (varies)",
          "Ignore Target's Defense",
          "+<span class='varies varies--old'>25-30</span>% To Cold Skill Damage (varies)",
          "-20% To Enemy Cold Resistance",
          "7% Life Stolen Per Hit",
          "20% Deadly Strike",
          "3.125-309.375 Extra Gold From Monsters (Based on Character Level)",
        ],
      },
    },
  },

  {
    id: 84,
    name: {
      ru: "Последняя воля",
      en: "Last Wish",
    },
    runes: [31, 23, 31, 29, 31, 30],
    types: [12],
    excluded: "",
    patch: "1.10",
    level: 65,
    ladder: false,
    reworked: true,
    stats: {
      ru: [
        "10% Chance To Cast Level 18 Life Tap On Striking",
        "6% Chance To Cast Level 11 Burst of Speed When you kill an enemy",
        "Level <span class='varies'>12-17</span> Might Aura When Equipped (varies)",
        "+496% Enhanced Damage",
        "+ (2.5 Per Character Level) 2-247 To Maximum Damage (Based On Character Level)",
        "Ignore Target's Defense",
        "+<span class='varies'>60-70</span>% Chance of Crushing Blow (varies)",
        "+<span class='varies'>60-70</span>% Deadly Strike (varies)",
        "Prevent Monster Heal",
        "Hit Blinds Target",
      ],
      en: [
        "10% Chance To Cast Level 18 Life Tap On Striking",
        "6% Chance To Cast Level 11 Burst of Speed When you kill an enemy",
        "Level <span class='varies'>12-17</span> Might Aura When Equipped (varies)",
        "+496% Enhanced Damage",
        "+ (2.5 Per Character Level) 2-247 To Maximum Damage (Based On Character Level)",
        "Ignore Target's Defense",
        "+<span class='varies'>60-70</span>% Chance of Crushing Blow (varies)",
        "+<span class='varies'>60-70</span>% Deadly Strike (varies)",
        "Prevent Monster Heal",
        "Hit Blinds Target",
      ],
    },
    complete: false,
    old: {
      runes: [31, 23, 31, 29, 31, 30],
      types: [3, 11, 1],
      stats: {
        ru: [
          "Вероятность 6% применить умение «Уход в тень» 11-го уровня при получении урона",
          "Вероятность 10% применить умение «Похищение жизни» 18-го уровня при ударе",
          "Вероятность 20% применить умение «Залп молний» 20-го уровня при атаке",
          "При надевании дает ауру «Мощь» 17-го уровня",
          "+(330-375)% к урону",
          "Игнорирует защиту цели",
          "+(60-70)% к вероятности нанести сокрушающий удар",
          "Запрещает монстрам лечиться",
          "При ударе ослепляет цель",
          "+(0.5*clvl)% к вероятности найти магический предмет (зависит от уровня персонажа)",
        ],
        en: [
          "6% Chance To Cast Level 11 Fade When Struck",
          "10% Chance To Cast Level 18 Life Tap On Striking",
          "20% Chance To Cast Level 20 Charged Bolt On Attack",
          "Level 17 Might Aura When Equipped",
          "+<span class='varies varies--old'>330-375</span>% Enhanced Damage (varies)",
          "Ignore Target's Defense",
          "<span class='varies varies--old'>60-70</span>% Chance of Crushing Blow (varies)",
          "Prevent Monster Heal",
          "Hit Blinds Target",
          "+(0.5 per character level) 0.5-49.5% Chance of Getting Magic Items (Based on Character Level)",
        ],
      },
    },
  },

  {
    id: 85,
    name: {
      ru: "Феникс",
      en: "Phoenix",
    },
    runes: [26, 26, 28, 31],
    types: [12, 16],
    excluded: "",
    patch: "1.10",
    level: 65,
    ladder: false,
    reworked: true,
    bugged: {
      status: false,
      message: [],
    },
    stats: {
      ru: [
        "#Оружие#",
        "Вероятность 100% применить умение «Огненный след» 40-го уровня при достижении нового уровня",
        "Вероятность 20% применить умение «Огненная буря» 44-го уровня при ударе",
        "При надевании дает ауру «Искупление» <span class='varies'>10-15</span>-го уровня",
        "+<span class='varies'>350-400</span>% к урону",
        "Игнорирует защиту цели",
        "Похищает 14% маны за удар",
        "-28% к сопротивлению огню у врага",
        "+20% к вероятности нанести смертельный удар",
        "+<span class='varies'>15-21</span> к поглощению огня",
        "Восполняет 1 ед. прочности раз в 5 сек.",

        "#Щиты#",
        "Вероятность 100% применить умение «Огненный след» 40-го уровня при достижении нового уровня",
        "Вероятность 20% применить умение «Огненная буря» 44-го уровня при ударе",
        "При надевании дает ауру «Искупление» <span class='varies'>10-15</span>-го уровня",
        "+<span class='varies'>350-400</span>% к урону",
        "+50 к здоровью",
        "+5% к максимальному сопротивлению молнии",
        "+10% к максимальному сопротивлению огню",
        "+<span class='varies'>15-21</span> к поглощению огня",
        "Восполняет 1 ед. прочности раз в 5 сек.",
      ],
      en: [
        "#Weapons#",
        "100% Chance To Cast level 40 Blaze When You Level-up",
        "20% Chance to cast level 44 Firestorm on striking",
        "Level <span class='varies'>10-15</span> Redemption Aura When Equipped (varies)",
        "+<span class='varies'>350-400</span>% Enhanced Damage (varies)",
        "Ignores Target Defense",
        "14% Mana Stolen Per Hit",
        "-28% To Enemy Fire Resistance",
        "20% Deadly Strike",
        "+<span class='varies'>15-21</span> Fire Absorb (varies)",
        "Repairs 1 durability in 5 seconds",
        "#Shields#",
        "100% Chance To Cast level 40 Blaze When You Level-up",
        "20% Chance to cast level 44 Firestorm on striking",
        "Level <span class='varies'>10-15</span> Redemption Aura When Equipped (varies)",
        "+<span class='varies'>350-400</span>% Enhanced Damage (varies)",
        "-28% To Enemy Fire Resistance",
        "+50 To Life",
        "+5% To Maximum Lightning Resist",
        "+10% To Maximum Fire Resist",
        "+<span class='varies'>15-21</span> Fire Absorb (varies)",
        "Repairs 1 durability in 5 seconds",
      ],
    },
    complete: false,
    old: {
      runes: [26, 26, 28, 31],
      types: [12, 16],
      stats: {
        ru: [
          "#Оружие#",
          "Вероятность 100% применить умение «Огненный след» 40-го уровня при достижении нового уровня",
          "Вероятность 40% применить умение «Огненная буря» 22-го уровня при ударе",
          "При надевании дает ауру «Искупление» (10-15)-го уровня",
          "+(350-400)% к урону",
          "-28% к сопротивлению огню у врага",
          "+(350-400) к защите от снарядов",
          "+(15-21) к поглощению огня",
          "Игнорирует защиту цели",
          "Похищает 15% маны за удар",
          "+20% к вероятности нанести смертельный удар",
          "#Щиты#",
          "Вероятность 100% применить умение «Огненный след» 40-го уровня при достижении нового уровня",
          "Вероятность 40% применить умение «Огненная буря» 22-го уровня при ударе",
          "При надевании дает ауру «Искупление» (10-15)-го уровня",
          "+(350-400)% к урону",
          "-28% к сопротивлению огню у врага",
          "+(350-400) к защите от снарядов",
          "+(15-21) к поглощению огня",
          "+50 к здоровью",
          "+5% к максимальному сопротивлению молнии",
          "+10% к максимальному сопротивлению огню",
        ],
        en: [
          "#Weapons#",
          "100% Chance To Cast level 40 Blaze When You Level-up",
          "40% Chance To Cast Level 22 Firestorm On Striking",
          "Level 10-15 Redemption Aura When Equipped (varies)",
          "+<span class='varies varies--old'>350-400</span>% Enhanced Damage (varies)",
          "Ignores Target's Defense",
          "14% Mana Stolen Per Hit",
          "-28% To Enemy Fire Resistance",
          "20% Deadly Strike",
          "+<span class='varies varies--old'>350-400</span> Defense Vs. Missile (varies)",
          "+<span class='varies varies--old'>15-21</span> Fire Absorb (varies)",
          "#Shields#",
          "100% Chance To Cast level 40 Blaze When You Level-up",
          "40% Chance To Cast Level 22 Firestorm On Striking",
          "Level <span class='varies varies--old'>10-15</span> Redemption Aura When Equipped (varies)",
          "+<span class='varies varies--old'>350-400</span> Defense Vs. Missile (varies)",
          "+<span class='varies varies--old'>350-400</span>% Enhanced Damage (varies)",
          "-28% To Enemy Fire Resistance",
          "+50 To Life",
          "+5% To Maximum Lightning Resist",
          "+10% To Maximum Fire Resist",
          "+<span class='varies varies--old'>15-21</span> Fire Absorb (varies)",
        ],
      },
    },
  },

  {
    id: 86,
    name: {
      ru: "Гибель",
      en: "Doom",
    },
    runes: [15, 27, 22, 28, 32],
    types: [4],
    excluded: "",
    patch: "1.10",
    level: 67,
    ladder: false,
    reworked: true,
    bugged: {
      status: false,
      message: [],
    },
    stats: {
      ru: [
        "Вероятность 5% применить умение «Армагеддон» 18-го уровня при ударе",
        "При надевании дает ауру «Священный холод» 12-го уровня",
        "+2 ко всем умениям",
        "+45% к скорости атаки",
        "+<span class='varies'>330-370</span>% к урону",
        "-(<span class='varies'>40-60</span>)% к сопротивлению льду у врага",
        "+20% к вероятности нанести смертельный удар",
        "+25% к вероятности нанести открытую рану",
        "Замораживает цель +3",
        "Восполняет 1 ед. прочности раз в 5 сек.",
        "Требования -20%",
      ],
      en: [
        "5% Chance To Cast Level 18 Armageddon On Striking",
        "Level 12 Holy Freeze Aura When Equipped",
        "+2 To All Skills",
        "+45% Increased Attack Speed",
        "+<span class='varies'>330-370</span>% Enhanced Damage (varies)",
        "-<span class='varies'>40-60</span>% To Enemy Cold Resistance (varies)",
        "+20% Deadly Strike",
        "+25% Chance of Open Wounds",
        "Freezes Target +3",
        "Repairs 1 durability in 5 seconds",
        "Requirements -20%",
      ],
    },
    complete: false,
    old: {
      runes: [15, 27, 22, 28, 32],
      types: [1, 9, 11],
      stats: {
        ru: [
          "Вероятность 5% применить умение «Вулкан» 18-го уровня при ударе",
          "При надевании дает ауру «Священный холод» 12-го уровня",
          "+2 ко всем умениям",
          "+45% к скорости атаки",
          "+(330-370)% к урону",
          "-(40-60)% к сопротивлению льду у врага",
          "+20% к вероятности нанести смертельный удар",
          "+25% к вероятности нанести открытую рану",
          "Запрещает монстрам лечиться",
          "Замораживает цель +3",
          "Требования -20%",
        ],
        en: [
          "5% Chance To Cast Level 18 Volcano On Striking",
          "Level 12 Holy Freeze Aura When Equipped",
          "+2 To All Skills",
          "+45% Increased Attack Speed",
          "+<span class='varies varies--old'>330-370</span>% Enhanced Damage (varies)",
          "-<span class='varies varies--old'>40-60</span>% To Enemy Cold Resistance (varies)",
          "20% Deadly Strike",
          "25% Chance of Open Wounds",
          "Prevent Monster Heal",
          "Freezes Target +3",
          "Requirements -20%",
        ],
      },
    },
  },

  {
    id: 87,
    name: {
      ru: "Длань Правосудия",
      en: "Hand of Justice",
    },
    runes: [29, 32, 11, 28],
    types: [12],
    excluded: "",
    patch: "1.10",
    level: 67,
    ladder: false,
    reworked: true,
    stats: {
      ru: [
        "Вероятность 100% применить умение «Метеорит» 48-го уровня после смерти",
        "При надевании дает ауру «Священный огонь» 16-го уровня",
        "+33% к скорости атаки",
        "+<span class='varies'>280-330</span>% к урону",
        "Игнорирует защиту цели",
        "Похищает 7% здоровья при ударе",
        "-20% к сопротивлению огню у врага",
        "+20% к вероятности нанести смертельный удар",
        "При ударе ослепляет цель",
        "Замораживает цель +3",
      ],
      en: [
        "100% Chance To Cast Level 48 Meteor When You Die",
        "Level 16 Holy Fire Aura When Equipped",
        "+33% Increased Attack Speed",
        "+<span class='varies'>280-330</span>% Enhanced Damage (varies)",
        "Ignore Target's Defense",
        "7% Life Stolen Per Hit",
        "-20% To Enemy Fire Resistance",
        "+20% fire skill damage",
        "+20% Deadly Strike",
        "Hit Blinds Target",
        "Freezes Target +3",
      ],
    },
    complete: false,
    old: {
      runes: [29, 32, 11, 28],
      types: [12],
      stats: {
        ru: [
          "Вероятность 100% применить умение «Огненный след» 36-го уровня при достижении нового уровня",
          "Вероятность 100% применить умение «Метеорит» 48-го уровня после смерти",
          "При надевании дает ауру «Священный огонь» 16-го уровня",
          "+33% к скорости атаки",
          "+(280-330)% к урону",
          "Игнорирует защиту цели",
          "-20% к сопротивлению огню у врага",
          "Похищает 7% здоровья при ударе",
          "+20% к вероятности нанести смертельный удар",
          "При ударе ослепляет цель",
          "Замораживает цель +3",
        ],
        en: [
          "100% Chance To Cast Level 36 Blaze When You Level-Up",
          "100% Chance To Cast Level 48 Meteor When You Die",
          "Level 16 Holy Fire Aura When Equipped",
          "+33% Increased Attack Speed",
          "+<span class='varies varies--old'>280-330</span>% Enhanced Damage (varies)",
          "Ignore Target's Defense",
          "7% Life Stolen Per Hit",
          "-20% To Enemy Fire Resistance",
          "20% Deadly Strike",
          "Hit Blinds Target",
          "Freezes Target +3",
        ],
      },
    },
  },

  {
    id: 88,
    name: {
      ru: "Гордость",
      en: "Pride",
    },
    runes: [32, 29, 16, 28],
    types: [9, 13],
    excluded: "",
    patch: "1.10",
    level: 67,
    ladder: false,
    reworked: true,
    stats: {
      ru: [
        "Не теряет прочности",
        "При надевании дает ауру «Сосредоточенность» (<span class='varies'>16-20</span>)-го уровня",
        "+<span class='varies'>450-500</span>% к урону",
        "+(1*clvl)% к урону по демонам (зависит от уровня персонажа)",
        "+20% к вероятности нанести смертельный удар",
        "+ 6 к умению «Лучшая защита» (только для амазонок)",
        "+ 6 к умению «Выпад» (только для амазонок)",
        "При ударе ослепляет цель",
        "Замораживает цель +3",
        "+10 к живучести",
      ],
      en: [
        "Indestructible",
        "Level <span class='varies'>16-20</span> Concentration Aura When Equipped (varies)",
        "+<span class='varies'>450-500</span>% Enhanced Damage (varies)",
        "<span class='varies'>260-300</span>% Bonus To Attack Rating (varies)",
        "+4-396% Damage To Demons (Based on Character Level)",
        "+20% Deadly Strike",
        "+6 to Fend (Amazon only)",
        "+<span class='varies'>6-7</span> to Jab (Amazon only) (varies)",
        "Hit Blinds Target",
        "Freezes Target +3",
        "+10 To Vitality",
      ],
    },
    complete: false,
    old: {
      runes: [32, 29, 16, 28],
      types: [9, 13],
      stats: {
        ru: [
          "Вероятность 25% применить умение «Огненная стена» 17-го уровня при получении урона",
          "При надевании дает ауру «Сосредоточенность» (16-20)-го уровня",
          "+(260-300)% к рейтингу атаки",
          "+(1*clvl)% к урону по демонам (зависит от уровня персонажа)",
          "+50-280 урона от молнии",
          "+20% к вероятности нанести смертельный удар",
          "При ударе ослепляет цель",
          "Замораживает цель +3",
          "+10 к живучести",
          "Восполняет +8 здоровья",
          "+(1.875*clvl)% к золоту за убийство монстров (зависит от уровня персонажа)",
        ],
        en: [
          "25% Chance To Cast Level 17 Fire Wall When Struck",
          "Level <span class='varies varies--old'>16-20</span> Concentration Aura When Equipped (varies)",
          "<span class='varies varies--old'>260-300</span>% Bonus To Attack Rating (varies)",
          "+1-99% Damage To Demons (Based on Character Level)",
          "Adds 50-280 Lightning Damage",
          "20% Deadly Strike",
          "Hit Blinds Target",
          "Freezes Target +3",
          "+10 To Vitality",
          "Replenish Life +8",
          "1.875-185.625% Extra Gold From Monsters (Based on Character Level)",
        ],
      },
    },
  },

  /**
   * Mist (id 90) — сверено со скрином вики/UI (март 2026): порядок stats и EN-строки
   * приведены к типичному отображению в игре (IAS → аура → piercing → ED → резисты → проки → …).
   */
  {
    id: 90,
    name: {
      ru: "Туман",
      en: "Mist",
    },
    runes: [32, 13, 25, 10, 6],
    types: [6],
    excluded: "",
    patch: "2.4",
    level: 67,
    ladder: false,
    reworked: true,
    stats: {
      ru: [
        "+60% к скорости атаки",
        "При надевании дает ауру «Сосредоточенность» <span class='varies'>8-12</span>-го уровня",
        "+100% к пробивающей атаке",
        "+<span class='varies'>325-375</span>% к урону",
        "+40 к сопротивлению всем видам урона",
        "Вероятность 20% применить умение «Внутреннее зрение» 16-го уровня при атаке",
        "Вероятность 10% применить умение «Уход в тень» 12-го уровня при убийстве врага",
        "Замораживает цель +3",
        "+20% к рейтингу атаки",
        "+3-14 урона от льда",
        "+9 к максимальному урону",
      ],
      en: [
        "+60% Increased Attack Speed",
        "Level <span class='varies'>8-12</span> Concentration Aura When Equipped (varies)",
        "+100% Piercing Attack",
        "+<span class='varies'>325-375</span>% Enhanced Damage (varies)",
        "All Resistances +40%",
        "20% Chance To Cast Level 16 Inner Sight On Striking",
        "10% Chance To Cast Level 12 Fade When You Kill An Enemy",
        "Freezes Target +3",
        "20% Bonus to Attack Rating",
        "Adds 3-14 Cold Damage",
        "+9 To Maximum Damage",
      ],
    },
    complete: false,
    old: {
      runes: [32, 13, 25, 10, 6],
      types: [6],
      stats: {
        ru: [
          "При надевании дает ауру «Сосредоточенность» (8-12)-го уровня",
          "+3 ко всем умениям",
          "+20% к скорости атаки",
          "+100% к пронзающей атаке",
          "+(325-375)% к урону",
          "+9 к максимальному урону",
          "+20% к рейтингу атаки",
          "+3-14 урона от льда",
          "Замораживает цель +3",
          "+24 к живучести",
          "+40 к сопротивлению всем видам урона",
        ],
        en: [
          "Level <span class='varies varies--old'>8-12</span> Concentration Aura When Equipped (varies)",
          "+3 To All Skills",
          "20% Increased Attack Speed",
          "+100% Piercing Attack",
          "+<span class='varies varies--old'>325-375</span>% Enhanced Damage (varies)",
          "+9 To Maximum Damage",
          "20% Bonus to Attack Rating",
          "Adds 3-14 Cold Damage",
          "Freeze Target +3",
          "+24 Vitality",
          "All Resistances +40",
        ],
      },
    },
  },

  /**
   * Breath of the Dying — checked.
   */
  {
    id: 92,
    name: {
      ru: "Вздох умирающего",
      en: "Breath of the Dying",
    },
    runes: [26, 15, 1, 2, 33, 5],
    types: [12],
    excluded: "",
    classes: [],
    patch: "1.10",
    level: 69,
    ladder: false,
    reworked: true,
    bugged: {
      status: false,
      message: [],
    },
    stats: {
      ru: [
        "Вероятность 50% применить умение «Кольцо яда» 20-го уровня при убийстве",
        "+<span class='varies'>375-435</span>% к урону",
        "+60% к скорости атаки",
        "-25% к защите цели",
        "+30% к вероятности нанести сокрушающий удар",
        "+15% к вероятности нанести смертельный удар",
        "Похищает <span class='varies'>12-15</span>% здоровья за удар",
        "Запрещает монстрам лечиться",
        "+50 к рейтингу атаки",
        "+75% урона по нежити",
        "+50 к рейтингу атаки по нежити",
        "Похищает 7% маны за удар",
        "+1 к радиусу обзора",
        "Не теряет прочности",
        "Требования -20%",
      ],
      en: [
        "50% Chance To Cast Level 20 Poison Nova When You Kill An Enemy",
        "+<span class='varies'>375-435</span>% Enhanced Damage (varies)",
        "+60% Increased Attack Speed",
        "-25% Target Defense",
        "+30% Chance of Crushing Blow",
        "+15% Deadly Strike",
        "<span class='varies'>12-15</span>% Life Stolen Per Hit (varies)",
        "Prevent Monster Heal",
        "+50 To Attack Rating",
        "75% Damage To Undead",
        "+50 To Attack Rating Against Undead",
        "+7% Mana Stolen Per Hit",
        "+1 To Light Radius",
        "Indestructible",
        "Requirements -20%",
      ],
    },
    complete: false,
    old: {
      runes: [26, 15, 1, 2, 33, 5],
      types: [12],
      stats: {
        ru: [
          "Вероятность 50% применить умение «Кольцо яда» 20-го уровня при убийстве",
          "Не теряет прочности",
          "+60% к скорости атаки",
          "+(350-400)% к урону",
          "-25% к защите цели",
          "+50 к рейтингу атаки",
          "+200% урона по нежити",
          "+50 к рейтингу атаки по нежити",
          "Похищает 7% маны за удар",
          "Похищает (12-15)% здоровья за удар",
          "Запрещает монстрам лечиться",
          "+30 ко всем характеристикам",
          "+1 к радиусу обзора",
          "Требования -20%",
        ],
        en: [
          "50% Chance To Cast Level 20 Poison Nova When You Kill An Enemy",
          "Indestructible",
          "+60% Increased Attack Speed",
          "+<span class='varies varies--old'>350-400</span>% Enhanced Damage (varies)",
          "+200% Damage To Undead",
          "-25% Target Defense",
          "+50 To Attack Rating",
          "+50 To Attack Rating Against Undead",
          "7% Mana Stolen Per Hit",
          "<span class='varies varies--old'>12-15</span>% Life Stolen Per Hit (varies)",
          "Prevent Monster Heal",
          "+30 To All Attributes",
          "+1 To Light Radius",
          "Requirements -20%",
        ],
      },
    },
  },
];
