/**
 * Runewords из контента Rise of the West (RotW) / «новые» записи сервера (`patch: "rotw"`).
 * Склеиваются с базовым списком в store.
 * Записи с `marked: true` по умолчанию в `custom-runewords.ts` (здесь могут быть исключения).
 */
export const ROTW_RUNEWORDS = [
  {
    id: 98,
    name: {
      ru: "Истерия",
      en: "Hysteria",
    },
    runes: [13, 18, 2],
    types: [17],
    excluded: "",
    classes: [],
    patch: "rotw",
    level: 39,
    ladder: true,
    marked: false,
    stats: {
      ru: [
        "+65% к скорости ходьбы и бега",
        "+40% к скорости атаки",
        "+20% к ускоренному восстановлению от удара",
        "+6 к умению «Избежание»",
        "+10 к ловкости",
        "Выносливость снижается на 50% медленнее",
        "Все сопротивления +10",
      ],
      en: [
        "+65% Faster Run/Walk",
        "+40% Increased Attack Speed",
        "+20% Faster Hit Recovery",
        "+6 to Evade",
        "+10 to Dexterity",
        "50% Slower Stamina Drain",
        "All Resistances +10",
      ],
    },
    complete: false,
  },
  {
    id: 99,
    name: {
      ru: "Мания",
      en: "Mania",
    },
    runes: [13, 18, 2],
    types: [12],
    excluded: "",
    classes: [],
    patch: "rotw",
    level: 39,
    ladder: true,
    marked: false,
    stats: {
      ru: [
        "Вероятность 5% применить умение «Ускорение» 1-го уровня при ударе",
        "При надевании даёт ауру «Фанатизм» 1-го уровня",
        "+30% к скорости атаки",
        "+<span class='varies'>180-200</span>% к урону",
        "+75% урона по нежити",
        "+50 к рейтингу атаки против нежити",
        "+10 к ловкости",
      ],
      en: [
        "5% Chance to cast level 1 Burst of Speed on striking",
        "Level 1 Fanaticism Aura When Equipped",
        "+30% Increased Attack Speed",
        "+<span class='varies'>180-200</span>% Enhanced Damage (varies)",
        "+75% Damage to Undead",
        "+50 to Attack Rating against Undead",
        "+10 to Dexterity",
      ],
    },
    complete: false,
  },
  {
    id: 100,
    name: {
      ru: "Ковен",
      en: "Coven",
    },
    runes: [24, 8, 16],
    types: [18],
    excluded: "",
    classes: [],
    patch: "rotw",
    level: 51,
    ladder: true,
    marked: false,
    stats: {
      ru: [
        "Вероятность 5% применить умение «Sigil Lethargy» 10-го уровня при получении урона",
        "+1 ко всем умениям",
        "+20% к скорости колдовства",
        "+<span class='varies'>30-50</span>% к защите",
        "+<span class='varies'>1-5</span> к здоровью при убийстве",
        "+<span class='varies'>26-40</span>% к поиску магических предметов",
        "Сопротивление огню +30%",
        "+10 к живучести",
      ],
      en: [
        "5% Chance to cast level 10 Sigil Lethargy when struck",
        "+1 to All Skills",
        "+20% Faster Cast Rate",
        "+<span class='varies'>30-50</span>% Enhanced Defense (varies)",
        "+<span class='varies'>1-5</span> Life After Each Kill (varies)",
        "+<span class='varies'>26-40</span>% Better Chance of Getting Magic Items (varies)",
        "Fire Resist +30%",
        "+10 to Vitality",
      ],
    },
    complete: false,
  },
  {
    id: 101,
    name: {
      ru: "Ритуал",
      en: "Ritual",
    },
    runes: [11, 13, 27],
    types: [15],
    excluded: "",
    classes: [],
    patch: "rotw",
    level: 57,
    ladder: true,
    marked: false,
    stats: {
      ru: [
        "Вероятность 13% применить умение «Sigil Death» 1-го уровня при получении урона",
        "+40% к скорости атаки",
        "+<span class='varies'>250-320</span>% к урону",
        "+<span class='varies'>150-250</span>% к урону по демонам",
        "+<span class='varies'>200-260</span>% к рейтингу атаки",
        "+<span class='varies'>3-5</span> к здоровью при убийстве",
        "Убитые монстры не возрождаются",
        "Похищает 7% здоровья за удар",
      ],
      en: [
        "13% Chance to cast level 1 Sigil Death when struck",
        "+40% Increased Attack Speed",
        "+<span class='varies'>250-320</span>% Enhanced Damage (varies)",
        "+<span class='varies'>150-250</span>% Damage To Demons (varies)",
        "+<span class='varies'>200-260</span>% Bonus to Attack Rating (varies)",
        "+<span class='varies'>3-5</span> Life After Each Kill (varies)",
        "Slain Monsters Rest In Peace",
        "7% Life Stolen Per Hit",
      ],
    },
    complete: false,
  },
  {
    id: 102,
    name: {
      ru: "Власть",
      en: "Authority",
    },
    runes: [15, 13, 8],
    types: [17],
    excluded: "",
    classes: ["Warlock"],
    patch: "rotw",
    level: 29,
    ladder: true,
    marked: false,
    stats: {
      ru: [
        "Вероятность 2% применить умение «Psychic Ward» 10-го уровня при получении урона",
        "Вероятность 10% применить умение «Miasma Chain» 15-го уровня при ударе",
        "+2 к уровням умений Warlock",
        "+<span class='varies'>40-60</span>% к урону",
        "Требования -15%",
        "+20% к ускоренному восстановлению от удара",
        "Сопротивление огню +30%",
      ],
      en: [
        "2% Chance to cast level 10 Psychic Ward when struck",
        "10% Chance to cast level 15 Miasma Chain on striking",
        "+2 To Warlock Skill Levels",
        "+<span class='varies'>40-60</span>% Enhanced Damage (varies)",
        "Requirements -15%",
        "+20% Faster Hit Recovery",
        "Fire Resist +30%",
      ],
    },
    complete: false,
  },
  {
    id: 103,
    name: {
      ru: "Бдительность",
      en: "Vigilance",
    },
    runes: [14, 25],
    types: [24, 16, 21, 20],
    excluded: "",
    classes: [],
    patch: "rotw",
    level: 53,
    ladder: true,
    marked: false,
    stats: {
      ru: [
        "Вероятность 5% применить умение «Ring of Fire» 10-го уровня при получении урона",
        "+10% к скорости ходьбы и бега",
        "+30% к скорости блока",
        "+<span class='varies'>20-40</span> к здоровью",
        "+<span class='varies'>20-40</span> к мане",
        "+<span class='varies'>25-35</span> к сопротивлению всем видам урона",
        "+<span class='varies'>75-100</span>% к защите",
        "Восполнение жизни +7",
        "+5% к максимальному сопротивлению яду",
      ],
      en: [
        "5% Chance to cast level 10 Ring of Fire when struck",
        "+10% Faster Run/Walk",
        "+30% Faster Block Rate",
        "+<span class='varies'>20-40</span> To Life (varies)",
        "+<span class='varies'>20-40</span> To Mana (varies)",
        "All Resistances +<span class='varies'>25-35</span> (varies)",
        "+<span class='varies'>75-100</span>% Enhanced Defense (varies)",
        "Replenish Life +7",
        "+5% to Maximum Poison Resist",
      ],
    },
    complete: false,
  },
  {
    id: 104,
    name: {
      ru: "Пустота",
      en: "Void",
    },
    runes: [10, 33, 24],
    types: [15],
    excluded: "",
    classes: [],
    patch: "rotw",
    level: 69,
    ladder: true,
    marked: false,
    stats: {
      ru: [
        "+2 ко всем умениям",
        "+40% к скорости колдовства",
        "+<span class='varies'>10-15</span>% к урону магических умений",
        "+<span class='varies'>1-3</span> к умению «Abyss»",
        "+<span class='varies'>8-12</span> ко всем характеристикам",
        "«Одряхление» 4-го уровня (35/35 зарядов)",
        "+3-14 урона от льда",
        "Не теряет прочности",
        "+30% к поиску магических предметов",
      ],
      en: [
        "+2 To All Skills",
        "+40% Faster Cast Rate",
        "+<span class='varies'>10-15</span>% to Magic Skill Damage (varies)",
        "+<span class='varies'>1-3</span> To Abyss (varies)",
        "+<span class='varies'>8-12</span> To All Attributes (varies)",
        "Level 4 Decrepify (35/35 Charges)",
        "Adds 3-14 Cold Damage",
        "Indestructible",
        "30% Better Chance of Getting Magic Items",
      ],
    },
    complete: false,
  },
];
