export const RUNEWORDS = [
  {
    id: 1,
    name: "Nadir",
    runes: [4, 3],
    types: ["Helms"],
    level: 13,
    ladder: false,
    stats: [
      "+50% Enhanced Defense",
      "+10 Defense",
      "+30 Defense vs. Missile",
      "Level 13 Cloak of Shadows (9 Charges)",
      "+2 To Mana After Each Kill",
      "+5 To Strength",
      "-33% Extra Gold From Monsters",
      "-3 To Light Radius",
    ],
  },
  {
    id: 2,
    name: "Steel",
    runes: [3, 1],
    types: ["Swords", "Axes", "Maces"],
    level: 13,
    ladder: false,
    stats: [
      "20% Enhanced Damage",
      "+3 To Minimum Damage",
      "+3 To Maximum Damage",
      "+50 To Attack Rating",
      "50% Chance Of Open Wounds",
      "25% Increased Attack Speed",
      "+2 To Mana After Each Kill",
      "+1 To Light Radius",
    ],
  },
  {
    id: 3,
    name: "Malice",
    runes: [6, 1, 5],
    types: ["Melee Weapons"],
    level: 15,
    ladder: false,
    stats: [
      "+33% Enhanced Damage",
      "+9 To Maximum Damage",
      "100% Chance Of Open Wounds",
      "-25% Target Defense",
      "-100 To Monster Defense Per Hit",
      "Prevent Monster Heal",
      "+50 To Attack Rating",
      "Drain Life -5",
    ],
  },
  {
    id: 4,
    name: "Stealth",
    runes: [7, 5],
    types: ["Body Armors"],
    level: 17,
    ladder: false,
    stats: [
      "Magic Damage Reduced By 3",
      "+6 To Dexterity",
      "+15 To Maximum Stamina",
      "Poison Resist +30%",
      "Regenerate Mana 15%",
      "25% Faster Cast Rate",
      "25% Faster Hit Recovery",
    ],
  },
  {
    id: 5,
    name: "Leaf",
    runes: [3, 8],
    types: ["Staves"],
    excluded: "Not Orbs/Wands",
    level: 19,
    ladder: false,
    stats: [
      "Adds 5-30 Fire Damage",
      "+3 To Fire Skills",
      "+3 To Fire Bolt (Sorceress Only)",
      "+3 To Inferno (Sorceress Only)",
      "+3 To Warmth (Sorceress Only)",
      "+2 To Mana After Each Kill",
      "+ (2 Per Character Level) +2-198 To Defense (Based On Character Level)",
      "Cold Resist +33%",
    ],
  },
  {
    id: 6,
    name: "Ancient's Pledge",
    runes: [8, 9, 7],
    types: ["Shields"],
    excluded: "",
    level: 21,
    ladder: false,
    stats: [
      "+50% Enhanced Defense",
      "Cold Resist +43%",
      "Fire Resist +48%",
      "Lightning Resist +48%",
      "Poison Resist +48%",
      "10% Damage Goes To Mana",
    ],
  },
  {
    id: 7,
    name: "Holy Thunder",
    runes: [5, 8, 9, 7],
    types: ["Scepters"],
    excluded: "",
    level: 21,
    ladder: false,
    stats: [
      "+60% Enhanced Damage",
      "-25% Target Defense",
      "Adds 5-30 Fire Damage",
      "Adds 21-110 Lightning Damage",
      "+75 Poison Damage Over 5 Seconds",
      "+10 To Maximum Damage",
      "Lightning Resistance +60%",
      "+5 To Maximum Lightning Resistance",
      "+3 To Holy Shock (Paladin Only)",
      "Level 7 Chain Lightning (60 Charges)",
    ],
  },
  {
    id: 8,
    name: "Zephyr",
    runes: [9, 5],
    types: ["Missile Weapons"],
    excluded: "",
    level: 21,
    ladder: false,
    stats: [
      "+33% Enhanced Damage",
      "+66 To Attack Rating",
      "Adds 1-50 Lightning Damage",
      "-25% Target Defense",
      "+25 Defense",
      "25% Faster Run/Walk",
      "25% Increased Attack Speed",
      "7% Chance To Cast Level 1 Twister When Struck",
    ],
  },
  {
    id: 9,
    name: "Pattern",
    runes: [7, 9, 10],
    types: ["Katars"],
    excluded: "",
    classes: ["Assassin"],
    patch: "2.4",
    level: 23,
    ladder: false,
    reworked: true,
    stats: [
      "+30% Faster Block Rate",
      "+40-80% Enhanced Damage (varies)",
      "+3 to Weapon block (Assassin only)",
      "+75 Poison Damage Over 5 Seconds",
      "+6 to Strength",
      "+6 to Dexterity",
      "All Resistances +15",
      "Adds 17-62 Fire Damage",
      "Adds 1-50 Lightning Damage",
      "Adds 3-14 Cold Damage"
    ],
  },
  {
    id: 10,
    name: "King's Grace",
    runes: [11, 8, 10],
    types: ["Swords", "Scepters"],
    excluded: "",
    classes: [],
    patch: "",
    level: 25,
    ladder: false,
    stats: [
      "+100% Enhanced Damage",
      "+100% Damage To Demons",
      "+50% Damage To Undead",
      "Adds 5-30 Fire Damage",
      "Adds 3-14 Cold Damage - 3 Second Duration",
      "+150 To Attack Rating",
      "+100 To Attack Rating Against Demons",
      "+100 To Attack Rating Against Undead",
      "7% Life Stolen Per Hit",
    ],
  },
  {
    id: 11,
    name: "Strength",
    runes: [11, 3],
    types: ["Melee Weapons"],
    excluded: "",
    classes: [],
    patch: "",
    level: 25,
    ladder: false,
    stats: [
      "35% Enhanced Damage",
      "25% Chance Of Crushing Blow",
      "7% Life Stolen Per Hit",
      "+2 To Mana After Each Kill",
      "+ 20 To Strength",
      "+10 To Vitality",
    ],
  },
  {
    id: 12,
    name: "Edge",
    runes: [3, 7, 11],
    types: ["Melee Weapons"],
    excluded: "",
    classes: [],
    patch: "1.10",
    level: 25,
    ladder: false,
    stats: [
      "Level 15 Thorns Aura When Equipped",
      "+35% Increased Attack Speed",
      "+320-380% Damage To Demons (varies)",
      "+280% Damage To Undead",
      "+75 Poison Damage Over 5 Seconds",
      "7% Life Stolen Per Hit",
      "Prevent Monster Heal",
      "+5-10 To All Attributes (varies)",
      "+2 To Mana After Each Kill",
      "Reduces All Vendor Prices 15%!!!",
    ],
  },
  {
    id: 13,
    name: "Spirit",
    runes: [7, 10, 9, 11],
    types: ["Swords", "Shields"],
    excluded: "",
    classes: [],
    patch: "1.10",
    level: 25,
    ladder: false,
    stats: [
      "+2 To All Skills",
      "+25-35% Faster Cast Rate (varies)",
      "+55% Faster Hit Recovery",
      "Adds 1-50 Lightning Damage",
      "Adds 3-14 Cold Damage 3 Second Duration (Normal)",
      "+75 Poison Damage Over 5 Seconds",
      "7% Life Stolen Per Hit",
      "+250 Defense Vs. Missile",
      "+22 To Vitality",
      "+89-112 To Mana (varies)",
      "+3-8 Magic Absorb (varies)",
    ],
  },
  {
    id: 14,
    name: "Myth",
    runes: [15, 14, 21],
    types: ["Body Armors"],
    excluded: "",
    classes: ["Barbarian"],
    patch: "1.11",
    level: 45,
    ladder: false,
    reworked: true,
    bugged: {
      status: true,
      message: [
        '100% Enhanced Damage'
      ]
    },
    stats: [
      "Adds +40 damage",
      "+3 to Masteries (barbarian only)",
      "+2 To Barbarian Skill Levels",
      "+130% Enhanced Defence",
      "+20% Deadly Strike",
      "Requirements -15%",
      "Replenish Life 7"
    ],
  },
  {
    id: 15,
    name: "Honor",
    runes: [11, 1, 6, 3, 12],
    types: ["Melee Weapons"],
    excluded: "",
    classes: [],
    patch: "",
    level: 27,
    ladder: false,
    stats: [
      "+160% Enhanced Damage",
      "+9 To Minimum Damage",
      "+9 To Maximum Damage",
      "25% Deadly Strike",
      "+250 To Attack Rating",
      "+1 to All Skills",
      "7% Life Stolen Per Hit",
      "Replenish Life +10",
      "+10 To Strength",
      "+1 To Light Radius",
      "+2 To Mana After Each Kill",
    ],
  },
  {
    id: 16,
    name: "Lore",
    runes: [9, 12],
    types: ["Helms"],
    excluded: "",
    classes: [],
    patch: "",
    level: 27,
    ladder: false,
    stats: [
      "+1 To All Skill Levels",
      "+10 To Energy",
      "+2 To Mana After Each Kill",
      "Lightning Resist +30%",
      "Damage Reduced By 7",
      "+2 To Light Radius",
    ],
  },
  {
    id: 17,
    name: "Radiance",
    runes: [4, 12, 6],
    types: ["Helms"],
    excluded: "",
    classes: [],
    patch: "",
    level: 27,
    ladder: false,
    stats: [
      "+75% Enhanced Defense",
      "+30 Defense Vs. Missile",
      "+10 To Energy",
      "+10 To Vitality",
      "15% Damage Goes To Mana",
      "Magic Damage Reduced By 3",
      "+33 To Mana",
      "Damage Reduced By 7",
      "+5 To Light Radius",
    ],
  },
  {
    id: 18,
    name: "Insight",
    runes: [8, 3, 7, 12],
    types: ["Missile Weapons", "Polearms", "Staves"],
    excluded: "",
    classes: [],
    patch: "1.10",
    level: 27,
    ladder: false,
    stats: [
      "Level 12-17 Meditation Aura When Equipped (varies)",
      "+35% Faster Cast Rate",
      "+200-260% Enhanced Damage (varies)",
      "+9 To Minimum Damage",
      "180-250% Bonus to Attack Rating (varies)",
      "Adds 5-30 Fire Damage",
      "+75 Poison Damage Over 5 Seconds",
      "+1-6 To Critical Strike (varies)",
      "+5 To All Attributes",
      "+2 To Mana After Each Kill",
      "23% Better Chance of Getting Magic Items",
    ],
  },
  {
    id: 19,
    name: "Rhyme",
    runes: [13, 5],
    types: ["Shields"],
    excluded: "",
    classes: [],
    patch: "",
    level: 29,
    ladder: false,
    stats: [
      "20% Increased Chance of Blocking",
      "40% Faster Block Rate",
      "All Resistances +25",
      "Regenerate Mana 15%",
      "Cannot Be Frozen",
      "50% Extra Gold From Monsters",
      "25% Better Chance Of Getting Magic Items",
    ],
  },
  {
    id: 20,
    name: "Peace",
    runes: [22, 10, 11],
    types: ["Body Armors"],
    excluded: "",
    classes: ["Amazon"],
    patch: "",
    level: 47,
    ladder: false,
    reworked: true,
    stats: [
      "2% Chance To Cast level 15 Valkyrie On Striking",
      "+2 To Amazon Skill Levels",
      "+2 To Critical Strike",
      "+30% increased attack speed",
      "Cold Resist +30%",
      "All resist +15%",
      "Attacker Takes Damage of 14",
    ],
  },
  {
    id: 21,
    name: "Black",
    runes: [10, 16, 4],
    types: ["Clubs", "Hammers", "Maces"],
    excluded: "",
    classes: [],
    patch: "",
    level: 35,
    ladder: false,
    stats: [
      "+120% Enhanced Damage",
      "40% Chance Of Crushing Blow",
      "+200 To Attack Rating",
      "Adds 3-14 Cold Damage - Cold Duration 3 Seconds",
      "+10 To Vitality",
      "15% Increased Attack Speed",
      "Knockback",
      "Magic Damage Reduced By 2",
      "Level 4 Corpse Explosion (12 Charges)",
    ],
  },
  {
    id: 22,
    name: "White",
    runes: [14, 16],
    types: ["Wands"],
    excluded: "",
    classes: ["Necromancer"],
    patch: "",
    level: 35,
    ladder: false,
    stats: [
      "Hit Causes Monster To Flee 25%",
      "+10 To Vitality",
      "+3 To Poison And Bone Skills (Necromancer Only)",
      "+3 To Bone Armor (Necromancer Only)",
      "+2 To Bone Spear (Necromancer Only)",
      "+4 To Skeleton Mastery (Necromancer Only)",
      "Magic Damage Reduced By 4",
      "20% Faster Cast Rate",
      "+13 To Mana",
    ],
  },
  {
    id: 23,
    name: "Bulwark",
    runes: [13, 16, 12],
    types: ["Helms"],
    excluded: "",
    classes: [],
    patch: "2.6",
    level: 35,
    ladder: true,
    stats: [
      "+20% Faster Hit Recovery",
      "+4-6% Life stolen per hit",
      "+75-100% Enhanced Defense",
      "+10 to Vitality",
      "Increase Maximum Life 5%",
      "Replenish Life +30",
      "Damage Reduced by 7",
      "Physical Damage Received Reduced by 10-15%",
    ],
  },
  {
    id: 24,
    name: "Cure",
    runes: [13, 16, 7],
    types: ["Helms"],
    excluded: "",
    classes: [],
    patch: "",
    level: 35,
    ladder: true,
    stats: [
      "Level 1 Cleansing Aura when Equipped",
      "+20% Faster Hit Recovery",
      "+75-100% Enhanced Defense",
      "+10 to Vitality",
      "Increase Maximum Life 5%",
      "Poison Resist +40-60%",
      "Poison Length Reduced by 50%",
    ],
  },
  {
    id: 25,
    name: "Ground",
    runes: [13, 16, 24],
    types: ["Helms"],
    excluded: "",
    classes: [],
    patch: "",
    level: 51,
    ladder: true,
    reworked: true,
    stats: [
      "+75-100% Enhanced Defense",
      "Increase Maximum Mana 30%",
      "Level 1 Cleansing aura when equipped",
      "Lightning Resist +30%",
      "Lightning Absorb +10-15%",
      "+25% Better Chance of Getting Magic Items",
      "+20% Faster Hit Recovery",
      "+10 to Vitality"
    ],
  },
  {
    id: 26,
    name: "Hearth",
    runes: [13, 16, 25],
    types: ["Helms"],
    excluded: "",
    classes: [],
    patch: "",
    level: 53,
    ladder: true,
    reworked: true,
    stats: [
      "+20% Faster Hit Recovery",
      "+75-100% Enhanced Defense",
      "Level 16 Blessed Aim aura when equipped",
      "+10 to Vitality",
      "Cold Resist +30%",
      "Cold Absorb +10-15%",
      "Cannot be Frozen",
      "5% to Maximum Poison Resist",
    ],
  },
  {
    id: 27,
    name: "Temper",
    runes: [13, 16, 21],
    types: ["Helms"],
    excluded: "",
    classes: [],
    patch: "",
    level: 45,
    ladder: true,
    reworked: true,
    stats: [
      "130% Enhanced Defense",
      "8% life stolen per hit",
      "Fire Resist +30%",
      "Fire Absorb +10-15%",
      "+350% extra gold from monsters",
      "+20% Faster Cast Rate",
      "+10 to Vitality",
      "+20% Faster Hit Recovery",
    ],
  },
  {
    id: 28,
    name: "Memory",
    runes: [17, 16, 12, 5],
    types: ["Staves"],
    excluded: "Not Orbs/Wands",
    classes: [],
    patch: "",
    level: 37,
    ladder: false,
    stats: [
      "+3 to Sorceress Skill Levels",
      "33% Faster Cast Rate",
      "Increase Maximum Mana 20%",
      "+3 Energy Shield (Sorceress Only)",
      "+2 Static Field (Sorceress Only)",
      "+10 To Energy",
      "+10 To Vitality",
      "+9 To Minimum Damage",
      "-25% Target Defense",
      "Magic Damage Reduced By 7",
      "+50% Enhanced Defense",
    ],
  },
  {
    id: 29,
    name: "Smoke",
    runes: [4, 17],
    types: ["Body Armors"],
    excluded: "",
    classes: [],
    patch: "",
    level: 37,
    ladder: false,
    stats: [
      "+75% Enhanced Defense",
      "+280 Defense Vs. Missile",
      "All Resistances +50",
      "20% Faster Hit Recovery",
      "Level 6 Weaken (18 Charges)",
      "+10 To Energy",
      "-1 To Light Radius",
    ],
  },
  {
    id: 30,
    name: "Splendor",
    runes: [5, 17],
    types: ["Shields"],
    excluded: "",
    classes: [],
    patch: "1.10",
    level: 37,
    ladder: false,
    stats: [
      "+1 To All Skills",
      "+10% Faster Cast Rate",
      "+20% Faster Block Rate",
      "+60-100% Enhanced Defense (varies)",
      "+10 To Energy",
      "Regenerate Mana 15%",
      "50% Extra Gold From Monsters",
      "20% Better Chance of Getting Magic Items",
      "+3 To Light Radius",
    ],
  },
  {
    id: 31,
    name: "Melody",
    runes: [13, 18, 4],
    types: ["Missile Weapons"],
    excluded: "",
    classes: [],
    patch: "1.10",
    level: 39,
    ladder: false,
    stats: [
      "+50% Enhanced Damage",
      "+300% Damage To Undead",
      "+3 To Bow and Crossbow Skills (Amazon Only)",
      "+3 To Critical Strike (Amazon Only)",
      "+3 To Dodge (Amazon Only)",
      "+3 To Slow Missiles (Amazon Only)",
      "20% Increased Attack Speed",
      "+10 To Dexterity",
      "Knockback",
    ],
  },

  {
    id: 32,
    name: "Harmony",
    runes: [3, 6, 12, 18],
    types: ["Missile Weapons"],
    excluded: "",
    classes: [],
    patch: "1.10",
    level: 39,
    ladder: false,
    stats: [
      "Level 10 Vigor Aura When Equipped",
      "+200-275% Enhanced Damage (varies)",
      "+9 To Minimum Damage",
      "+9 To Maximum Damage",
      "Adds 55-160 Lightning Damage",
      "Adds 55-160 Fire Damage",
      "Adds 55-160 Cold Damage",
      "+2-6 To Valkyrie (varies)",
      "+10 To Dexterity",
      "Regenerate Mana 20%",
      "+2 To Mana After Each Kill",
      "+2 To Light Radius",
      "Level 20 Revive (25 Charges)",
    ],
  },
  {
    id: 33,
    name: "Hustle",
    runes: [13, 18, 2],
    types: ["Weapons", "Body Armors"],
    excluded: "",
    classes: [],
    patch: "2.6",
    level: 39,
    ladder: true,
    stats: [
      "Weapons",
      "5% Chance to cast level 1 Burst of Speed on striking",
      "Level 1 Fanaticism Aura",
      "+30% Increased Attack Speed",
      "+180-200% Enhanced Damage",
      "+75% Damage to Undead",
      "+50 to Attack Rating against Undead",
      "+10 to Dexterity",

      "Body Armors",
      "+65% Faster Run/Walk",
      "+40% Increased Attack Speed",
      "+20% Faster Hit Recovery",
      "+6 to Evade",
      "+10 to Dexterity",
      "50% Slower Stamina Drain",
      "+All Resistances +10",
    ],
  },
  {
    id: 34,
    name: "Lionheart",
    runes: [15, 17, 19],
    types: ["Body Armors"],
    excluded: "",
    classes: [],
    patch: "2.6",
    level: 41,
    ladder: false,
    stats: [
      "+20% Enhanced Damage",
      "Requirements -15%",
      "+25 To Strength",
      "+10 To Energy",
      "+20 To Vitality",
      "+15 To Dexterity",
      "+50 To Life",
      "All Resistances +30",
    ],
  },
  {
    id: 35,
    name: "Obedience",
    runes: [15, 18, 10, 5, 19],
    types: ["Polearms", "Spears"],
    excluded: "",
    classes: [],
    patch: "1.10",
    level: 41,
    ladder: false,
    stats: [
      "30% Chance To Cast Level 21 Enchant When You Kill An Enemy",
      "40% Faster Hit Recovery",
      "+370% Enhanced Damage",
      "-25% Target Defense",
      "Adds 3-14 Cold Damage 3 Second Duration (Normal)",
      "-25% To Enemy Fire Resistance",
      "40% Chance of Crushing Blow",
      "+200-300 Defense (varies)",
      "+10 To Strength",
      "+10 To Dexterity",
      "All Resistances +20-30 (varies)",
      "Requirements -20%",
    ],
  },
  {
    id: 36,
    name: "Unbending Will",
    runes: [19, 16, 6, 15],
    types: ["Swords"],
    excluded: "",
    classes: [],
    patch: "2.4",
    level: 41,
    ladder: false,
    reworked: true,
    stats: [
      '18% Chance to cast Level 18 Taunt on striking',
      '+3 To Combat Skills (Barbarian Only)',
      '+20-30% Increased Attack Speed (varies)',
      '+300-350% Enhanced Damage (varies)',
      '+9 To Maximum Damage',
      // '+50 To Attack Rating', El rune
      // '+75% Damage to Undead', Eld rune
      // '+50 Attack Rating Against Undead', Eld rune
      '8-10% Life Stolen Per Hit (varies)',
      'Prevent Monster Heal',
      '+10 To Strength',
      '+10 To Vitality',
      'Damage Reduced By 8',
      // '+1 Light Radius', El rune
      'Requirements -20%',
    ],
  },
  {
    id: 37,
    name: "Wealth",
    runes: [20, 18, 3],
    types: ["Body Armors"],
    excluded: "",
    classes: [],
    patch: "",
    level: 43,
    ladder: false,
    stats: [
      "300% Extra Gold From Monsters",
      "100% Better Chance Of Getting Magic Items",
      "+2 To Mana After Each Kill",
      "+10 To Dexterity",
    ],
  },
  {
    id: 38,
    name: "Passion",
    runes: [14, 9, 2, 20],
    types: ["Weapons"],
    excluded: "",
    classes: [],
    patch: "",
    level: 43,
    ladder: false,
    reworked: true,
    bugged: {
      status: true,
      message: [
        'Adds +210 Maximum Damage',
        'Hit Causes Monster To Flee 44%'
      ]
    },
    stats: [
      '+25% Increased Attack Speed',
      'Adds +200 Maximum Damage',
      '50-80% Bonus To Attack Rating (varies)',
      '+1-6 To Berserk',
      '+1-6 To Zeal',
      'Hit Causes Monster To Flee 25%',
      'Level 3 Heart of Wolverine (12 Charges)',
      '+75% Damage To Undead',
      '+50 To Attack Rating Against Undead',
      'Adds 1-50 Lightning Damage',
      '75% Extra Gold From Monsters'
    ],
  },
  {
    id: 39,
    name: "Lawbringer",
    runes: [11, 20, 18],
    types: ["Swords", "Hammers", "Scepters"],
    excluded: "",
    classes: [],
    patch: "",
    level: 43,
    ladder: false,
    reworked: true,
    stats: [
      '20% Chance To Cast Level 15 Decrepify On Striking',
      'Level 16-18 Sanctuary Aura When Equipped (varies)',
      '+1 to Zeal',
      'Adds 1-990 Lightning Damage',
      '+25% increased attack speed',
      'Slain Monsters Rest In Peace',
      '15% Mana Stolen Per Hit',
      '+10 To Dexterity',
      '75% Extra Gold From Monsters',
      '7% Life Stolen Per Hit'
    ],
  },
  {
    id: 40,
    name: "Voice of Reason",
    runes: [20, 18, 1, 2],
    types: ["Swords", "Maces", "Scepters"],
    excluded: "",
    classes: [],
    patch: "1.10",
    level: 43,
    ladder: false,
    reworked: true,
    stats: [
      '150-200% Enhanced Damage',
      '+30% Faster Cast Rate',
      '+220-350% Damage To Demons',
      '+355-375% Damage To Undead (varies)',
      'Adds 100-220 Cold Damage',
      '-24% To Enemy Cold Resistance',
      'Cannot Be Frozen',
      '+10 To Dexterity',
      '75% Extra Gold From Monsters',
      '+1 To Light Radius',
      '+50 To Attack Rating',
      '+50 To Attack Rating Against Undead'
    ],
  },
  {
    id: 41,
    name: "Treachery",
    runes: [13, 10, 20],
    types: ["Body Armors"],
    excluded: "",
    classes: ["Assassin"],
    patch: "1.11",
    level: 43,
    ladder: false,
    stats: [
      "5% Chance To Cast Level 15 Fade When Struck",
      "25% Chance To Cast level 15 Venom On Striking",
      "+2 To Assassin Skills",
      "+45% Increased Attack Speed",
      "+20% Faster Hit Recovery",
      "Cold Resist +30%",
      "50% Extra Gold From Monsters",
    ],
  },
  {
    id: 42,
    name: "Enlightenment",
    runes: [21, 8, 12],
    types: ["Body Armors"],
    excluded: "",
    classes: ["Sorceress"],
    patch: "1.11",
    level: 45,
    ladder: false,
    reworked: true,
    stats: [
      '30% Chance To Cast Level 15 Blaze When Struck',
      '+2 To Sorceress Skill Levels',
      '+6 to Frost Nova (sorceress only)',
      '+6 to Fire Wall (sorceress only)',
      '+10% Faster Cast Rate',
      '+30% Enhanced Defense',
      'Fire Resist +30%',
      'Damage Reduced By 7'
    ],
  },
  {
    id: 43,
    name: "Wisdom",
    runes: [21, 6, 2],
    types: ["Helms"],
    excluded: "",
    classes: [],
    patch: "2.4",
    level: 45,
    ladder: false,
    reworked: true,
    stats: [
      '+33% Piercing Attack',
      '90% Enhanced Damage',
      '4-8% Mana Stolen Per Hit (varies)',
      '+10 Energy',
      'Cannot Be Frozen',
      '+5 Mana After Each Kill',
      '15% Slower Stamina Drain',
      '15% Damage Taken Goes to Mana',
      '+30% Enhanced Defense',
    ],
  },
  {
    id: 44,
    name: "Crescent Moon",
    runes: [13, 22, 3],
    types: ["Axes", "Swords", "Polearms"],
    excluded: "",
    classes: [],
    patch: "2.4",
    level: 47,
    ladder: false,
    stats: [
      "10% Chance To Cast Level 17 Chain Lightning On Striking",
      "7% Chance To Cast Level 13 Static Field On Striking",
      "+20% Increased Attack Speed",
      "+180-220% Enhanced Damage (varies)",
      "Ignore Target's Defense",
      "-35% To Enemy Lightning Resistance",
      "25% Chance of Open Wounds",
      "+9-11 Magic Absorb (varies)",
      "+2 To Mana After Each Kill",
      "Level 18 Summon Spirit Wolf (30 Charges)",
    ],
  },
  {
    id: 45,
    name: "Duress",
    runes: [13, 22, 10],
    types: ["Body Armors"],
    excluded: "",
    classes: [],
    patch: "1.10",
    level: 47,
    ladder: false,
    stats: [
      "+40% Faster Hit Recovery",
      "+10-20% Enhanced Damage (varies)",
      "Adds 37-133 Cold Damage 2 sec. Duration (Normal)",
      "15% Chance of Crushing Blow",
      "33% Chance of Open Wounds",
      "+150-200% Enhanced Defense (varies)",
      "-20% Slower Stamina Drain",
      "Cold Resist +45%",
      "Lightning Resist +15%",
      "Fire Resist +15%",
      "Poison Resist +15%",
    ],
  },
  {
    id: 46,
    name: "Gloom",
    runes: [19, 22, 21],
    types: ["Body Armors"],
    excluded: "",
    classes: [],
    patch: "1.10",
    level: 47,
    ladder: false,
    reworked: true,
    bugged: {
      status: true,
      message: [
        "30% Chance To Cast Level 8 Cloak of Shadows When Struck (doesn't work)",
        "-25% Chance Of Getting Magic Items (doesn't work)",
      ]
    },
    stats: [
      '30% Chance To Cast Level 8 Cloak of Shadows When Struck',
      '30% Faster Hit Recovery',
      '+200-260% Enhanced Defense (varies)',
      '+20% Faster Cast Rate',
      '+1 To All Skills',
      '-25% Chance Of Getting Magic Items',
      '+10 To Strength',
      'All resistances 15%',
    ],
  },
  {
    id: 47,
    name: "Stone",
    runes: [13, 22, 21, 17],
    types: ["Body Armors"],
    excluded: "",
    classes: [],
    patch: "1.10",
    level: 47,
    ladder: false,
    reworked: true,
    stats: [
      '+60% Faster Hit Recovery',
      '+250-290% Enhanced Defense (varies)',
      '+20% increased chance of blocking',
      '+16 To Strength',
      '+16 To Vitality',
      'All Resistances +40%',
      'Level 6 Defiance aura when equipped',
      '+10 To Energy',
    ],
  },
  {
    id: 48,
    name: "Bone",
    runes: [12, 22, 22],
    types: ["Body Armors"],
    excluded: "",
    classes: ["Necromancer"],
    patch: "1.11",
    level: 47,
    ladder: false,
    reworked: true,
    bugged: {
      status: true,
      message: [
        '+5 to Raise Skeleton (necromancer only)',
        '+40% Faster Cast Rate',
      ]
    },
    stats: [
      '+6 to Bone Armor (necromancer only)',
      '+6 to Raise Skeleton (necromancer only)',
      '+2 To Necromancer Skill Levels',
      '+20% Faster Cast Rate',
      'All Resistances +30',
      'Damage Reduced By 7'
    ],
  },
  {
    id: 49,
    name: "Venom",
    runes: [7, 14, 23],
    types: ["Weapons"],
    excluded: "",
    classes: [],
    patch: "1.11",
    level: 49,
    ladder: false,
    stats: [
      "Hit Causes Monster To Flee 25%",
      "Prevent Monster Heal",
      "Ignore Target's Defense",
      "7% Mana Stolen Per Hit",
      "Level 15 Poison Explosion (27 Charges)",
      "Level 13 Poison Nova (11 Charges)",
      "+273 Poison Damage Over 6 seconds",
    ],
  },
  {
    id: 50,
    name: "Prudence",
    runes: [23, 3],
    types: ["Body Armors"],
    excluded: "",
    classes: [],
    patch: "1.10",
    level: 49,
    ladder: false,
    stats: [
      '10% Chance to cast level 16 Cyclone Armor when struck',
      '10% Chance to cast level 20 Bone Armor when struck',
      '200-235% Enhanced Defense (varies)',
      'All Resistances +25-35 (varies)',
      '+4-6 to Shout',
      'Damage reduced by 12%',
      'Magic Damage Reduced by 7',
      '+2 To Mana After Each Kill',
      'Repairs Durability 1 In 4 Seconds',
    ],
  },
  {
    id: 51,
    name: "Sanctuary",
    runes: [18, 18, 23],
    types: ["Shields"],
    excluded: "",
    classes: [],
    patch: "1.10",
    level: 49,
    ladder: false,
    reworked: true,
    stats: [
      '+20% Faster Hit Recovery',
      '+20% Faster Block Rate',
      '40% Increased Chance of Blocking',
      '+130-160% Enhanced Defense (varies)',
      '+2 To All Skills',
      'Level 1-4 Salvation aura when equipped',
      '10% Chance to cast level 12 Slow Missiles when struck',
      '+20 To Dexterity',
      'Magic Damage Reduced By 7'
    ],
  },
  {
    id: 52,
    name: "Oath",
    runes: [13, 21, 23, 17],
    types: ["Swords", "Axes", "Maces"],
    excluded: "",
    classes: [],
    patch: "1.10",
    level: 49,
    ladder: false,
    reworked: true,
    stats: [
      'Indestructible',
      '30% Chance To Cast Level 20 Bone Spirit On Striking',
      '40-50% Increased Attack Speed',
      '+300-340% Enhanced Damage (varies)',
      '+10-15 Magic Absorb (varies)',
      'Level 16 Heart Of Wolverine (20 Charges)',
      'Level 17 Iron Golem (14 Charges)',
      '+10 To Energy',
      'Prevent Monster Heal',
      '+75% Damage To Demons',
      '+100 To Attack Rating Against Demons',
    ],
  },
  {
    id: 53,
    name: "Rain",
    runes: [9, 23, 6],
    types: ["Body Armors"],
    excluded: "",
    classes: ["Druid"],
    patch: "1.11",
    level: 49,
    ladder: false,
    reworked: true,
    stats: [
      "5% Chance To Cast Level 15 Cyclone Armor When Struck",
      "5% Chance To Cast Level 26 Hurricane When Struck",
      "+2 To Druid Skills",
      "+2 to Summoning skils (druid only)",
      "300% extra gold from monsters",
      "Level 1 Amplify Damage (12 Charges)",
      "Lightning Resist +30%",
      "Magic Damage Reduced By 7",
      "15% Damage Taken Goes to Mana"
    ],
  },
  {
    id: 54,
    name: "Delirium",
    runes: [20, 24, 16],
    types: ["Helms"],
    excluded: "",
    classes: [],
    patch: "1.11",
    level: 51,
    ladder: false,
    reworked: true,
    stats: [
      '1% Chance To Cast Level 50 Delirium* (morph) When Struck',
      '6% Chance To Cast Level 14 Mind Blast When Struck',
      '11% Chance To Cast Level 18 Confuse When Struck',
      '+2 To All Skills',
      '+261 Defense',
      '+75% Better Chance of Getting Magic Items',
      'Level 1 Teleport (60 Charges)',
      '50% Extra Gold From Monsters',
      '+10 To Vitality'
    ],
  },
  {
    id: 55,
    name: "Kingslayer",
    runes: [23, 22, 25, 19],
    types: ["Swords", "Axes"],
    excluded: "",
    classes: [],
    patch: "1.10",
    level: 53,
    ladder: false,
    reworked: true,
    stats: [
      '270-300% Enhanced Damage (varies)',
      '-25% Target Defense',
      '33% Chance of Crushing Blow',
      '50% Chance of Open Wounds',
      '+6 To Vengeance (paladin only)',
      'Repairs 1 durability in 20 seconds',
      'Prevent Monster Heal',
      '+10 To Strength',
      '20% Bonus To Attack Rating',
    ],
  },
  {
    id: 56,
    name: "Rift",
    runes: [15, 18, 20, 25],
    types: ["Polearms", "Scepters"],
    excluded: "",
    classes: [],
    patch: "1.10",
    level: 53,
    ladder: false,
    reworked: true,
    stats: [
      '20% Chance To Cast Level 16 Hurricane On Striking',
      '16% Chance To Cast Level 21 Frozen Orb On Attack',
      '+15% Cold Skill Damage',
      '+20% Increased Attack Speed',
      '+5-10 To All Stats (varies)',
      '38% Damage Taken Goes To Mana',
      'Level 15 Iron Maiden (40 Charges)',
      'Requirements -20%',
      '+10 To Dexterity',
      '75% Extra Gold From Monsters',
      '20% Bonus To Attack Rating',
    ],
  },
  {
    id: 57,
    name: "Principle",
    runes: [8, 24, 2],
    types: ["Body Armors"],
    excluded: "",
    classes: ["Paladin"],
    patch: "1.11",
    level: 51,
    ladder: false,
    reworked: true,
    stats: [
      "15% chance to cast level 25 Fist of Heavens on striking",
      "+2 To Paladin Skill Levels",
      "+50% Damage to Undead",
      "+100-150 To Life (varies)",
      "15% Slower Stamina Drain",
      "Fire Resist +30%",
      "+75% Better Chance of Getting Magic Items"
    ],
  },
  {
    id: 58,
    name: "Mosaic",
    runes: [23, 25, 11],
    types: ["Katars"],
    excluded: "",
    classes: ["Assassin"],
    patch: "2.6",
    level: 53,
    ladder: true,
    reworked: true,
    stats: [
      '+5 to Phoenix Strike (assassin only)',
      '+5 to Claws of Thunder (assassin only)',
      '+5 to Blades of Ice (assassin only)',
      '+50% Increased Attack Speed',
      '+8-15% to Cold Skill Damage',
      '+8-15% to Lightning Skill Damage',
      '+8-15% to Fire Skill Damage',
      'Prevent Monster Heal',
      '7% Life Steal',
      '+20% Bonus to Attack Rating'
    ],
  },
  {
    id: 59,
    name: "Silence",
    runes: [14, 2, 15, 24, 3, 26],
    types: ["Weapons"],
    excluded: "",
    classes: [],
    patch: "",
    level: 55,
    ladder: false,
    stats: [
      "200% Enhanced Damage",
      "+75% Damage To Undead",
      "Requirements -20%",
      "20% Increased Attack Speed",
      "+50 To Attack Rating Against Undead",
      "+2 To All Skills",
      "All Resistances +75",
      "20% Faster Hit Recovery",
      "11% Mana Stolen Per Hit",
      "Hit Causes Monster To Flee 25%",
      "Hit Blinds Target +33",
      "+2 To Mana After Each Kill",
      "30% Better Chance Of Getting Magic Items",
    ],
  },
  {
    id: 60,
    name: "Heart of the Oak",
    runes: [18, 26, 21, 10],
    types: ["Staves", "Maces"],
    excluded: "",
    classes: [],
    patch: "1.10",
    level: 55,
    ladder: false,
    stats: [
      "+3 To All Skills",
      "+40% Faster Cast Rate",
      "+75% Damage To Demons",
      "+100 To Attack Rating Against Demons",
      "Adds 3-14 Cold Damage, 3 sec. Duration (Normal)",
      "7% Mana Stolen Per Hit",
      "+10 To Dexterity",
      "Replenish Life +20",
      "Increase Maximum Mana 15%",
      "All Resistances +30-40 (varies)",
      "Level 4 Oak Sage (25 Charges)",
      "Level 14 Raven (60 Charges)",
    ],
  },
  {
    id: 61,
    name: "Death",
    runes: [15, 1, 26, 9, 25],
    types: ["Swords", "Axes"],
    excluded: "",
    classes: [],
    patch: "1.10",
    level: 55,
    ladder: false,
    stats: [
      "100% Chance To Cast Level 44 Chain Lightning When You Die",
      "25% Chance To Cast Level 18 Glacial Spike On Attack",
      "Indestructible",
      "+300-385% Enhanced Damage (varies)*",
      "20% Bonus To Attack Rating",
      "+50 To Attack Rating",
      "Adds 1-50 Lightning Damage",
      "7% Mana Stolen Per Hit",
      "50% Chance of Crushing Blow",
      "+(0.5 per Character Level) 0.5-49.5% Deadly Strike (Based on Character Level)",
      "+1 To Light Radius",
      "Level 22 Blood Golem  (15 Charges)",
      "Requirements -20%",
    ],
  },
  {
    id: 62,
    name: "Flickering Flame",
    runes: [4, 21, 26],
    types: ["Helms"],
    excluded: "",
    classes: [],
    patch: "2.4",
    level: 55,
    ladder: false,
    stats: [
      "Level 4-8 Resist Fire Aura When Equipped (varies)",
      "+3 To Fire Skills",
      "-10-15% to Enemy Fire Resistance (varies)",
      "+30% Enhanced Defense",
      "+30 Defense Vs. Missile",
      "+50-75 To Mana (varies)",
      "Half Freeze Duration",
      "+5% To Maximum Fire Resist",
      "Poison Length Reduced by 50%",
    ],
  },
  {
    id: 63,
    name: "Call to Arms",
    runes: [11, 8, 23, 24, 27],
    types: ["Weapons"],
    excluded: "",
    classes: [],
    patch: "1.10",
    level: 57,
    ladder: false,
    stats: [
      "+1 To All Skills",
      "+40% Increased Attack Speed",
      "+250-290% Enhanced Damage (varies)",
      "Adds 5-30 Fire Damage",
      "7% Life Stolen Per Hit",
      "+2-6 To Battle Command (varies)*",
      "+1-6 To Battle Orders (varies)*",
      "+1-4 To Battle Cry (varies)*",
      "Prevent Monster Heal",
      "Replenish Life +12",
      "30% Better Chance of Getting Magic Items",
    ],
  },
  {
    id: 64,
    name: "Chaos",
    runes: [19, 27, 22],
    types: ["Claws"],
    excluded: "",
    classes: ["Assassin"],
    patch: "1.10",
    level: 57,
    ladder: false,
    stats: [
      "9% Chance To Cast Level 11 Frozen Orb On Striking",
      "11% Chance To Cast Level 9 Charged Bolt On Striking",
      "+35% Increased Attack Speed",
      "+290-340% Enhanced Damage (varies)",
      "Adds 216-471 Magic Damage",
      "25% Chance of Open Wounds",
      "+1 To Whirlwind",
      "+10 To Strength",
      "+15 Life After Each Demon Kill",
    ],
  },
  {
    id: 65,
    name: "Exile",
    runes: [26, 27, 24, 14],
    types: ["Paladin Shields"],
    excluded: "",
    classes: ["Paladin"],
    patch: "1.10",
    level: 57,
    ladder: false,
    stats: [
      "15% Chance To Cast Level 5 Life Tap On Striking",
      "Level 13-16 Defiance Aura When Equipped (varies)",
      "+2 To Offensive Auras (Paladin Only)",
      "+30% Faster Block Rate",
      "Freezes Target",
      "+220-260% Enhanced Defense (varies)",
      "Replenish Life +7",
      "+5% To Maximum Cold Resist",
      "+5% To Maximum Fire Resist",
      "25% Better Chance Of Getting Magic Items",
      "Repairs 1 Durability in 4 Seconds",
    ],
  },
  {
    id: 66,
    name: "Fortitude",
    runes: [1, 12, 14, 28],
    types: ["Weapons", "Body Armors"],
    excluded: "",
    classes: [],
    patch: "1.10",
    level: 59,
    ladder: false,
    stats: [
      "Weapons",
      "20% Chance To Cast Level 15 Chilling Armor when Struck",
      "+25% Faster Cast Rate",
      "+300% Enhanced Damage",
      "+9 To Minimum Damage",
      "+50 To Attack Rating",
      "20% Deadly Strike",
      "Hit Causes Monster To Flee 25%",
      "+200% Enhanced Defense",
      "+X To Life (Based on Character Level)*",
      "All Resistances +25-30 (varies)",
      "12% Damage Taken Goes To Mana",
      "+1 To Light Radius",

      "Body Armor",
      "20% Chance To Cast Level 15 Chilling Armor when Struck",
      "+25% Faster Cast Rate",
      "+300% Enhanced Damage",
      "+200% Enhanced Defense",
      "+15 Defense",
      "+X To Life (Based on Character Level)*",
      "Replenish Life +7",
      "+5% To Maximum Lightning Resist",
      "All Resistances +25-30 (varies)",
      "Damage Reduced By 7",
      "12% Damage Taken Goes To Mana",
      "+1 To Light Radius",
    ],
  },
  {
    id: 67,
    name: "Grief",
    runes: [5, 3, 28, 23, 8],
    types: ["Swords", "Axes"],
    excluded: "",
    patch: "1.10",
    level: 59,
    ladder: false,
    reworked: true,
    stats: [
      '35% Chance To Cast Level 15 Venom On Striking',
      '+30-40% Increased Attack Speed (varies)',
      'Damage +320-360 (varies)',
      "Ignore Target's Defense",
      '+(1.875 per character level) 1.875-185.625% Damage To Demons (Based on Character Level) ',
      '-20-25% To Enemy Poison Resistance (varies)',
      '+10-15 Life After Each Kill (varies)',
      '20% Deadly Strike',
      'Prevent Monster Heal',
      '+2 To Mana After Each Kill',
      'Adds 5-30 Fire Damage',
      '-25% Target Defense',
    ],
  },
  {
    id: 68,
    name: "Bramble",
    runes: [8, 27, 29, 5],
    types: ["Body Armors"],
    excluded: "",
    patch: "1.10",
    level: 61,
    ladder: false,
    stats: [
      "Level 15-21 Thorns Aura When Equipped (varies)",
      "+50% Faster Hit Recovery",
      "+25-50% To Poison Skill Damage (varies)",
      "+300 Defense",
      "Increase Maximum Mana 5%",
      "Regenerate Mana 15%",
      "+5% To Maximum Cold Resist",
      "Fire Resist +30%",
      "Poison Resist +100%",
      "+13 Life After Each Kill",
      "Level 13 Spirit of Barbs (33 Charges)",
    ],
  },
  {
    id: 69,
    name: "Wind",
    runes: [29, 1],
    types: ["Melee Weapons"],
    excluded: "",
    patch: "1.10",
    level: 61,
    ladder: false,
    reworked: true,
    stats: [
      '+1 to All Skills',
      '+20% Faster Run/Walk',
      '25% Chance To Cast Level 9 Twister On Striking',
      '+40% Increased Attack Speed',
      'Adds Damage +280-320 (varies)',
      '-50% Target Defense',
      '+10% Faster Cast Rate',
      'Hit Blinds Target',
      '+1 To Light Radius',
      '+50 To Attack Rating'
    ],
  },
  {
    id: 70,
    name: "Dragon",
    runes: [29, 28, 12],
    types: ["Body Armors", "Shields"],
    excluded: "",
    patch: "1.10",
    level: 61,
    ladder: false,
    stats: [
      "20% Chance to Cast Level 18 Venom When Struck",
      "12% Chance To Cast Level 15 Hydra On Striking",
      "Level 14 Holy Fire Aura When Equipped",
      "+360 Defense",
      "+230 Defense Vs. Missile",
      "+3-5 To All Attributes (varies)",
      "+0.375-37.125 To Strength (Based on Character Level)",
      "Increase Maximum Mana 5% (Armor Only)",
      "+50 To Mana (Shields Only)",
      "+5% To Maximum Lightning Resist",
      "Damage Reduced by 7",
    ],
  },
  {
    id: 71,
    name: "Beast",
    runes: [30, 3, 22, 23, 17],
    types: ["Axes", "Scepters", "Hammers"],
    excluded: "",
    patch: "1.10",
    level: 63,
    ladder: false,
    stats: [
      "Level 9 Fanaticism Aura When Equipped",
      "+40% Increased Attack Speed",
      "+240-270% Enhanced Damage (varies)",
      "20% Chance of Crushing Blow",
      "25% Chance of Open Wounds",
      "+3 To Werebear",
      "+3 To Lycanthropy",
      "Prevent Monster Heal",
      "+25-40 To Strength (varies)",
      "+10 To Energy",
      "+2 To Mana After Each Kill",
      "Level 13 Summon Grizzly (5 Charges)",
    ],
  },
  {
    id: 72,
    name: "Chains of Honor",
    runes: [14, 22, 30, 24],
    types: ["Body Armors"],
    excluded: "",
    patch: "1.10",
    level: 63,
    ladder: false,
    reworked: true,
    stats: [
      'Magic damage reduced by 25',
      '+15% increased attack speed',
      '400% Damage To Demons',
      '10% Life Stolen Per Hit',
      '120% Enhanced Defense',
      'All Resistances +65',
      '+75% Better Chance of Getting Magic Items',
      'Damage Reduced By 8%',
      'Replenish Life +7'
    ],
  },
  {
    id: 73,
    name: "Eternity",
    runes: [11, 30, 24, 12, 29],
    types: ["Melee Weapons"],
    excluded: "",
    patch: "1.10",
    level: 63,
    ladder: false,
    reworked: true,
    stats: [
      'Indestructible',
      '310-350% Enhanced Damage (varies)',
      'Slows Target By 33%',
      '+1 to Teleport',
      '+6 to Enchant',
      '+6 to Revive',
      '+9 To Minimum Damage',
      '7% Life Stolen Per Hit',
      '20% Chance of Crushing Blow',
      'Hit Blinds Target',
      '30% Better Chance Of Getting Magic Items',
    ],
  },
  {
    id: 74,
    name: "Infinity",
    runes: [30, 23, 30, 24],
    types: ["Polearms", "Spears"],
    excluded: "",
    patch: "1.10",
    level: 63,
    ladder: false,
    stats: [
      "50% Chance To Cast Level 20 Chain Lightning When You Kill An Enemy",
      "Level 12 Conviction Aura When Equipped",
      "+35% Faster Run/Walk",
      "+255-325% Enhanced Damage (varies)",
      "-(45-55)% To Enemy Lightning Resistance (varies)",
      "40% Chance of Crushing Blow",
      "Prevent Monster Heal",
      "0.5-49.5 To Vitality (Based on Character Level)",
      "30% Better Chance of Getting Magic Items",
      "Level 21 Cyclone Armor (30 Charges)",
    ],
  },
  {
    id: 75,
    name: "Wrath",
    runes: [21, 17, 30, 23],
    types: ["Missile Weapons"],
    excluded: "",
    patch: "1.10",
    level: 63,
    ladder: false,
    reworked: true,
    stats: [
      '15% Chance To Cast Level 14 Amplify Damage On Striking',
      '5% Chance To Cast Level 10 Life Tap On Striking',
      '+300% Enhanced Damage',
      '+1 to Multishot',
      '+20% Increased Attack Speed',
      'Cannot Be Frozen',
      '20% Chance of Crushing Blow',
      'Prevent Monster Heal',
      '+10 To Energy',
      '75% Damage To Demons',
      '+100 To Attack Rating Against Demons'
    ],
  },
  {
    id: 76,
    name: "Fury",
    runes: [31, 25, 5],
    types: ["Melee Weapons"],
    excluded: "",
    patch: "1.10",
    level: 65,
    ladder: false,
    stats: [
      "+209% Enhanced Damage",
      "40% Increased Attack Speed",
      "Prevent Monster Heal",
      "66% Chance Of Open Wounds",
      "33% Deadly Strike",
      "Ignore Target's Defense",
      "-25% Target Defense",
      "20% Bonus To Attack Rating",
      "6% Life Stolen Per Hit",
      "+5 To Frenzy (Barbarian Only)",
    ],
  },
  {
    id: 77,
    name: "Enigma",
    runes: [31, 6, 30],
    types: ["Body Armors"],
    excluded: "",
    patch: "1.10",
    level: 65,
    ladder: false,
    stats: [
      "+2 To All Skills",
      "+45% Faster Run/Walk",
      "+1 To Teleport",
      "+750-775 Defense (varies)",
      "+ (0.75 Per Character Level) +0-74 To Strength (Based On Character Level)",
      "Increase Maximum Life 5%",
      "Damage Reduced By 8%",
      "+14 Life After Each Kill",
      "15% Damage Taken Goes To Mana",
      "+ (1 Per Character Level) +1-99% Better Chance of Getting Magic Items (Based On Character Level)",
    ],
  },
  {
    id: 78,
    name: "Famine",
    runes: [19, 27, 9, 31],
    types: ["Missile Weapons"],
    excluded: "",
    patch: "1.10",
    level: 65,
    ladder: false,
    reworked: true,
    stats: [
      '85% Increased Attack Speed',
      '250% Enhanced Damage',
      'Fires Explosive arrows or bolts [Level 12]',
      'Adds 520-840 Fire Damage',
      'Adds 1-2030 Lightning Damage',
      '10% chance to cast level 7 Lower Resist on striking',
      '+1 to Fire Mastery',
      '+10 To Strength',
      "Ignore Target's Defense",
    ],
  },
  {
    id: 79,
    name: "Brand",
    runes: [31, 28, 23, 25],
    types: ["Missile Weapons"],
    excluded: "",
    patch: "1.10",
    level: 65,
    ladder: false,
    reworked: true,
    stats: [
      '30% Chance To Cast Level 1 Decrepify On Striking',
      '100% Chance To Cast Level 18 Bone Spear On Striking',
      '+365-400% Enhanced Damage (varies)',
      '+280-330% Damage To Demons (varies)',
      '+50% Deadly Strike',
      'Knockback',
      'Fires Explosive Arrows or Bolts (15)',
      'Prevent Monster Heal',
      '20% Bonus to Attack Rating',
      "Ignore Target's Defense"
    ],
  },
  {
    id: 80,
    name: "Destruction",
    runes: [26, 28, 30, 31, 18],
    types: ["Weapons"],
    excluded: "",
    patch: "1.10",
    level: 65,
    ladder: false,
    reworked: true,
    stats: [
      '10% chance to cast level 25 Immolation Arrow on striking',
      '15% chance to cast level 30 Fissure on striking',
      '10% chance to cast level 20 Death Sentry when you kill an enemy',
      '10% chance to cast Level 20 Armageddon when you kill an enemy',
      '+350% Enhanced Damage',
      '20% increased attack speed',
      'Knockback',
      '+10 To Dexterity',
      '20% Chance Of Crushing Blow',
      '20% Deadly Strike',
      "Ignore Target's Defense",
      '7% Mana Stolen Per Hit',
    ],
  },
  {
    id: 81,
    name: "Dream",
    runes: [16, 31, 21],
    types: ["Helms", "Shields"],
    excluded: "",
    patch: "1.10",
    level: 65,
    ladder: false,
    stats: [
      "10% Chance To Cast Level 15 Confuse When Struck",
      "Level 15 Holy Shock Aura When Equipped",
      "+20-30% Faster Hit Recovery (varies)",
      "+30% Enhanced Defense",
      "+150-220 Defense (varies)",
      "+10 To Vitality",
      "Increase Maximum Life 5% (Helms Only)",
      "+50 To Life (Shields Only)",
      "+0.625-61.875 To Mana (Based On Character Level)",
      "All Resistances +5-20 (varies)",
      "12-25% Better Chance of Getting Magic Items (varies)",
    ],
  },
  {
    id: 82,
    name: "Faith",
    runes: [27, 31, 20, 2],
    types: ["Missile Weapons"],
    excluded: "",
    patch: "1.10",
    level: 65,
    ladder: false,
    stats: [
      'Level 12-15 Fanaticism Aura When Equipped (varies)',
      '+1-2 To All Skills (varies)',
      '+330% Enhanced Damage',
      "Ignore Target's Defense",
      '300% Bonus To Attack Rating',
      '+75% Damage To Undead',
      '+50 To Attack Rating Against Undead',
      '+120 Fire Damage',
      'All Resistances +15',
      '10% Reanimate As: Returned',
      '75% Extra Gold From Monsters',
    ],
  },
  {
    id: 83,
    name: "Ice",
    runes: [11, 13, 31, 28],
    types: ["Missile Weapons"],
    excluded: "",
    patch: "1.10",
    level: 65,
    ladder: false,
    reworked: true,
    stats: [
      '100% chance to cast level 26 Arctic Blast on striking',
      'Level 18 Holy Freeze Aura When Equipped',
      '+90% Increased Attack Speed',
      '+285-310% Enhanced Damage (varies)',
      '+25-30% To Cold Skill Damage (varies)',
      '-20% To Enemy Cold Resistance',
      '3.125-309.375 Extra Gold From Monsters (Based on Character Level)',
      '7% Life Stolen Per Hit',
      '20% Deadly Strike',
      "Ignore Target's Defense",
    ],
  },
  {
    id: 84,
    name: "Last Wish",
    runes: [31, 23, 31, 29, 31, 30],
    types: ["Weapons"],
    excluded: "",
    patch: "1.10",
    level: 65,
    ladder: false,
    reworked: true,
    stats: [
      '6% Chance To Cast Level 11 Burst of Speed When you kill an enemy',
      '10% Chance To Cast Level 18 Life Tap On Striking',
      'Level 12-17 Might Aura When Equipped (varies)',
      '+496% Enhanced Damage',
      '+ (2.5 Per Character Level) 2-247 To Maximum Damage (Based On Character Level)',
      '60-70% Chance of Crushing Blow (varies)',
      '60-70% Deadly Strike (varies)',
      'Prevent Monster Heal',
      'Hit Blinds Target',
      "Ignore Target's Defense",
    ],
  },
  {
    id: 85,
    name: "Phoenix",
    runes: [26, 26, 28, 31],
    types: ["Weapons", "Shields"],
    excluded: "",
    patch: "1.10",
    level: 65,
    ladder: false,
    reworked: true,
    stats: [
      'Weapons',
      '100% Chance To Cast level 40 Blaze When You Level-up',
      '20% Chance to cast level 44 Firestorm on striking',
      'Level 10-15 Redemption Aura When Equipped (varies)',
      '+350-400% Enhanced Damage (varies)',
      '-28% To Enemy Fire Resistance',
      'Repairs 1 durability in 5 seconds',
      '+15-21 Fire Absorb (varies)',
      '20% Deadly Strike',
      'Ignores Target Defense',
      '14% Mana Stolen Per Hit',

      'Shields',
      '100% Chance To Cast level 40 Blaze When You Level-up',
      '20% Chance to cast level 44 Firestorm on striking',
      'Level 10-15 Redemption Aura When Equipped (varies)',
      'Repairs 1 durability in 5 seconds',
      '+350-400% Enhanced Damage (varies)',
      '-28% To Enemy Fire Resistance',
      '+15-21 Fire Absorb (varies)',
      '+50 To Life',
      '+5% To Maximum Lightning Resist',
      '+10% To Maximum Fire Resist'
    ],
  },
  {
    id: 86,
    name: "Doom",
    runes: [15, 27, 22, 28, 32],
    types: ["Melee Weapons"],
    excluded: "",
    patch: "1.10",
    level: 67,
    ladder: false,
    reworked: true,
    stats: [
      '5% Chance To Cast Level 18 Armageddon On Striking',
      'Level 12 Holy Freeze Aura When Equipped',
      '+2 To All Skills',
      '+45% Increased Attack Speed',
      '+330-370% Enhanced Damage (varies)',
      '-(40-60)% To Enemy Cold Resistance (varies)',
      'Repairs 1 durability in 5 seconds',
      '-(40-60)% To Enemy Cold Resistance (varies)',
      'Freezes Target +3',
      'Requirements -20%',
      '20% Deadly Strike',
      '25% Chance of Open Wounds',
    ],
  },
  {
    id: 87,
    name: "Hand of Justice",
    runes: [29, 32, 11, 28],
    types: ["Weapons"],
    excluded: "",
    patch: "1.10",
    level: 67,
    ladder: false,
    reworked: true,
    stats: [
      '100% Chance To Cast Level 48 Meteor When You Die',
      'Level 16 Holy Fire Aura When Equipped',
      '+33% Increased Attack Speed',
      '+280-330% Enhanced Damage (varies)',
      "Ignore Target's Defense",
      '-20% To Enemy Fire Resistance',
      '+20% fire skill damage',
      '20% Deadly Strike',
      'Hit Blinds Target',
      'Freezes Target +3',
      '7% Life Stolen Per Hit',
    ],
  },
  {
    id: 88,
    name: "Pride",
    runes: [32, 29, 16, 28],
    types: ["Polearms", "Spears"],
    excluded: "",
    patch: "1.10",
    level: 67,
    ladder: false,
    reworked: true,
    stats: [
      'Indestructible',
      '450-500% enhanced damage',
      'Level 16-20 Concentration Aura When Equipped (varies)',
      '260-300% Bonus To Attack Rating (varies)',
      '+4-396% Damage To Demons (Based on Character Level)',
      '+6 to Fend (Amazon only)',
      '+6 to Jab (Amazon only)',
      '20% Deadly Strike',
      'Hit Blinds Target',
      'Freezes Target +3',
      '+10 To Vitality',
    ],
  },
  {
    id: 89,
    name: "Plague",
    runes: [32, 13, 22],
    types: ["Swords", "Claws", "Daggers"],
    excluded: "",
    patch: "2.4",
    level: 67,
    ladder: false,
    stats: [
      '20% Chance to Cast level 12 Lower Resist when struck',
      '25% Chance to Cast level 15 Poison Nova on striking',
      'Level 13-17 Cleansing Aura When Equipped (varies)',
      '+1-2 All Skills',
      '+20% Increased Attack Speed',
      '+220-320% Enhanced Damage (varies)',
      '-23% To Enemy Poison Resistance',
      '0.3% (0-29.7) Deadly Strike (Based on Character Level)',
      '+25% Chance of Open Wounds',
      'Freezes Target +3',
    ],
  },
  {
    id: 90,
    name: "Mist",
    runes: [32, 13, 25, 10, 6],
    types: ["Missile Weapons"],
    excluded: "",
    patch: "2.4",
    level: 67,
    ladder: false,
    reworked: true,
    stats: [
      'Level 8-12 Concentration Aura When Equipped (varies)',
      '+60% Increased Attack Speed',
      '+100% Piercing Attack',
      '+325-375% Enhanced Damage (varies)',
      '20% chance to cast level 16 Inner Sight on attack',
      '10% chance to cast level 12 Fade when you kill an Enemy',
      'All Resistances +40',
      'Freeze Target +3',
      '20% Bonus to Attack Rating',
      'Adds 3-14 Cold Damage',
      '+9 To Maximum Damage'
    ],
  },
  {
    id: 91,
    name: "Metamorphosis",
    runes: [16, 32, 19],
    types: ["Helms"],
    excluded: "",
    classes: ["Druid"],
    patch: "2.6",
    level: 67,
    ladder: true,
    stats: [
      '100% Chance to cast level 1 Mark of the Wolf on striking',
      '100% Chance to cast level 1 Mark of the Bear on striking',
      '+5 to Shape Shifting Skills (Druid only)',
      '+25% Chance of Crushing Blow',
      '+50-80% Enhanced Defense',
      '+10 to Strength',
      '+10 to Vitality',
      'All Resistances +10',
      'Cannot be Frozen',
    ],
  },
  {
    id: 92,
    name: "Breath of the Dying",
    runes: [26, 15, 1, 2, 33, 5],
    types: ["Weapons"],
    excluded: "",
    classes: [],
    patch: "1.10",
    level: 69,
    ladder: false,
    reworked: true,
    stats: [
      '50% Chance To Cast Level 20 Poison Nova When You Kill An Enemy',
      '+60% Increased Attack Speed',
      '375-435% Enhanced Damage (varies)',
      '+30% Crushing Blow',
      '12-15% Life Stolen Per Hit (varies)',
      'Prevent Monster Heal',
      'Requirements -40%',
      '+50 To Attack Rating',
      '+50 To Attack Rating Against Undead',
      '7% Mana Stolen Per Hit',
      '75%  Damage To Undead',
      '+1 To Light Radius',
      '-25% Target Defense',
      'Indestructible',
    ],
  },
  {
    id: 93,
    name: "Obsession",
    runes: [33, 24, 20, 17, 16, 4],
    types: ["Staves"],
    excluded: "",
    classes: [],
    patch: "2.4",
    level: 69,
    ladder: false,
    stats: [
      'Indestructible',
      '24% Chance to cast level 10 Weaken when struck',
      '+4 To All Skills',
      '+65% Faster Cast Rate',
      '+60% Faster Hit Recovery',
      'Knockback',
      '+10 To Vitality',
      '+10 To Energy',
      'Increase Maximum Life 15-25% (varies)',
      'Regenerate Mana 15-30% (varies)',
      'All Resistances +60-70 (varies)',
      '75% Extra Gold from Monsters',
      '30% Better Chance of Getting Magic Items',
    ],
  },
];
