export const RUNEWORDS = [
  {
    id: 1,
    name: {
      ru: "Упадок",
      en: "Nadir",
    },
    runes: [4, 3],
    types: [18],
    level: 13,
    ladder: false,
    stats: {
      ru: [
        "+50% к защите",
        "+10 к защите",
        "+30 к защите от снарядов",
        "+5 к силе",
        "+2 к мане при убийстве",
        "-33% к золоту за убийство монстров",
        "-3 к радиусу обзора",
        "«Покров теней» 13-го уровня (9 зарядов)",
      ],
      en: [
        "+50% Enhanced Defense",
        "+10 Defense",
        "+30 Defense vs. Missile",
        "+5 To Strength",
        "+2 To Mana After Each Kill",
        "-33% Extra Gold From Monsters",
        "-3 To Light Radius",
        "Level 13 Cloak of Shadows (9 Charges)",
      ],
    },
    complete: false,
  },

  {
    id: 2,
    name: {
      ru: "Сталь",
      en: "Steel",
    },
    runes: [3, 1],
    types: [3, 1, 2],
    level: 13,
    ladder: false,
    stats: {
      ru: [
        "+25% к скорости атаки",
        "+20% к урону",
        "+3 к минимальному урону",
        "+3 к максимальному урону",
        "+50 к рейтингу атаки",
        "+50% к вероятности нанести открытую рану",
        "+2 к мане при убийстве",
        "+1 к радиусу обзора",
      ],
      en: [
        "25% Increased Attack Speed",
        "20% Enhanced Damage",
        "+3 To Minimum Damage",
        "+3 To Maximum Damage",
        "+50 To Attack Rating",
        "50% Chance Of Open Wounds",
        "+2 To Mana After Each Kill",
        "+1 To Light Radius",
      ],
    },
    complete: false,
  },

  {
    id: 3,
    name: {
      ru: "Злоба",
      en: "Malice",
    },
    runes: [6, 1, 5],
    types: [4],
    level: 15,
    ladder: false,
    stats: {
      ru: [
        "+33% к урону",
        "+9 к максимальному урону",
        "-25% к защите цели",
        "+50 к рейтингу атаки",
        "+100% к вероятности нанести открытую рану",
        "Запрещает монстрам лечиться",
        "-100 к защите от монстров за удар",
        "Похищает -5 здоровья",
      ],
      en: [
        "+33% Enhanced Damage",
        "+9 To Maximum Damage",
        "-25% Target Defense",
        "+50 To Attack Rating",
        "100% Chance Of Open Wounds",
        "Prevent Monster Heal",
        "-100 To Monster Defense Per Hit",
        "Drain Life -5",
      ],
    },
    complete: false,
  },

  {
    id: 4,
    name: {
      ru: "Незаметность",
      en: "Stealth",
    },
    runes: [7, 5],
    types: [17],
    level: 17,
    ladder: false,
    stats: {
      ru: [
        "+25% к скорости ходьбы и бега",
        "+25% к скорости применения умений",
        "+25% к ускоренному восстановлению от удара",
        "+6 к ловкости",
        "Восполняет 15% маны",
        "15 к максимальной выносливости",
        "+30% к сопротивлению яду",
        "-3 к магическому урону",
      ],
      en: [
        "25% Faster Run/Walk",
        "25% Faster Cast Rate",
        "25% Faster Hit Recovery",
        "+6 To Dexterity",
        "Regenerate Mana 15%",
        "+15 To Maximum Stamina",
        "Poison Resist +30%",
        "Magic Damage Reduced By 3",
      ],
    },
    complete: false,
  },

  {
    id: 5,
    name: {
      ru: "Лист",
      en: "Leaf",
    },
    runes: [3, 8],
    types: [5],
    excluded: "Not Orbs/Wands",
    level: 19,
    ladder: false,
    stats: {
      ru: [
        "+3 к умениям огня",
        "+5-30 урона от огня",
        "+3 к умению «Инферно»",
        "+3 к умению «Тепло»",
        "+3 к умению «Стрела огня»",
        "+(2 за уровень персонажа) к защите (зависит от уровня персонажа)",
        "+33% к сопротивлению льду",
        "+2 к мане при убийстве",
      ],
      en: [
        "+3 To Fire Skills",
        "Adds 5-30 Fire Damage",
        "+3 To Inferno (Sorceress Only)",
        "+3 To Warmth (Sorceress Only)",
        "+3 To Fire Bolt (Sorceress Only)",
        "+ (2 Per Character Level) +2-198 To Defense (Based On Character Level)",
        "Cold Resist +33%",
        "+2 To Mana After Each Kill",
      ],
    },
    complete: false,
  },

  {
    id: 6,
    name: {
      ru: "Клятва Древних",
      en: "Ancient's Pledge",
    },
    runes: [8, 9, 7],
    types: [16],
    excluded: "",
    level: 21,
    ladder: false,
    stats: {
      ru: [
        "+50% к защите",
        "+43% к сопротивлению льду",
        "+48% к сопротивлению молнии",
        "+48% к сопротивлению огню",
        "+48% к сопротивлению яду",
        "+10% к урону, приходящемуся на ману",
      ],
      en: [
        "+50% Enhanced Defense",
        "Cold Resist +43%",
        "Lightning Resist +48%",
        "Fire Resist +48%",
        "Poison Resist +48%",
        "10% Damage Taken Goes To Mana",
      ],
    },
    complete: false,
  },

  {
    id: 7,
    name: {
      ru: "Божественный гром",
      en: "Holy Thunder",
    },
    runes: [5, 8, 9, 7],
    types: [7],
    excluded: "",
    level: 21,
    ladder: false,
    stats: {
      ru: [
        "+60% к урону",
        "+10 к максимальному урону",
        "-25% к защите цели",
        "+5-30 урона от огня",
        "+21-110 урона от молнии",
        "+75 урона от яда за 5 сек.",
        "+3 к умению «Священная молния» (только для паладинов)",
        "+5% к максимальному сопротивлению молнии",
        "+60% к сопротивлению молнии",
        "«Цепная молния» 7-го уровня (60/60 зарядов)",
      ],
      en: [
        "+60% Enhanced Damage",
        "+10 To Maximum Damage",
        "-25% Target Defense",
        "Adds 5-30 Fire Damage",
        "Adds 21-110 Lightning Damage",
        "+75 Poison Damage Over 5 Seconds",
        "+3 To Holy Shock (Paladin Only)",
        "+5 To Maximum Lightning Resistance",
        "Lightning Resistance +60%",
        "Level 7 Chain Lightning (60 Charges)",
      ],
    },
    complete: false,
  },

  {
    id: 8,
    name: {
      ru: "Бриз",
      en: "Zephyr",
    },
    runes: [9, 5],
    types: [6],
    excluded: "",
    level: 21,
    ladder: false,
    stats: {
      ru: [
        "Вероятность 7% применить умение «Смерч» 1-го уровня при получении урона",
        "+25% к скорости ходьбы и бега",
        "+25% к скорости атаки",
        "+33% к урону",
        "-25% к защите цели",
        "+66 к рейтингу атаки",
        "+1-50 урона от молнии",
        "+25 к защите",
      ],
      en: [
        "7% Chance To Cast Level 1 Twister When Struck",
        "25% Faster Run/Walk",
        "25% Increased Attack Speed",
        "+33% Enhanced Damage",
        "-25% Target Defense",
        "+66 To Attack Rating",
        "Adds 1-50 Lightning Damage",
        "+25 Defense",
      ],
    },
    complete: false,
  },

  {
    id: 10,
    name: {
      ru: "Милость короля",
      en: "King's Grace",
    },
    runes: [11, 8, 10],
    types: [3, 7],
    excluded: "",
    classes: [],
    patch: "",
    level: 25,
    ladder: false,
    stats: {
      ru: [
        "+100% к урону",
        "+150 к рейтингу атаки",
        "+100% к урону по демонам",
        "+100 к рейтингу атаки против демонов",
        "+50% урона по нежити",
        "+100 к рейтингу атаки против нежити",
        "+5-30 урона от огня",
        "+3-14 урона от льда",
        "Похищает 7% здоровья за удар",
      ],
      en: [
        "+100% Enhanced Damage",
        "+150 To Attack Rating",
        "+100% Damage To Demons",
        "+100 To Attack Rating Against Demons",
        "+50% Damage To Undead",
        "+100 To Attack Rating Against Undead",
        "Adds 5-30 Fire Damage",
        "Adds 3-14 Cold Damage - 3 Second Duration",
        "7% Life Stolen Per Hit",
      ],
    },
    complete: false,
  },

  {
    id: 11,
    name: {
      ru: "Сила",
      en: "Strength",
    },
    runes: [11, 3],
    types: [4],
    excluded: "",
    classes: [],
    patch: "",
    level: 25,
    ladder: false,
    stats: {
      ru: [
        "+35% к урону",
        "Похищает 7% здоровья за удар",
        "+25% к вероятности нанести сокрушающий удар",
        "+20 к силе",
        "+10 к живучести",
        "+2 к мане при убийстве",
      ],
      en: [
        "35% Enhanced Damage",
        "7% Life Stolen Per Hit",
        "25% Chance Of Crushing Blow",
        "+20 To Strength",
        "+10 To Vitality",
        "+2 To Mana After Each Kill",
      ],
    },
    complete: false,
  },

  {
    id: 12,
    name: {
      ru: "Острие",
      en: "Edge",
    },
    runes: [3, 7, 11],
    types: [6],
    excluded: "",
    classes: [],
    patch: "1.10",
    level: 25,
    ladder: false,
    stats: {
      ru: [
        "При надевании дает ауру «Шипы» 15-го уровня",
        "+35% к скорости атаки",
        "+<span class='varies'>320-380</span>% к урону по демонам",
        "+280% урона по нежити",
        "+75 урона от яда за 5 сек.",
        "Похищает 7% здоровья за удар",
        "Запрещает монстрам лечиться",
        "+<span class='varies'>5-10</span> ко всем характеристикам",
        "+2 к мане при убийстве",
        "Снижает цены у торговцев на 15%",
      ],
      en: [
        "Level 15 Thorns Aura When Equipped",
        "+35% Increased Attack Speed",
        "+<span class='varies'>320-380</span>% Damage To Demons (varies)",
        "+280% Damage To Undead",
        "+75 Poison Damage Over 5 Seconds",
        "7% Life Stolen Per Hit",
        "Prevent Monster Heal",
        "+<span class='varies'>5-10</span> To All Attributes (varies)",
        "+2 To Mana After Each Kill",
        "Reduces All Vendor Prices 15%!!!",
      ],
    },
    complete: false,
  },

  {
    id: 13,
    name: {
      ru: "Дух",
      en: "Spirit",
    },
    runes: [7, 10, 9, 11],
    types: [3, 16],
    excluded: "",
    classes: [],
    patch: "1.10",
    level: 25,
    ladder: false,
    stats: {
      ru: [
        "#Мечи#",
        "+2 ко всем умениям",
        "+<span class='varies'>25-35</span>% к скорости применения умений",
        "+55% к ускоренному восстановлению от удара",
        "+250 к защите от снарядов",
        "+22 к живучести",
        "+<span class='varies'>89-112</span> к мане",
        "+<span class='varies'>3-8</span> поглощаемого магического урона",
        "+1-50 урона от молнии",
        "+3-14 урона от льда",
        "+75 урона от яда за 5 сек.",
        "Похищает 7% здоровья за удар",

        "#Щиты#",
        "+2 ко всем умениям",
        "+<span class='varies'>25-35</span>% к скорости применения умений",
        "+55% к ускоренному восстановлению от удара",
        "+250 к защите от снарядов",
        "+22 к живучести",
        "+<span class='varies'>89-112</span> к мане",
        "+<span class='varies'>3-8</span> поглощаемого магического урона",
        "+35% к сопротивлению льду",
        "+35% к сопротивлению молнии",
        "+35% к сопротивлению яду",
        "Атакующий получает 14 урона",
      ],
      en: [
        "#Swords#",
        "+2 To All Skills",
        "+<span class='varies'>25-35</span>% Faster Cast Rate (varies)",
        "+55% Faster Hit Recovery",
        "Adds 1-50 Lightning Damage",
        "Adds 3-14 Cold Damage 3 Second Duration (Normal)",
        "+75 Poison Damage Over 5 Seconds",
        "7% Life Stolen Per Hit",
        "+250 Defense Vs. Missile",
        "+22 To Vitality",
        "+<span class='varies'>89-112</span> To Mana (varies)",
        "+<span class='varies'>3-8</span> Magic Absorb (varies)",
        "#Shields#",
        "+2 To All Skills",
        "+<span class='varies'>25-35</span>% Faster Cast Rate (varies)",
        "+55% Faster Hit Recovery",
        "+250 Defense Vs. Missile",
        "+22 To Vitality",
        "+<span class='varies'>89-112</span> To Mana (varies)",
        "Cold Resist +35%",
        "Lightning Resist +35%",
        "Poison Resist +35%",
        "+<span class='varies'>3-8</span> Magic Absorb (varies)",
        "Attacker Takes Damage of 14",
      ],
    },
    complete: false,
  },

  {
    id: 15,
    name: {
      ru: "Честь",
      en: "Honor",
    },
    runes: [11, 1, 6, 3, 12],
    types: [4],
    excluded: "",
    classes: [],
    patch: "",
    level: 27,
    ladder: false,
    stats: {
      ru: [
        "+1 ко всем умениям",
        "+160% к урону",
        "+9 к минимальному урону",
        "+9 к максимальному урону",
        "+250 к рейтингу атаки",
        "Похищает 7% здоровья за удар",
        "+25% к вероятности нанести смертельный удар",
        "+10 к силе",
        "Восполняет +10 здоровья",
        "+2 к мане при убийстве",
        "+1 к радиусу обзора",
      ],
      en: [
        "+1 to All Skills",
        "+160% Enhanced Damage",
        "+9 To Minimum Damage",
        "+9 To Maximum Damage",
        "+250 To Attack Rating",
        "7% Life Stolen Per Hit",
        "25% Deadly Strike",
        "+10 To Strength",
        "Replenish Life +10",
        "+2 To Mana After Each Kill",
        "+1 To Light Radius",
      ],
    },
    complete: false,
  },

  {
    id: 16,
    name: {
      ru: "История",
      en: "Lore",
    },
    runes: [9, 12],
    types: [18],
    excluded: "",
    classes: [],
    patch: "",
    level: 27,
    ladder: false,
    stats: {
      ru: [
        "+1 ко всем умениям",
        "+10 к энергии",
        "+30% к сопротивлению молнии",
        "-7 к урону",
        "+2 к мане при убийстве",
        "+2 к радиусу обзора",
      ],
      en: [
        "+1 To All Skills",
        "+10 To Energy",
        "Lightning Resist +30%",
        "Damage Reduced By 7",
        "+2 To Mana After Each Kill",
        "+2 To Light Radius",
      ],
    },
    complete: false,
  },

  {
    id: 17,
    name: {
      ru: "Сияние",
      en: "Radiance",
    },
    runes: [4, 12, 6],
    types: [18],
    excluded: "",
    classes: [],
    patch: "",
    level: 27,
    ladder: false,
    stats: {
      ru: [
        "+75% к защите",
        "+30 к защите от снарядов",
        "+10 к живучести",
        "+10 к энергии",
        "+33 к мане",
        "-7 к урону",
        "-3 к магическому урону",
        "+15% к урону, приходящемуся на ману",
        "+5 к радиусу обзора",
      ],
      en: [
        "+75% Enhanced Defense",
        "+30 Defense Vs. Missile",
        "+10 To Vitality",
        "+10 To Energy",
        "+33 To Mana",
        "Damage Reduced By 7",
        "Magic Damage Reduced By 3",
        "15% Damage Goes To Mana",
        "+5 To Light Radius",
      ],
    },
    complete: false,
  },

  {
    id: 18,
    name: {
      ru: "Прозрение",
      en: "Insight",
    },
    runes: [8, 3, 7, 12],
    types: [6, 9, 5],
    excluded: "Not Spears",
    classes: [],
    patch: "1.10",
    level: 27,
    ladder: false,
    stats: {
      ru: [
        "При надевании дает ауру «Медитация» <span class='varies'>12-17</span>-го уровня",
        "+35% к скорости применения умений",
        "+<span class='varies'>200-260</span>% к урону",
        "+9 к минимальному урону",
        "+<span class='varies'>180-250</span>% к рейтингу атаки",
        "+5-30 урона от огня",
        "+75 урона от яда за 5 сек.",
        "+<span class='varies'>1-6</span> к умению «Критический удар»",
        "+5 ко всем характеристикам",
        "+2 к мане при убийстве",
        "+23% к вероятности найти магический предмет",
      ],
      en: [
        "Level <span class='varies'>12-17</span> Meditation Aura When Equipped (varies)",
        "+35% Faster Cast Rate",
        "+<span class='varies'>200-260</span>% Enhanced Damage (varies)",
        "+9 To Minimum Damage",
        "<span class='varies'>180-250</span>% Bonus to Attack Rating (varies)",
        "Adds 5-30 Fire Damage",
        "+75 Poison Damage Over 5 Seconds",
        "+<span class='varies'>1-6</span> To Critical Strike (varies)",
        "+5 To All Attributes",
        "+2 To Mana After Each Kill",
        "23% Better Chance of Getting Magic Items",
      ],
    },
    complete: false,
  },

  {
    id: 19,
    name: {
      ru: "Рифма",
      en: "Rhyme",
    },
    runes: [13, 5],
    types: [16],
    excluded: "",
    classes: [],
    patch: "",
    level: 29,
    ladder: false,
    stats: {
      ru: [
        "+40% к скорости блока",
        "Вероятность 20% заблокировать удар",
        "Восполняет 15% маны",
        "+25% к сопротивлению всем видам урона",
        "Нельзя заморозить",
        "+50% к золоту за убийство монстров",
        "+25% к вероятности найти магический предмет",
      ],
      en: [
        "40% Faster Block Rate",
        "20% Increased Chance of Blocking",
        "Regenerate Mana 15%",
        "All Resistances +25",
        "Cannot Be Frozen",
        "50% Extra Gold From Monsters",
        "25% Better Chance Of Getting Magic Items",
      ],
    },
    complete: false,
  },

  {
    id: 21,
    name: {
      ru: "Мрак",
      en: "Black",
    },
    runes: [10, 16, 4],
    types: [10, 11, 2],
    excluded: "",
    classes: [],
    patch: "",
    level: 35,
    ladder: false,
    stats: {
      ru: [
        "+15% к скорости атаки",
        "+120% к урону",
        "+200 к рейтингу атаки",
        "+3-14 урона от льда",
        "+40% к вероятности нанести сокрушающий удар",
        "Отбрасывает врагов",
        "+10 к живучести",
        "-2 к магическому урону",
        "«Взрыв трупа» 4-го уровня (12 зарядов)",
      ],
      en: [
        "15% Increased Attack Speed",
        "+120% Enhanced Damage",
        "+200 To Attack Rating",
        "Adds 3-14 Cold Damage - Cold Duration 3 Seconds",
        "40% Chance Of Crushing Blow",
        "Knockback",
        "+10 To Vitality",
        "Magic Damage Reduced By 2",
        "Level 4 Corpse Explosion (12 Charges)",
      ],
    },
    complete: false,
  },

  {
    id: 22,
    name: {
      ru: "Белизна",
      en: "White",
    },
    runes: [14, 16],
    types: [14],
    excluded: "",
    classes: ["Necromancer"],
    patch: "",
    level: 35,
    ladder: false,
    stats: {
      ru: [
        "+3 к умениям ядов и костей (только для некромантов)",
        "+20% к скорости применения умений",
        "+2 к умению «Костяное копье» (только для некромантов)",
        "+4 у умению «Мастер скелетов» (только для некромантов)",
        "+3 к умению «Костяной доспех» (только для некромантов)",
        "+25% к вероятности обратить монстра в бегство при ударе",
        "+10 к живучести",
        "+13 к мане",
        "-4 к магическому урону",
      ],
      en: [
        "+3 To Poison And Bone Skills (Necromancer Only)",
        "20% Faster Cast Rate",
        "+2 To Bone Spear (Necromancer Only)",
        "+4 To Skeleton Mastery (Necromancer Only)",
        "+3 To Bone Armor (Necromancer Only)",
        "Hit Causes Monster To Flee 25%",
        "+10 To Vitality",
        "+13 To Mana",
        "Magic Damage Reduced By 4",
      ],
    },
    complete: false,
  },

  {
    id: 23,
    name: {
      ru: "Оплот",
      en: "Bulwark",
    },
    runes: [13, 16, 12],
    types: [18],
    excluded: "",
    classes: [],
    patch: "2.6",
    level: 35,
    ladder: true,
    stats: {
      ru: [
        "+20% к ускоренному восстановлению от удара",
        "Похищает <span class='varies'>4-6</span>% здоровья за удар",
        "+<span class='varies'>75-100</span>% к защите",
        "+10 к живучести",
        "+5% к максимальному запасу здоровья",
        "Восполняет +30 здоровья",
        "-7 к урону",
        "Физический урон уменьшен на <span class='varies'>10-15</span>%",
      ],
      en: [
        "+20% Faster Hit Recovery",
        "+<span class='varies'>4-6</span>% Life stolen per hit (varies)",
        "+<span class='varies'>75-100</span>% Enhanced Defense (varies)",
        "+10 to Vitality",
        "Increase Maximum Life 5%",
        "Replenish Life +30",
        "Damage Reduced by 7",
        "Physical Damage Received Reduced by <span class='varies'>10-15</span>% (varies)",
      ],
    },
    complete: false,
  },

  {
    id: 24,
    name: {
      ru: "Лекарство",
      en: "Cure",
    },
    runes: [13, 16, 7],
    types: [18],
    excluded: "",
    classes: [],
    patch: "",
    level: 35,
    ladder: true,
    stats: {
      ru: [
        "При надевании даёт ауру «Очищение» 1-го уровня",
        "+20% к ускоренному восстановлению от удара",
        "+<span class='varies'>75-100</span>% к защите",
        "+10 к живучести",
        "+5% к максимальному запасу здоровья",
        "+<span class='varies'>40-60</span>% к сопротивлению яду",
        "Сокращает время действия яда на 50%",
      ],
      en: [
        "Level 1 Cleansing Aura when Equipped",
        "+20% Faster Hit Recovery",
        "+75-100% Enhanced Defense",
        "+10 to Vitality",
        "Increase Maximum Life 5%",
        "Poison Resist +40-60%",
        "Poison Length Reduced by 50%",
      ],
    },
    complete: false,
  },

  {
    id: 28,
    name: {
      ru: "Память",
      en: "Memory",
    },
    runes: [17, 16, 12, 5],
    types: [5],
    excluded: "Not Orbs/Wands",
    classes: [],
    patch: "",
    level: 37,
    ladder: false,
    stats: {
      ru: [
        "+3 к уровню умений волшебницы",
        "+33% к скорости применения умений",
        "+9 к минимальному урону",
        "-25% к защите цели",
        "+3 к умению «Энергетический щит» (только для волшебниц)",
        "+2 к умению «Статическое поле» (только для волшебниц)",
        "+50% к защите",
        "+10 к живучести",
        "+10 к энергии",
        "+20% к максимальному запасу маны",
        "-7 к магическому урону",
      ],
      en: [
        "+3 to Sorceress Skill Levels",
        "33% Faster Cast Rate",
        "+9 To Minimum Damage",
        "-25% Target Defense",
        "+3 Energy Shield (Sorceress Only)",
        "+2 Static Field (Sorceress Only)",
        "+50% Enhanced Defense",
        "+10 To Energy",
        "+10 To Vitality",
        "Increase Maximum Mana 20%",
        "Magic Damage Reduced By 7",
      ],
    },
    complete: false,
  },

  {
    id: 29,
    name: {
      ru: "Дым",
      en: "Smoke",
    },
    runes: [4, 17],
    types: [17],
    excluded: "",
    classes: [],
    patch: "",
    level: 37,
    ladder: false,
    stats: {
      ru: [
        "+20% к ускоренному восстановлению от удара",
        "+75% к защите",
        "+280 к защите от снарядов",
        "+10 к энергии",
        "+50 к сопротивлению всем видам урона",
        "-1 к радиусу обзора",
        "«Немощность» 6-го уровня (18 зарядов)",
      ],
      en: [
        "20% Faster Hit Recovery",
        "+75% Enhanced Defense",
        "+280 Defense Vs. Missile",
        "+10 To Energy",
        "All Resistances +50",
        "-1 To Light Radius",
        "Level 6 Weaken (18 Charges)",
      ],
    },
    complete: false,
  },

  {
    id: 30,
    name: {
      ru: "Великолепие",
      en: "Splendor",
    },
    runes: [5, 17],
    types: [16],
    excluded: "",
    classes: [],
    patch: "1.10",
    level: 37,
    ladder: false,
    stats: {
      ru: [
        "+1 ко всем умениям",
        "+10% к скорости применения умений",
        "+20% к скорости блока",
        "+<span class='varies'>60-100</span>% к защите",
        "+10 к энергии",
        "Восполняет 15% маны",
        "+50% к золоту за убийство монстров",
        "+20% к вероятности найти магический предмет",
        "+3 к радиусу обзора",
      ],
      en: [
        "+1 To All Skills",
        "+10% Faster Cast Rate",
        "+20% Faster Block Rate",
        "+<span class='varies'>60-100</span>% Enhanced Defense (varies)",
        "+10 To Energy",
        "Regenerate Mana 15%",
        "50% Extra Gold From Monsters",
        "20% Better Chance of Getting Magic Items",
        "+3 To Light Radius",
      ],
    },
    complete: false,
  },

  {
    id: 31,
    name: {
      ru: "Мелодия",
      en: "Melody",
    },
    runes: [13, 18, 4],
    types: [6],
    excluded: "",
    classes: [],
    patch: "1.10",
    level: 39,
    ladder: false,
    stats: {
      ru: [
        "+3 к умениям обращения с луками и арбалетами (только для амазонок)",
        "+20% к скорости атаки",
        "+50% к урону",
        "+300% урона по нежити",
        "+3 к умению «Замедление снарядов» (только для амазонок)",
        "+3 к умению «Уклонение» (только для амазонок)",
        "+3 к умению «Критический удар» (только для амазонок)",
        "Отбрасывает врагов",
        "+10 к ловкости",
      ],
      en: [
        "+3 To Bow and Crossbow Skills (Amazon Only)",
        "20% Increased Attack Speed",
        "+50% Enhanced Damage",
        "+300% Damage To Undead",
        "+3 To Slow Missiles (Amazon Only)",
        "+3 To Dodge (Amazon Only)",
        "+3 To Critical Strike (Amazon Only)",
        "Knockback",
        "+10 To Dexterity",
      ],
    },
    complete: false,
  },

  {
    id: 32,
    name: {
      ru: "Гармония",
      en: "Harmony",
    },
    runes: [3, 6, 12, 18],
    types: [6],
    excluded: "",
    classes: [],
    patch: "1.10",
    level: 39,
    ladder: false,
    stats: {
      ru: [
        "При надевании дает ауру «Бодрость» 10-го уровня",
        "+<span class='varies'>200-275</span>% к урону",
        "+9 к минимальному урону",
        "+9 к максимальному урону",
        "+55-160 урона от огня",
        "+55-160 урона от молнии",
        "+55-160 урона от льда",
        "+<span class='varies'>2-6</span> к умению «Валькирия»",
        "+10 к ловкости",
        "Восполняет 20% маны",
        "+2 к мане при убийстве",
        "+2 к радиусу обзора",
        "«Оживление» 20-го уровня (25 зарядов)",
      ],
      en: [
        "Level 10 Vigor Aura When Equipped",
        "+<span class='varies'>200-275</span>% Enhanced Damage (varies)",
        "+9 To Minimum Damage",
        "+9 To Maximum Damage",
        "Adds 55-160 Fire Damage",
        "Adds 55-160 Lightning Damage",
        "Adds 55-160 Cold Damage",
        "+<span class='varies'>2-6</span> To Valkyrie (varies)",
        "+10 To Dexterity",
        "Regenerate Mana 20%",
        "+2 To Mana After Each Kill",
        "+2 To Light Radius",
        "Level 20 Revive (25 Charges)",
      ],
    },
    complete: false,
  },

  {
    id: 33,
    name: {
      ru: "Переполох",
      en: "Hustle",
    },
    runes: [13, 18, 2],
    types: [12, 17],
    excluded: "",
    classes: [],
    patch: "2.6",
    level: 39,
    ladder: true,
    stats: {
      ru: [
        "#Оружие#",
        "Вероятность 5% применить умение «Ускорение» 1-го уровня при ударе",
        "При надевании даёт ауру «Фанатизм» 1-го уровня",
        "+30% к скорости атаки",
        "+<span class='varies'>180-200</span>% к урону",
        "+75% урона по нежити",
        "+50 к рейтингу атаки против нежити",
        "+10 к ловкости",
        "#Броня#",
        "+65% к скорости ходьбы и бега",
        "+40% к скорости атаки",
        "+20% к ускоренному восстановлению от удара",
        "+6 к умению «Избежание»",
        "+10 к ловкости",
        "Выносливость снижается на 50% медленнее",
        "+10 к сопротивлению всем типам урона",
      ],
      en: [
        "#Weapons#",
        "5% Chance to cast level 1 Burst of Speed on striking",
        "Level 1 Fanaticism Aura",
        "+30% Increased Attack Speed",
        "+<span class='varies'>180-200</span>% Enhanced Damage (varies)",
        "+75% Damage to Undead",
        "+50 to Attack Rating against Undead",
        "+10 to Dexterity",
        "#Body Armors#",
        "+65% Faster Run/Walk",
        "+40% Increased Attack Speed",
        "+20% Faster Hit Recovery",
        "+6 to Evade",
        "+10 to Dexterity",
        "50% Slower Stamina Drain",
        "All Resistances +10",
      ],
    },
    complete: false,
  },

  {
    id: 34,
    name: {
      ru: "Львиное сердце",
      en: "Lionheart",
    },
    runes: [15, 17, 19],
    types: [17],
    excluded: "",
    classes: [],
    patch: "2.6",
    level: 41,
    ladder: false,
    stats: {
      ru: [
        "+20% к урону",
        "+25 к силе",
        "+15 к ловкости",
        "+20 к живучести",
        "+10 к энергии",
        "+50 к здоровью",
        "+30 к сопротивлению всем видам урона",
        "Требования -15%",
      ],
      en: [
        "+20% Enhanced Damage",
        "+25 To Strength",
        "+15 To Dexterity",
        "+20 To Vitality",
        "+10 To Energy",
        "+50 To Life",
        "All Resistances +30",
        "Requirements -15%",
      ],
    },
    complete: false,
  },

  {
    id: 35,
    name: {
      ru: "Послушание",
      en: "Obedience",
    },
    runes: [15, 18, 10, 5, 19],
    types: [9, 13],
    excluded: "",
    classes: [],
    patch: "1.10",
    level: 41,
    ladder: false,
    stats: {
      ru: [
        "Вероятность 30% применить умение «Чары» 21-го уровня при убийстве",
        "+40% к ускоренному восстановлению от удара",
        "+370% к урону",
        "-25% к защите цели",
        "+3-14 урона от льда",
        "-25% к сопротивлению огню у врага",
        "+40% к вероятности нанести сокрушающий удар",
        "+<span class='varies'>200-300</span> к защите",
        "+10 к силе",
        "+10 к ловкости",
        "+<span class='varies'>20-30</span> к сопротивлению всем видам урона",
        "Требования -20%",
      ],
      en: [
        "30% Chance To Cast Level 21 Enchant When You Kill An Enemy",
        "40% Faster Hit Recovery",
        "+370% Enhanced Damage",
        "-25% Target Defense",
        "Adds 3-14 Cold Damage 3 Second Duration (Normal)",
        "-25% To Enemy Fire Resistance",
        "40% Chance of Crushing Blow",
        "+<span class='varies'>200-300</span> Defense (varies)",
        "+10 To Strength",
        "+10 To Dexterity",
        "All Resistances +<span class='varies'>20-30</span> (varies)",
        "Requirements -20%",
      ],
    },
    complete: false,
  },

  {
    id: 37,
    name: {
      ru: "Изобилие",
      en: "Wealth",
    },
    runes: [20, 18, 3],
    types: [17],
    excluded: "",
    classes: [],
    patch: "",
    level: 43,
    ladder: false,
    stats: {
      ru: [
        "+10 к ловкости",
        "+2 к мане при убийстве",
        "+300% к золоту за убийство монстров",
        "+100% к вероятности найти магический предмет",
      ],
      en: [
        "+10 To Dexterity",
        "+2 To Mana After Each Kill",
        "300% Extra Gold From Monsters",
        "100% Better Chance Of Getting Magic Items",
      ],
    },
    complete: false,
  },

  {
    id: 41,
    name: {
      ru: "Вероломство",
      en: "Treachery",
    },
    runes: [13, 10, 20],
    types: [17],
    excluded: "",
    classes: ["Assassin"],
    patch: "1.11",
    level: 43,
    ladder: false,
    stats: {
      ru: [
        "Вероятность 25% применить умение «Яд» 15-го уровня при ударе",
        "Вероятность 5% применить умение «Уход в тень» 15-го уровня при получении урона",
        "+2 к умениям ассасина",
        "+45% к скорости атаки",
        "+20% к ускоренному восстановления после удара",
        "+30% к сопротивлению льду",
        "+50% к золоту за убийство монстров",
      ],
      en: [
        "25% Chance To Cast level 15 Venom On Striking",
        "5% Chance To Cast Level 15 Fade When Struck",
        "+2 To Assassin Skills",
        "+45% Increased Attack Speed",
        "+20% Faster Hit Recovery",
        "Cold Resist +30%",
        "50% Extra Gold From Monsters",
      ],
    },
    complete: false,
  },

  {
    id: 44,
    name: {
      ru: "Полумесяц",
      en: "Crescent Moon",
    },
    runes: [13, 22, 3],
    types: [1, 3, 9],
    excluded: "",
    classes: [],
    patch: "2.4",
    level: 47,
    ladder: false,
    stats: {
      ru: [
        "Вероятность 10% применить умение «Цепная молния» 17-го уровня при ударе",
        "Вероятность 7% применить умение «Статическое поле» 13-го уровня при ударе",
        "+20% к скорости атаки",
        "+<span class='varies'>180-220</span>% к урону",
        "Игнорирует защиту цели",
        "-35% к сопротивлению молнии у врага",
        "+25% к вероятности нанести открытую рану",
        "+<span class='varies'>9-11</span> поглощаемого магического урона",
        "+2 к мане при убийстве",
        "«Призрачный волк» 18-го уровня (30 зарядов)",
      ],
      en: [
        "10% Chance To Cast Level 17 Chain Lightning On Striking",
        "7% Chance To Cast Level 13 Static Field On Striking",
        "+20% Increased Attack Speed",
        "+<span class='varies'>180-220</span>% Enhanced Damage (varies)",
        "Ignore Target's Defense",
        "-35% To Enemy Lightning Resistance",
        "+25% Chance of Open Wounds",
        "+<span class='varies'>9-11</span> Magic Absorb (varies)",
        "+2 To Mana After Each Kill",
        "Level 18 Summon Spirit Wolf (30 Charges)",
      ],
    },
    complete: false,
  },

  {
    id: 45,
    name: {
      ru: "Принуждение",
      en: "Duress",
    },
    runes: [13, 22, 10],
    types: [17],
    excluded: "",
    classes: [],
    patch: "1.10",
    level: 47,
    ladder: false,
    stats: {
      ru: [
        "+40% к ускоренному восстановлению от удара",
        "+<span class='varies'>10-20</span>% к урону",
        "+37-133 урона от льда",
        "+15% к вероятности нанести сокрушающий удар",
        "+33% к вероятности нанести открытую рану",
        "+<span class='varies'>150-200</span>% к защите",
        "Выносливость снижается на 20% медленнее",
        "+45% к сопротивлению льду",
        "+15% к сопротивлению молнии",
        "+15% к сопротивлению огню",
        "+15% к сопротивлению яду",
      ],
      en: [
        "+40% Faster Hit Recovery",
        "+<span class='varies'>10-20</span>% Enhanced Damage (varies)",
        "Adds 37-133 Cold Damage 2 sec. Duration (Normal)",
        "15% Chance of Crushing Blow",
        "33% Chance of Open Wounds",
        "+<span class='varies'>150-200</span>% Enhanced Defense (varies)",
        "-20% Slower Stamina Drain",
        "Cold Resist +45%",
        "Lightning Resist +15%",
        "Fire Resist +15%",
        "Poison Resist +15%",
      ],
    },
    complete: false,
  },

  {
    id: 49,
    name: {
      ru: "Яд",
      en: "Venom",
    },
    runes: [7, 14, 23],
    types: [12],
    excluded: "",
    classes: [],
    patch: "1.11",
    level: 49,
    ladder: false,
    stats: {
      ru: [
        "Игнорирует защиту цели",
        "+273 урона от яда за 6 сек.",
        "Похищает 7% маны за удар",
        "Запрещает монстрам лечиться",
        "+25% к вероятности обратить монстра в бегство при ударе",
        "«Кольцо яда» 13-го уровня (11 зарядов)",
        "«Ядовитый взрыв» 15-го уровня (27 зарядов)",
      ],
      en: [
        "Ignore Target's Defense",
        "+273 Poison Damage Over 6 seconds",
        "7% Mana Stolen Per Hit",
        "Prevent Monster Heal",
        "Hit Causes Monster To Flee 25%",
        "Level 13 Poison Nova (11 Charges)",
        "Level 15 Poison Explosion (27 Charges)",
      ],
    },
    complete: false,
  },

  {
    id: 59,
    name: {
      ru: "Безмолвие",
      en: "Silence",
    },
    runes: [14, 2, 15, 24, 3, 26],
    types: [12],
    excluded: "",
    classes: [],
    patch: "",
    level: 55,
    ladder: false,
    stats: {
      ru: [
        "+2 ко всем умениям",
        "+20% к скорости атаки",
        "+20% к ускоренному восстановлению от удара",
        "+200% к урону",
        "+75% урона по нежити",
        "+50 к рейтингу атаки против нежити",
        "Похищает 11% маны за удар",
        "При ударе ослепляет цель +33",
        "+25% к вероятности обратить монстра в бегство при ударе",
        "+75 к сопротивлению всем видам урона",
        "+2 к мане при убийстве",
        "+30% к вероятности найти магический предмет",
        "Требования -20%",
      ],
      en: [
        "+2 To All Skills",
        "+20% Increased Attack Speed",
        "20% Faster Hit Recovery",
        "+200% Enhanced Damage",
        "+75% Damage To Undead",
        "+50 To Attack Rating Against Undead",
        "11% Mana Stolen Per Hit",
        "Hit Blinds Target +33",
        "Hit Causes Monster To Flee 25%",
        "All Resistances +75",
        "+2 To Mana After Each Kill",
        "30% Better Chance Of Getting Magic Items",
        "Requirements -20%",
      ],
    },
    complete: false,
  },

  {
    id: 60,
    name: {
      ru: "Сердце дуба",
      en: "Heart of the Oak",
    },
    runes: [18, 26, 21, 10],
    types: [5, 2],
    excluded: "",
    classes: [],
    patch: "1.10",
    level: 55,
    ladder: false,
    stats: {
      ru: [
        "+3 ко всем умениям",
        "+40% к скорости применения умений",
        "+75% к урону по демонам",
        "+100 к рейтингу атаки против демонов",
        "+3-14 урона от льда",
        "Похищает 7% маны за удар",
        "+10 к ловкости",
        "Восполняет +20 здоровья",
        "+15% к максимальному запасу маны",
        "+(30-40) к сопротивлению всем видам урона",
        "«Древесный дух» 4-го уровня (25/25 зарядов)",
        "«Ворон» 14-го уровня (60/60 зарядов)",
      ],
      en: [
        "+3 To All Skills",
        "+40% Faster Cast Rate",
        "+75% Damage To Demons",
        "+100 To Attack Rating Against Demons",
        "Adds 3-14 Cold Damage, 3 sec. Duration (Normal)",
        "7% Mana Stolen Per Hit",
        "+10 To Dexterity",
        "Replenish Life +20",
        "Increase Maximum Mana 15%",
        "All Resistances +<span class='varies'>30-40</span> (varies)",
        "Level 4 Oak Sage (25 Charges)",
        "Level 14 Raven (60 Charges)",
      ],
    },
    complete: false,
  },

  {
    id: 61,
    name: {
      ru: "Смерть",
      en: "Death",
    },
    runes: [15, 1, 26, 9, 25],
    types: [3, 1],
    excluded: "",
    classes: [],
    patch: "1.10",
    level: 55,
    ladder: false,
    stats: {
      ru: [
        "Не теряет прочности",
        "Вероятность 25% применить умение «Ледяной шип» 18-го уровня при атаке",
        "Вероятность 100% применить умение «Цепная молния» 44-го уровня после смерти",
        "+<span class='varies'>300-385</span>% к урону",
        "+20% к рейтингу атаки",
        "+50 к рейтингу атаки",
        "+1-50 урона от молнии",
        "Похищает 7% маны за удар",
        "+50% к вероятности нанести сокрушающий удар",
        "+(0.5%*clvl)% к вероятности нанести смертельный удар (зависит от уровня персонажа)",
        "+1 к радиусу обзора",
        "«Кровяной голем» 22-го уровня (15/15 зарядов)",
        "Требования -20%",
      ],
      en: [
        "Indestructible",
        "25% Chance To Cast Level 18 Glacial Spike On Attack",
        "100% Chance To Cast Level 44 Chain Lightning When You Die",
        "+<span class='varies'>300-385</span>% Enhanced Damage (varies)*",
        "20% Bonus To Attack Rating",
        "+50 To Attack Rating",
        "Adds 1-50 Lightning Damage",
        "7% Mana Stolen Per Hit",
        "50% Chance of Crushing Blow",
        "+(0.5 per Character Level) 0.5-49.5% Deadly Strike (Based on Character Level)",
        "+1 To Light Radius",
        "Level 22 Blood Golem  (15 Charges)",
        "Requirements -20%",
      ],
    },
    complete: false,
  },

  {
    id: 62,
    name: {
      ru: "Мерцающее пламя",
      en: "Flickering Flame",
    },
    runes: [4, 21, 26],
    types: [18],
    excluded: "",
    classes: [],
    patch: "2.4",
    level: 55,
    ladder: false,
    stats: {
      ru: [
        "При надевании даёт ауру «Сопротивление огню» (4-8)-го уровня",
        "+3 к умениям огня",
        "-(10-15)% к сопротивлению огню у врага",
        "+30% к защите",
        "+30 к защите от снарядов",
        "+(50-75) к мане",
        "+5% к максимальному сопротивлению огню",
        "Вдвое уменьшает время заморозки",
        "Сокращает время действия яда на 50%",
      ],
      en: [
        "Level <span class='varies'>4-8</span> Resist Fire Aura When Equipped (varies)",
        "+3 To Fire Skills",
        "-<span class='varies'>10-15</span>% to Enemy Fire Resistance (varies)",
        "+30% Enhanced Defense",
        "+30 Defense Vs. Missile",
        "+<span class='varies'>50-75</span> To Mana (varies)",
        "+5% To Maximum Fire Resist",
        "Half Freeze Duration",
        "Poison Length Reduced by 50%",
      ],
    },
    complete: false,
  },

  {
    id: 63,
    name: {
      ru: "Призыв к оружию",
      en: "Call to Arms",
    },
    runes: [11, 8, 23, 24, 27],
    types: [12],
    excluded: "",
    classes: [],
    patch: "1.10",
    level: 57,
    ladder: false,
    stats: {
      ru: [
        "+1 ко всем умениям",
        "+40% к скорости атаки",
        "+<span class='varies'>250-290</span>% к урону",
        "+5-30 урона от огня",
        "Похищает 7% здоровья за удар",
        "+<span class='varies'>2-6</span> к умению «Боевой призыв»",
        "+<span class='varies'>1-6</span> к умению «Боевые приказы»",
        "+<span class='varies'>1-4</span> к умению «Боевой клич»",
        "Запрещает монстрам лечиться",
        "Восполняет +12 здоровья",
        "+30% к вероятности найти магический предмет",
      ],
      en: [
        "+1 To All Skills",
        "+40% Increased Attack Speed",
        "+<span class='varies'>250-290</span>% Enhanced Damage (varies)",
        "Adds 5-30 Fire Damage",
        "7% Life Stolen Per Hit",
        "+<span class='varies'>2-6</span> To Battle Command (varies)*",
        "+<span class='varies'>1-6</span> To Battle Orders (varies)*",
        "+<span class='varies'>1-4</span> To Battle Cry (varies)*",
        "Prevent Monster Heal",
        "Replenish Life +12",
        "30% Better Chance of Getting Magic Items",
      ],
    },
    complete: false,
  },

  {
    id: 64,
    name: {
      ru: "Хаос",
      en: "Chaos",
    },
    runes: [19, 27, 22],
    types: [8],
    excluded: "",
    classes: ["Assassin"],
    patch: "1.10",
    level: 57,
    ladder: false,
    stats: {
      ru: [
        "Вероятность 9% применить умение «Морозная сфера» 11-го уровня при ударе",
        "Вероятность 11% применить умение «Залп молний» 9-го уровня при ударе",
        "+35% к скорости атаки",
        "+<span class='varies'>290-340</span>% к урону",
        "+216-471 магического урона",
        "+25% к вероятности нанести открытую рану",
        "+1 к умению «Вихрь»",
        "+10 к силе",
        "+15 к здоровью при убийстве демона",
      ],
      en: [
        "9% Chance To Cast Level 11 Frozen Orb On Striking",
        "11% Chance To Cast Level 9 Charged Bolt On Striking",
        "+35% Increased Attack Speed",
        "+<span class='varies'>290-340</span>% Enhanced Damage (varies)",
        "Adds 216-471 Magic Damage",
        "25% Chance of Open Wounds",
        "+1 To Whirlwind",
        "+10 To Strength",
        "+15 Life After Each Demon Kill",
      ],
    },
    complete: false,
  },

  {
    id: 65,
    name: {
      ru: "Изгнание",
      en: "Exile",
    },
    runes: [26, 27, 24, 14],
    types: [20],
    excluded: "",
    classes: ["Paladin"],
    patch: "1.10",
    level: 57,
    ladder: false,
    stats: {
      ru: [
        "Вероятность 15% применить умение «Похищение жизни» 5-го уровня при ударе",
        "При надевании дает ауру «Непокорность» <span class='varies'>13-16</span>-го уровня",
        "+2 к Боевым аурам (только для паладинов)",
        "+30% к скорости блока",
        "Замораживает цель",
        "+<span class='varies'>220-260</span>% к защите",
        "Восполняет +7 здоровья",
        "+5% к максимальному сопротивлению льду",
        "+5% к максимальному сопротивлению огню",
        "+25% к вероятности найти магический предмет",
        "Восполняет 1 ед. прочности каждые 4 сек.",
      ],
      en: [
        "15% Chance To Cast Level 5 Life Tap On Striking",
        "Level <span class='varies'>13-16</span> Defiance Aura When Equipped (varies)",
        "+2 To Offensive Auras (Paladin Only)",
        "+30% Faster Block Rate",
        "Freezes Target",
        "+<span class='varies'>220-260</span>% Enhanced Defense (varies)",
        "Replenish Life +7",
        "+5% To Maximum Cold Resist",
        "+5% To Maximum Fire Resist",
        "25% Better Chance Of Getting Magic Items",
        "Repairs 1 Durability in 4 Seconds",
      ],
    },
    complete: false,
  },

  {
    id: 66,
    name: {
      ru: "Сила духа",
      en: "Fortitude",
    },
    runes: [1, 12, 14, 28],
    types: [12, 17],
    excluded: "",
    classes: [],
    patch: "1.10",
    level: 59,
    ladder: false,
    stats: {
      ru: [
        "#Оружие#",
        "Вероятность 20% применить умение «Леденящий доспех» 15-го уровня при получении урона",
        "+25% к скорости применения умений",
        "+300% к урону",
        "+9 к минимальному урону",
        "+50 к рейтингу атаки",
        "20% к вероятности нанести смертельный удар",
        "25% к вероятности обратить монстра в бегство при ударе",
        "+200% к защите",
        "+X к здоровью (зависит от уровня персонажа)",
        "+<span class='varies'>25-30</span> к сопротивлению всем видам урона",
        "12% к урону, приходящемуся на ману",
        "+1 к радиусу обзора",
        "#Броня#",
        "Вероятность 20% применить умение «Леденящий доспех» 15-го уровня при получении урона",
        "+25% к скорости применения умений",
        "+300% к урону",
        "+200% к защите",
        "+15 к защите",
        "+X к здоровью (зависит от уровня персонажа)",
        "Восполняет +7 здоровья",
        "+5%к мксимальному сопротивлению молнии",
        "+<span class='varies'>25-30</span> к сопротивлению всем видам урона",
        "-7 к урону",
        "12% к урону, приходящемуся на ману",
        "+1 к радиусу обзора",
      ],
      en: [
        "#Weapons#",
        "20% Chance To Cast Level 15 Chilling Armor when Struck",
        "+25% Faster Cast Rate",
        "+300% Enhanced Damage",
        "+9 To Minimum Damage",
        "+50 To Attack Rating",
        "20% Deadly Strike",
        "Hit Causes Monster To Flee 25%",
        "+200% Enhanced Defense",
        "+X To Life (Based on Character Level)*",
        "All Resistances +<span class='varies'>25-30</span> (varies)",
        "12% Damage Taken Goes To Mana",
        "+1 To Light Radius",

        "#Body Armor#",
        "20% Chance To Cast Level 15 Chilling Armor when Struck",
        "+25% Faster Cast Rate",
        "+300% Enhanced Damage",
        "+200% Enhanced Defense",
        "+15 Defense",
        "+X To Life (Based on Character Level)*",
        "Replenish Life +7",
        "+5% To Maximum Lightning Resist",
        "All Resistances +<span class='varies'>25-30</span> (varies)",
        "Damage Reduced By 7",
        "12% Damage Taken Goes To Mana",
        "+1 To Light Radius",
      ],
    },
    complete: false,
  },

  {
    id: 68,
    name: {
      ru: "Терновник",
      en: "Bramble",
    },
    runes: [8, 27, 29, 5],
    types: [17],
    excluded: "",
    patch: "1.10",
    level: 61,
    ladder: false,
    stats: {
      ru: [
        "При надевании дает ауру «Шипы» <span class='varies'>15-21</span>-го уровня",
        "+50% к ускоренному восстановлению от удара",
        "+<span class='varies'>25-50</span>% урона умениями от яда",
        "+300 к защите",
        "+5% к максимальному запасу маны",
        "Восполняет 15% маны",
        "+5% к максимальному сопротивлению льду",
        "+30% к сопротивлению огню",
        "+100% к сопротивлению яду",
        "+13 к здоровью при убийстве",
        "«Терновый дух» 13-го уровня (33 зарядов)",
      ],
      en: [
        "Level <span class='varies'>15-21</span> Thorns Aura When Equipped (varies)",
        "+50% Faster Hit Recovery",
        "+<span class='varies'>25-50</span>% To Poison Skill Damage (varies)",
        "+300 Defense",
        "Increase Maximum Mana 5%",
        "Regenerate Mana 15%",
        "+5% To Maximum Cold Resist",
        "Fire Resist +30%",
        "Poison Resist +100%",
        "+13 Life After Each Kill",
        "Level 13 Spirit of Barbs (33 Charges)",
      ],
    },
    complete: false,
  },

  {
    id: 70,
    name: {
      ru: "Дракон",
      en: "Dragon",
    },
    runes: [29, 28, 12],
    types: [17, 16],
    excluded: "",
    patch: "1.10",
    level: 61,
    ladder: false,
    stats: {
      ru: [
        "Вероятность 12% применить умение «Гидра» 15-го уровня при ударе",
        "Вероятность 20% применить умение «Яд» 18-го уровня при получении урона",
        "При надевании дает ауру «Священный огонь» 14-го уровня",
        "+360 к защите",
        "+230 к защите от снарядов",
        "+<span class='varies'>3-5</span> ко всем характеристикам",
        "+(0.375*clvl) к силе (зависит от уровня персонажа)",
        "+5% к максимальному запасу маны (Только броня)",
        "+5 к максимальному сопротивлению молнии",
        "-7 к урону",
        "+50 к мане (Только щиты)",
      ],
      en: [
        "12% Chance To Cast Level 15 Hydra On Striking",
        "20% Chance to Cast Level 18 Venom When Struck",
        "Level 14 Holy Fire Aura When Equipped",
        "+360 Defense",
        "+230 Defense Vs. Missile",
        "+<span class='varies'>3-5</span> To All Attributes (varies)",
        "+0.375-37.125 To Strength (Based on Character Level)",
        "Increase Maximum Mana 5% (Armor Only)",
        "+50 To Mana (Shields Only)",
        "+5% To Maximum Lightning Resist",
        "Damage Reduced by 7",
      ],
    },
    complete: false,
  },

  {
    id: 71,
    name: {
      ru: "Зверь",
      en: "Beast",
    },
    runes: [30, 3, 22, 23, 17],
    types: [1, 7, 11],
    excluded: "",
    patch: "1.10",
    level: 63,
    ladder: false,
    stats: {
      ru: [
        "При надевании дает ауру «Фанатизм» 9-го уровня",
        "+40% к скорости атаки",
        "+<span class='varies'>240-270</span>% к урону",
        "+20% к вероятности нанести сокрушающий удар",
        "+25% к вероятности нанести открытую рану",
        "+3 к умению «Облик медведя»",
        "+3 к умению «Ликантропия»",
        "Запрещает монстрам лечиться",
        "+<span class='varies'>25-40</span> к силе",
        "+10 к энергии",
        "+2 к мане при убийстве",
        "«Гризли» 13-го уровня (5 зарядов)",
      ],
      en: [
        "Level 9 Fanaticism Aura When Equipped",
        "+40% Increased Attack Speed",
        "+<span class='varies'>240-270</span>% Enhanced Damage (varies)",
        "20% Chance of Crushing Blow",
        "25% Chance of Open Wounds",
        "+3 To Werebear",
        "+3 To Lycanthropy",
        "Prevent Monster Heal",
        "+<span class='varies'>25-40</span> To Strength (varies)",
        "+10 To Energy",
        "+2 To Mana After Each Kill",
        "Level 13 Summon Grizzly (5 Charges)",
      ],
    },
    complete: false,
  },

  {
    id: 74,
    name: {
      ru: "Бесконечность",
      en: "Infinity",
    },
    runes: [30, 23, 30, 24],
    types: [9, 13],
    excluded: "",
    patch: "1.10",
    level: 63,
    ladder: false,
    stats: {
      ru: [
        "Вероятность 50% применить умение «Цепная молния» 20-го уровня при убийстве",
        "При надевании дает ауру «Осуждение» 12-го уровня",
        "+35% к скорости ходьбы и бега",
        "+<span class='varies'>255-325</span>% к урону",
        "-<span class='varies'>45-55</span>% к сопротивлению молнии у врага",
        "+40% к вероятности нанести сокрушающий удар",
        "Запрещает монстрам лечиться",
        "+(0.5*clvl) к живучести (зависит от уровня персонажа)",
        "+30% к вероятности найти магический предмет",
        "«Ураганный доспех» 21-го уровня (30 зарядов)",
      ],
      en: [
        "50% Chance To Cast Level 20 Chain Lightning When You Kill An Enemy",
        "Level 12 Conviction Aura When Equipped",
        "+35% Faster Run/Walk",
        "+<span class='varies'>255-325</span>% Enhanced Damage (varies)",
        "-<span class='varies'>45-55</span>% To Enemy Lightning Resistance (varies)",
        "+40% Chance of Crushing Blow",
        "Prevent Monster Heal",
        "0.5-49.5 To Vitality (Based on Character Level)",
        "30% Better Chance of Getting Magic Items",
        "Level 21 Cyclone Armor (30 Charges)",
      ],
    },
    complete: false,
  },

  {
    id: 76,
    name: {
      ru: "Неистовство",
      en: "Fury",
    },
    runes: [31, 25, 5],
    types: [4],
    excluded: "",
    patch: "1.10",
    level: 65,
    ladder: false,
    stats: {
      ru: [
        "+40% к скорости атаки",
        "+209% к урону",
        "Игнорирует защиту цели",
        "-25% к защите цели",
        "+20% к рейтингу атаки",
        "Похищает 6% здоровья при ударе",
        "+33% к вероятности нанести смертельный удар",
        "+66% к вероятности нанести открытую рану",
        "+5 к умению «Берсерк» (только для варваров)",
        "Запрещает монстрам лечиться",
      ],
      en: [
        "+40% Increased Attack Speed",
        "+209% Enhanced Damage",
        "Ignore Target's Defense",
        "-25% Target Defense",
        "20% Bonus To Attack Rating",
        "6% Life Stolen Per Hit",
        "+33% Deadly Strike",
        "+66% Chance Of Open Wounds",
        "+5 To Frenzy (Barbarian Only)",
        "Prevent Monster Heal",
      ],
    },
    complete: false,
  },

  {
    id: 77,
    name: {
      ru: "Тайна",
      en: "Enigma",
    },
    runes: [31, 6, 30],
    types: [17],
    excluded: "",
    patch: "1.10",
    level: 65,
    ladder: false,
    stats: {
      ru: [
        "+2 ко всем умениям",
        "+45% к скорости ходьбы и бега",
        "+1 к умению «Телепортация»",
        "+<span class='varies'>750-775</span> к защите",
        "+(0.75*clvl) к силе (зависит от уровня персонажа)",
        "+5% к максимальному запасу здоровья",
        "Урон уменьшен на 8%",
        "+14 к здоровью при убийстве",
        "+15% к урону, приходящемуся на ману",
        "+(1*clvl)% к вероятности найти магический предмет (зависит от уровня персонажа)",
      ],
      en: [
        "+2 To All Skills",
        "+45% Faster Run/Walk",
        "+1 To Teleport",
        "+<span class='varies'>750-775</span> Defense (varies)",
        "+ (0.75 Per Character Level) +0-74 To Strength (Based On Character Level)",
        "Increase Maximum Life 5%",
        "Damage Reduced By 8%",
        "+14 Life After Each Kill",
        "15% Damage Taken Goes To Mana",
        "+ (1 Per Character Level) +1-99% Better Chance of Getting Magic Items (Based On Character Level)",
      ],
    },
    complete: false,
  },

  {
    id: 81,
    name: {
      ru: "Мечта",
      en: "Dream",
    },
    runes: [16, 31, 21],
    types: [18, 16],
    excluded: "",
    patch: "1.10",
    level: 65,
    ladder: false,
    stats: {
      ru: [
        "Вероятность 10% применить умение «Замешательство» 15-го уровня при ударе",
        "При надевании дает ауру «Священная молния» 15-го уровня",
        "+(20-30)% к ускоренному восстановлению от удара",
        "+30% к защите",
        "+(150-220) к защите",
        "+10 к живучести",
        "+(0.625*clvl) к мане (зависит от уровня персонажа)",
        "+(5-20) к сопротивлению всем видам урона",
        "+(12-25)% к вероятности найти магический предмет",
        "+5% к максимальному запасу здоровья (Только шлемы)",
        "+50 к здоровью (Только щиты)",
      ],
      en: [
        "10% Chance To Cast Level 15 Confuse When Struck",
        "Level 15 Holy Shock Aura When Equipped",
        "+<span class='varies'>20-30</span>% Faster Hit Recovery (varies)",
        "+30% Enhanced Defense",
        "+<span class='varies'>150-220</span> Defense (varies)",
        "+10 To Vitality",
        "Increase Maximum Life 5% (Helms Only)",
        "+50 To Life (Shields Only)",
        "+0.625-61.875 To Mana (Based On Character Level)",
        "All Resistances +<span class='varies'>5-20</span> (varies)",
        "<span class='varies'>12-25</span>% Better Chance of Getting Magic Items (varies)",
      ],
    },
    complete: false,
  },

  {
    id: 82,
    name: {
      ru: "Вера",
      en: "Faith",
    },
    runes: [27, 31, 20, 2],
    types: [6],
    excluded: "",
    patch: "1.10",
    level: 65,
    ladder: false,
    stats: {
      ru: [
        "При надевании дает ауру «Фанатизм» (12-15)-го уровня",
        "+<span class='varies'>1-2</span> ко всем умениям",
        "+330% к урону",
        "Игнорирует защиту цели",
        "+300% к рейтингу атаки",
        "+75% урона по нежити",
        "+50 к рейтингу атаки против нежити",
        "+120 урона от огня",
        "+15 к сопротивлению всем типам урона",
        "С вероятностью 10% возрождает как: Воскресший",
        "75% к золоту за убийство монстров",
      ],
      en: [
        "Level <span class='varies'>12-15</span> Fanaticism Aura When Equipped (varies)",
        "+<span class='varies'>1-2</span> To All Skills (varies)",
        "+330% Enhanced Damage",
        "Ignore Target's Defense",
        "300% Bonus To Attack Rating",
        "+75% Damage To Undead",
        "+50 To Attack Rating Against Undead",
        "+120 Fire Damage",
        "All Resistances +15",
        "10% Reanimate As: Returned",
        "75% Extra Gold From Monsters",
      ],
    },
    complete: false,
  },

  {
    id: 89,
    name: {
      ru: "Чума",
      en: "Plague",
    },
    runes: [32, 13, 22],
    types: [3, 8, 15],
    excluded: "",
    patch: "2.4",
    level: 67,
    ladder: false,
    stats: {
      ru: [
        "Вероятность 25% применить умение “Кольцо яда” 15-го уровня при ударе",
        "Вероятность 20% применить умение “Снижение сопротивления” 12-го уровня при получении урона",
        "При надевании даёт ауру «Очищение» <span class='varies'>13-17</span>-го уровня",
        "+<span class='varies'>1-2</span> ко всем умениям",
        "+20% к скорости атаки",
        "+<span class='varies'>220-320</span>% к урону",
        "-23% к сопротивлению яду у врага",
        "+(0.3*clvl)% к вероятности нанести смертельный удар (зависит от уровня персонажа)",
        "+25% к вероятности нанести открытую рану",
        "Замораживает цель +3",
      ],
      en: [
        "25% Chance to Cast level 15 Poison Nova on striking",
        "20% Chance to Cast level 12 Lower Resist when struck",
        "Level <span class='varies'>13-17</span> Cleansing Aura When Equipped (varies)",
        "+<span class='varies'>1-2</span> All Skills",
        "+20% Increased Attack Speed",
        "+<span class='varies'>220-320</span>% Enhanced Damage (varies)",
        "-23% To Enemy Poison Resistance",
        "0.3% (0-29.7) Deadly Strike (Based on Character Level)",
        "+25% Chance of Open Wounds",
        "Freezes Target +3",
      ],
    },
    complete: false,
  },

  {
    id: 91,
    name: {
      ru: "Метаморфоза",
      en: "Metamorphosis",
    },
    runes: [16, 32, 19],
    types: [18],
    excluded: "",
    classes: ["Druid"],
    patch: "2.6",
    level: 67,
    ladder: true,
    stats: {
      ru: [
        "Удары в облике волка активируют «Метку волка»",
        "Удары в облике медведя активируют «Метку медведя»",
        "+5 к умениям смены облика (только для друидов)",
        "+25% к вероятности нанести сокрушающий удар",
        "+<span class='varies'>50-80</span>% к защите",
        "+10 к силе",
        "+10 к живучести",
        "+10 к сопротивлению всем видам урона",
        "Нельзя заморозить",
      ],
      en: [
        "100% Chance to cast level 1 Mark of the Wolf on striking",
        "100% Chance to cast level 1 Mark of the Bear on striking",
        "+5 to Shape Shifting Skills (Druid only)",
        "+25% Chance of Crushing Blow",
        "+<span class='varies'>50-80</span>% Enhanced Defense",
        "+10 to Strength",
        "+10 to Vitality",
        "All Resistances +10",
        "Cannot be Frozen",
      ],
    },
    complete: false,
  },

  {
    id: 93,
    name: {
      ru: "Помешательство",
      en: "Obsession",
    },
    runes: [33, 24, 20, 17, 16, 4],
    types: [5],
    excluded: "",
    classes: [],
    patch: "2.4",
    level: 69,
    ladder: false,
    stats: {
      ru: [
        "Не теряет прочности",
        "Вероятность 24% применить умение «Немощность» 10-го уровня при получении урона",
        "+4 ко всем умениям",
        "+65% к скорости применения умений",
        "+60% к ускоренному восстановлению от удара",
        "Отбрасывает врагов",
        "+10 к живучести",
        "+10 к энергии",
        "+<span class='varies'>15-25</span>% к максимальному запасу здоровья",
        "Восполняет <span class='varies'>15-30</span>% маны",
        "+<span class='varies'>60-70</span> к сопротивлению всем видам урона",
        "+75% к золоту за убийство монстров",
        "30% к вероятности найти магический предмет",
      ],
      en: [
        "Indestructible",
        "24% Chance to cast level 10 Weaken when struck",
        "+4 To All Skills",
        "+65% Faster Cast Rate",
        "+60% Faster Hit Recovery",
        "Knockback",
        "+10 To Vitality",
        "+10 To Energy",
        "Increase Maximum Life <span class='varies'>15-25</span>% (varies)",
        "Regenerate Mana <span class='varies'>15-30</span>% (varies)",
        "All Resistances +<span class='varies'>60-70</span> (varies)",
        "75% Extra Gold from Monsters",
        "30% Better Chance of Getting Magic Items",
      ],
    },
    complete: false,
  },
];
