export const RUNEWORDS = [{
  id: 1,
  name: 'Nadir',
  runes: [4, 3],
  types: ['Helms'],
  level: 13,
  ladder: false,
  stats: [
    '+50% Enhanced Defense',
    '+10 Defense',
    '+30 Defense vs. Missile',
    'Level 13 Cloak of Shadows (9 Charges)',
    '+2 To Mana After Each Kill',
    '+5 To Strength',
    '-33% Extra Gold From Monsters',
    '-3 To Light Radius',
  ]
},{
  id: 2,
  name: 'Steel',
  runes: [3, 1],
  types: ['Swords', 'Axes', 'Maces'],
  level: 13,
  ladder: false,
  stats: [
    '20% Enhanced Damage',
    '+3 To Minimum Damage',
    '+3 To Maximum Damage',
    '+50 To Attack Rating',
    '50% Chance Of Open Wounds',
    '25% Increased Attack Speed',
    '+2 To Mana After Each Kill',
    '+1 To Light Radius',
  ]
},{
  id: 3,
  name: 'Malice',
  runes: [6, 1, 5],
  types: ['Melee Weapons'],
  level: 15,
  ladder: false,
  stats: [
    '+33% Enhanced Damage',
    '+9 To Maximum Damage',
    '100% Chance Of Open Wounds',
    '-25% Target Defense',
    '-100 To Monster Defense Per Hit',
    'Prevent Monster Heal',
    '+50 To Attack Rating',
    'Drain Life -5',
  ]
},{
  id: 4,
  name: 'Stealth',
  runes: [7, 5],
  types: ['Body Armors'],
  level: 17,
  ladder: false,
  stats: [
    'Magic Damage Reduced By 3',
    '+6 To Dexterity',
    '+15 To Maximum Stamina',
    'Poison Resist +30%',
    'Regenerate Mana 15%',
    '25% Faster Cast Rate',
    '25% Faster Hit Recovery',
  ]
},{
  id: 5,
  name: 'Leaf',
  runes: [3, 8],
  types: ['Staves'],
  excluded: 'Not Orbs/Wands',
  level: 19,
  ladder: false,
  stats: [
    'Adds 5-30 Fire Damage',
    '+3 To Fire Skills',
    '+3 To Fire Bolt (Sorceress Only)',
    '+3 To Inferno (Sorceress Only)',
    '+3 To Warmth (Sorceress Only)',
    '+2 To Mana After Each Kill',
    '+ (2 Per Character Level) +2-198 To Defense (Based On Character Level)',
    'Cold Resist +33%',
  ]
},{
  id: 6,
  name: "Ancient's Pledge",
  runes: [8, 9, 7],
  types: ['Shields'],
  excluded: '',
  level: 21,
  ladder: false,
  stats: [
    '+50% Enhanced Defense',
    'Cold Resist +43%',
    'Fire Resist +48%',
    'Lightning Resist +48%',
    'Poison Resist +48%',
    '10% Damage Goes To Mana',
  ]
},{
  id: 7,
  name: "Holy Thunder",
  runes: [5, 8, 9, 7],
  types: ['Scepters'],
  excluded: '',
  level: 21,
  ladder: false,
  stats: [
    '+60% Enhanced Damage',
    '-25% Target Defense',
    'Adds 5-30 Fire Damage',
    'Adds 21-110 Lightning Damage',
    '+75 Poison Damage Over 5 Seconds',
    '+10 To Maximum Damage',
    'Lightning Resistance +60%',
    '+5 To Maximum Lightning Resistance',
    '+3 To Holy Shock (Paladin Only)',
    'Level 7 Chain Lightning (60 Charges)',
  ]
},{
  id: 8,
  name: "Zephyr",
  runes: [9, 5],
  types: ['Missile Weapons'],
  excluded: '',
  level: 21,
  ladder: false,
  stats: [
    '+33% Enhanced Damage',
    '+66 To Attack Rating',
    'Adds 1-50 Lightning Damage',
    '-25% Target Defense',
    '+25 Defense',
    '25% Faster Run/Walk',
    '25% Increased Attack Speed',
    '7% Chance To Cast Level 1 Twister When Struck',
  ],
},{
  id: 9,
  name: "Pattern",
  runes: [7, 9, 10],
  types: ['Claws'],
  excluded: '',
  classes: ['Assassin'],
  patch: '2.4',
  level: 23,
  ladder: false,
  stats: [
    '+30% Faster Block Rate',
    '+40-80% Enhanced Damage (varies)',
    '10% Bonus to Attack Rating',
    'Adds 17-62 Fire Damage',
    'Adds 1-50 Lightning Damage',
    'Adds 3-14 Cold Damage',
    '+75 Poison Damage Over 5 Seconds',
    '+6 to Strength',
    '+6 to Dexterity',
    'All Resistances +15',
  ]
},{
  id: 10,
  name: "King's Grace",
  runes: [11, 8, 10],
  types: ['Swords', 'Scepters'],
  excluded: '',
  classes: [],
  patch: '',
  level: 25,
},{
  id: 11,
  name: "Strength",
  runes: [11, 3],
  types: ['Melee Weapons'],
  excluded: '',
  classes: [],
  patch: '',
  level: 25,
  ladder: false,
  stats: [
    '35% Enhanced Damage',
    '25% Chance Of Crushing Blow',
    '7% Life Stolen Per Hit',
    '+2 To Mana After Each Kill',
    '+ 20 To Strength',
    '+10 To Vitality',
  ]
},{
  id: 12,
  name: "Edge",
  runes: [3, 7, 11],
  types: ['Melee Weapons'],
  excluded: '',
  classes: [],
  patch: '1.10',
  level: 25,
},{
  id: 13,
  name: "Spirit",
  runes: [7, 10, 9, 11],
  types: ['Swords', 'Shields'],
  excluded: '',
  classes: [],
  patch: '1.10',
  level: 25,
},{
  id: 14,
  name: "Myth",
  runes: [15, 11, 4],
  types: ['Body Armors'],
  excluded: '',
  classes: ['Barbarian'],
  patch: '1.11',
  level: 25,
},{
  id: 15,
  name: "Honor",
  runes: [11, 1, 6, 3, 12],
  types: ['Melee Weapons'],
  excluded: '',
  classes: [],
  patch: '',
  level: 27,
},{
  id: 16,
  name: "Lore",
  runes: [9, 12],
  types: ['Helms'],
  excluded: '',
  classes: [],
  patch: '',
  level: 27,
},{
  id: 17,
  name: "Radiance",
  runes: [4, 12, 6],
  types: ['Helms'],
  excluded: '',
  classes: [],
  patch: '',
  level: 27,
  ladder: false,
  stats: [
    '+75% Enhanced Defense',
    '+30 Defense Vs. Missile',
    '+10 To Energy',
    '+10 To Vitality',
    '15% Damage Goes To Mana',
    'Magic Damage Reduced By 3',
    '+33 To Mana',
    'Damage Reduced By 7',
    '+5 To Light Radius',
  ]
},{
  id: 18,
  name: "Insight",
  runes: [8, 3, 7, 12],
  types: ['Missile Weapons', 'Polearms', 'Staves'],
  excluded: '',
  classes: [],
  patch: '1.10',
  level: 27,
},{
  id: 19,
  name: "Rhyme",
  runes: [13, 5],
  types: ['Shields'],
  excluded: '',
  classes: [],
  patch: '',
  level: 29,
  ladder: false,
  stats: [
    '20% Increased Chance of Blocking',
    '40% Faster Block Rate',
    'All Resistances +25',
    'Regenerate Mana 15%',
    'Cannot Be Frozen',
    '50% Extra Gold From Monsters',
    '25% Better Chance Of Getting Magic Items',
  ]
},{
  id: 20,
  name: "Rhyme",
  runes: [13, 5],
  types: ['Shields'],
  excluded: '',
  classes: [],
  patch: '',
  level: 29,
},{
  id: 21,
  name: "Peace",
  runes: [13, 10, 11],
  types: ['Body Armors'],
  excluded: '',
  classes: ['Amazon'],
  patch: '',
  level: 29,
},{
  id: 22,
  name: "Black",
  runes: [10, 16, 4],
  types: ['Clubs', 'Hammers', 'Maces'],
  excluded: '',
  classes: [],
  patch: '',
  level: 35,
},{
  id: 23,
  name: "White",
  runes: [14, 16],
  types: ['Wands'],
  excluded: '',
  classes: ['Necromancer'],
  patch: '',
  level: 35,
},{
  id: 24,
  name: "Bulwark",
  runes: [13, 16, 12],
  types: ['Helms'],
  excluded: '',
  classes: [],
  patch: '2.6',
  level: 35,
  ladder: true,
},{
  id: 25,
  name: "Cure",
  runes: [13, 16, 7],
  types: ['Helms'],
  excluded: '',
  classes: [],
  patch: '',
  level: 35,
  ladder: true,
},{
  id: 26,
  name: "Ground",
  runes: [13, 16, 9],
  types: ['Helms'],
  excluded: '',
  classes: [],
  patch: '',
  level: 35,
  ladder: true,
},{
  id: 27,
  name: "Hearth",
  runes: [13, 16, 10],
  types: ['Helms'],
  excluded: '',
  classes: [],
  patch: '',
  level: 35,
  ladder: true,
},{
  id: 28,
  name: "Temper",
  runes: [13, 16, 8],
  types: ['Helms'],
  excluded: '',
  classes: [],
  patch: '',
  level: 35,
  ladder: true,
},{
  id: 29,
  name: "Memory",
  runes: [17, 16, 12, 5],
  types: ['Staves'],
  excluded: 'Not Orbs/Wands',
  classes: [],
  patch: '',
  level: 37,
  ladder: false,
},{
  id: 29,
  name: "Smoke",
  runes: [4, 17],
  types: ['Body Armors'],
  excluded: '',
  classes: [],
  patch: '',
  level: 37,
  ladder: false,
  stats: [
    '+75% Enhanced Defense',
    '+280 Defense Vs. Missile',
    'All Resistances +50',
    '20% Faster Hit Recovery',
    'Level 6 Weaken (18 Charges)',
    '+10 To Energy',
    '-1 To Light Radius',
  ]
},{
  id: 29,
  name: "Splendor",
  runes: [5, 17],
  types: ['Shields'],
  excluded: '',
  classes: [],
  patch: '1.10',
  level: 37,
  ladder: false,
},{
  id: 29,
  name: "Melody",
  runes: [13, 18, 4],
  types: ['Missile Weapons'],
  excluded: '',
  classes: [],
  patch: '1.10',
  level: 39,
  ladder: false,
}];
